### ISSUE TITLE
CoffeeScript: sails lift error

### ISSUE THREAD

**Issue by adambiggs** [balderdashy/sails#1194]
Trying to write server code in CoffeeScript. Converted all the `api/*` files and everything seemed to work fine, but after converting the `config/*` files, `$ sails lift` now throws an error:

```
/Users/adam/[project-name]/config/400.coffee:1
(function (exports, require, module, __filename, __dirname) { ###
                                                              ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/adam/.nvm/v0.10.22/lib/node_modules/sails/node_modules/include-all/index.js:96:53
    at Array.forEach (native)
    at requireAll (/Users/adam/.nvm/v0.10.22/lib/node_modules/sails/node_modules/include-all/index.j
```

Running the app with `coffee` or `nodemon` works fine, only `sails lift` doesn't work.

I tried adding `require("coffee-script")` in `app.coffee` but that didn't make a difference.

Anybody know what I might be doing wrong?

**Comment by VoidVolker** [comment]
Same bug at server (centos), but at local system (fedora) all works good - all files are same, node version same :(
