### ISSUE TITLE
cookie parsing in socket.io interpreter needs try..catch wrapper in 0.10.x

### ISSUE THREAD

**Issue by krzysztofantczak** [balderdashy/sails#1206]
Hello,

While working on python client which consumes websockets API created with sails, i've noticed that it's pretty trivial to crash sails while connecting to it with invalid(?) cookie. I've tested it on all of my apps + on fresh sails project (sails 0.9.7 under OSX 10.9) all of them are ending up with:

```
debug: Lowering sails...

/usr/local/lib/node_modules/sails/node_modules/express/node_modules/connect/lib/utils.js:198
  return 0 == str.indexOf('s:')
                  ^
TypeError: Cannot call method 'indexOf' of undefined
    at exports.parseSignedCookie (/usr/local/lib/node_modules/sails/node_modules/express/node_modules/connect/lib/utils.js:198:19)
    at Manager.socketAttemptingToConnect (/usr/local/lib/node_modules/sails/lib/hooks/sockets/authorization.js:35:26)
    at Manager.authorize (/usr/local/lib/node_modules/sails/node_modules/socket.io/lib/manager.js:910:31)
    at Manager.handleHandshake (/usr/local/lib/node_modules/sails/node_modules/socket.io/lib/manager.js:786:8)
    at Manager.handleRequest (/usr/local/lib/node_modules/sails/node_modules/socket.io/lib/manager.js:593:12)
    at Server.<anonymous> (/usr/local/lib/node_modules/sails/node_modules/socket.io/lib/manager.js:119:10)
    at Server.EventEmitter.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2108:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1966:22)
    at TCP.onread (net.js:525:27)
```

I didn't had much time to investigate it more to be able to report some more details about source of that problem (which can exists ie. in connect itself), but it seems to be really ugly bug from my point of view, so i figured i'll let You guys know about it asap.

Python code which i'm using to crash it is pretty simple:

```
from socketIO_client import SocketIO

def main():
    socketIO = SocketIO('localhost', 1337, cookies={'a': 'aaa'})

if __name__ == '__main__':
    main()
```

Note: You need to install socketio-client ie. with: pip install socketIO-client

**Comment by khmereshop** [comment]
This issue cause by angular cookie that set by google. The cookie look like this in Safari browser, _ga=GA1.1.1279493516.1422988925 . I don't know why google automatic set up google cookie to Safari. It happen to only Safari browser. Then socket io cause error like you mention in this question. What is the best way to fix it? I can't get rid off _ga cookie either with sails js 0.10.5 version.
