### ISSUE TITLE
Sails@0.10 crushes on REST request if model has custom primary key

### ISSUE THREAD

**Issue by generalov** [balderdashy/sails#1381]
I have a MySQL database with table user_profile and fields (*user_id, first_name, last_name), where user_id is a primary key, and I try Sails to implement REST interface.

I generate UserProfile model connected with sails-mysql:

```
module.exports = {
    identity: 'user_profile',
    tableName: 'user_profile',
    autoPk: false,
    autoCreatedAt: false,
    autoUpdatedAt: false,
    attributes: {
        user_id: {
            type: 'integer',
            primaryKey: true
        },
        first_name: 'string',
        last_name: 'string'
    }

};
```

And controller User_ProfileController for it:

```
module.exports = {

};
```

When I open http://localhost:1337/user_profile/
I expect to see a some JSON
But Sails chrushes with trace:

```
Error: Must specify an `id` when calling `Model.room(id)`
    at bound.room (/x/node_modules/sails/lib/hooks/pubsub/index.js:384:20)
    at bound [as room] (/x/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /x/node_modules/sails/lib/hooks/pubsub/index.js:467:63
    at Function.forEach (/x/node_modules/sails/node_modules/lodash/dist/lodash.js:3297:15)
    at bound.subscribe (/x/node_modules/sails/lib/hooks/pubsub/index.js:464:7)
    at bound [as subscribe] (/x/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at found (/x/node_modules/sails/lib/hooks/blueprints/actions/find.js:145:11)
    at _normalizeCallback.callback.success (/x/node_modules/sails/node_modules/waterline/node_modules/node-switchback/lib/normalize.js:33:26)
    at _switch (/x/node_modules/sails/node_modules/waterline/node_modules/node-switchback/lib/factory.js:34:26)
    at returnResults (/x/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:259:9)
```

I try to dump 'models' near sails/lib/hooks/pubsub/index.js:464:7, it's really where is no 'id' field in object array:

```
[ { user_id: 1, first_name: 'John', last_name: 'Smith' },
   ...
]
```

and var ids = _.pluck(models,'id'); creates array of `undefined`.

**Comment by ckszabi** [comment]
The same error message (**Must specify an 'id' when calling 'Model.room(id)'**) is logged also in the case of **id being 0**.

I the sails/lib/hooks/pubsub/index.js room function:

`
if (!id) return sails.log.error('Must specify an 'id' when calling 'Model.room(id)')
`

the ` if (!id) ` is true also when id equals 0, 
but id being 0 is very acceptable as value for primary key, so the if is not quite correct. Should it be like ` if (id === undefined) ` ?

We solved it the easy way by not using 0 values :wink:
