### ISSUE TITLE
Cleaning up/ Rolling Back database after integration tests

### ISSUE THREAD

**Issue by cwadding** [balderdashy/sails#1554]
I am using `supertest` to test the sails controller but I would like to clean up or rollback the database after each test. Can someone propose some insight into how I would do this? I am using the current latest version of sails 0.10.0-rc4. Here is some sample code that I have to launch the sails app which I got from [Issue 565](https://github.com/balderdashy/sails/issues/565):

```
// Require app factory
var Sails = require('sails/lib/app');

// Instantiate the Sails app instance we'll be using
// (note that we don't use `new`, just call it like a function)
var app = Sails();

before(function(done) {
    this.timeout(10000);
    // Lift Sails and store the app reference
    app.lift({

        // Basic options you should pretty much always use for tests:
        /////////////////////////////////////////////////////////////////////////////

        // turn down the log level so we can view the test results
        log: {
            level: 'error'
        },

       // Prevent global variables from being exposed
       // (shouldn't matter in most cases, but not a bad idea when running tests)
       // globals: false,


       // Examples of other stuff you might want:
       /////////////////////////////////////////////////////////////////////////////

        // send test database connections down if needed
        // connections: {
        //     mysql: {
        //         adapter: 'sails-mysql',
        //         host: 'localhost',
        //         database: 'test',
        //         user: 'root',
        //         pass: ' '
        //     }
        // },

        // or any other configuration you like that you would normally have in config files
        // ....


        // Additionally, you get a couple of other options when using Sails programmatically this     way.
        // Please note that this usage may change in future versions of Sails
        // (but barring any crazy circumstances, backwards compatibility will be maintained)
       /////////////////////////////////////////////////////////////////////////////

        // Choose which hooks to load
        // NOTE: if you use this option, ONLY these hooks will be loaded
        // loadHooks: ['moduleloader', 'userconfig', 'orm'],


        // Or override some hooks:
        // (NOTE: if you just want to disable one or two hooks, you can set them to false here.)
        hooks: {
           grunt: false
        }

    }, done);
});


// After Function
after(function(done) {
    app.lower(done);
});
```

I was going to rollback the database changes in an afterEach hook:

```
afterEach(function(done){
    // What code should go in here to roll back my database changes
    done();
});    
```

**Comment by Crusader4Christ** [comment]
@xpepermint Good idea but no luck:
models: { migrate: 'drop' } leads to  this error
```
[Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: ER_ROW_IS_REFERENCED: Cannot delete or update a parent row: a foreign key constraint fails

Error (E_UNKNOWN) :: Encountered an unexpected error
Error (E_UNKNOWN) :: Encountered an unexpected error
: ER_ROW_IS_REFERENCED: Cannot delete or update a parent row: a foreign key constraint fails
    at Query.Sequence._packetToError (node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
    --------------------
    at Protocol._enqueue (node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at PoolConnection.query (node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:201:25)
    at dropTable (node_modules/sails-mysql/lib/adapter.js:275:22)
    at node_modules/sails-mysql/lib/adapter.js:287:11
    at node_modules/sails-mysql/node_modules/async/lib/async.js:52:16
    at iterate (node_modules/sails-mysql/node_modules/async/lib/async.js:260:24)
    at Object.async.forEachOfSeries.async.eachOfSeries (node_modules/sails-mysql/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (node_modules/sails-mysql/node_modules/async/lib/async.js:214:22)
    at __DROP__ (node_modules/sails-mysql/lib/adapter.js:285:15)
    at afterwards (node_modules/sails-mysql/lib/connections/spawn.js:84:5)
    at node_modules/sails-mysql/lib/connections/spawn.js:40:7
    at Handshake.onConnect (node_modules/sails-mysql/node_modules/mysql/lib/Pool.js:59:7)
    at Handshake.Sequence.end (node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Handshake.Sequence.OkPacket (node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
    at Protocol._parsePacket (node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
```
BTW how can I get normal error message and trace?
