### ISSUE TITLE
connect-mongo error after updating to sails 0.10.0-rc8

### ISSUE THREAD

**Issue by ArVan** [balderdashy/sails#1852]
Hi.
I just updated to version 0.10.0-rc8, and get the following error if I use mongo adapter as session store:

```
error: Could not load Connect session adapter :: connect-mongo

Error from adapter:
Error: Cannot find module '/nodejs/testApi/node_modules/connect-mongo/package.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Hook.Session.initialize (/usr/local/lib/node_modules/sails/lib/hooks/session/index.js:197:34)
    at Hook.bound [as initialize] (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /usr/local/lib/node_modules/sails/lib/hooks/index.js:124:33
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:425:17
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:419:17
    at Array.forEach (native)

Do you have the Connect session adapter installed in this project?
Try running the following command in your project's root directory:
npm install connect-mongo
(Note: Make sure the version of the Connet adapter you install is compatible with Express 3/Sails v0.10)
```

**Comment by kanecko** [comment]
I am having this issue. I've created a brand new v0.10 project and later updated to v0.10.5. I have enabled/installed mongodb after the 0.10.5 update.

**Comment by gilesbutler** [comment]
+1 for this! Having the same issues on Sails v0.10.5

For now im using the temporary fix mentioned above ````npm install connect-mongo@0.4.*```` and it's working but I have different Mongo configurations in env/development.js and env/production.js - Does anyone know the best way to configure sessions to use the different configurations?

At the moment in my config/session.js I have the following:
````
  adapter: 'mongo',
  url: process.env.MONGO_URL,
  collection: 'sessions',
````
This is working for my production setup but now local setup isn't working because I need to use:
````
  adapter: 'mongo',
  host: 'localhost',
  port: 27017,
  db: 'sails-dev',
  collection: 'sessions',
```` 
Appreciate any help anybody can offer.

**Comment by djlovegrind** [comment]
Idk if anyone is still checking on here, but which version of connect-mongo is recommended to be using with ``sails`` and ``sails-mongo`` at v ``^0.11``? I can't find this info anywhere.

**Comment by tjwebb** [comment]
The latest `connect-mongo` on npm is 0.8.2, which should work. They also claim that the upcoming 1.x series will be compatible, so I think `npm install connect-mongo --save` should be all you need.

**Comment by ram-you** [comment]
The latest connect-mongo 1.1.0 doesn't work. 
Switching to "connect-mongo": "^0.8.2"    works.

Sails : v 0.11.4

**Comment by frutality** [comment]
@ram-you +1
I have exactly same situation. Thanks for the fix. 0.8.2 works.

**Comment by parkeragee** [comment]
The 0.8.2 fix crashes Heroku apps:

```
2016-01-14T14:15:38.355766+00:00 app[web.1]: > node app.js
2016-01-14T14:15:38.355766+00:00 app[web.1]: 
2016-01-14T14:15:41.185732+00:00 app[web.1]: Could not load Connect session adapter :: connect-mongo
2016-01-14T14:15:41.178170+00:00 app[web.1]: Thu, 14 Jan 2016 14:15:41 GMT connect-mongo deprecated auto_reconnect option is deprecated. Use autoReconnect instead at node_modules/sails/lib/hooks/session/index.js:169:37
2016-01-14T14:15:41.185735+00:00 app[web.1]: 
2016-01-14T14:15:41.185738+00:00 app[web.1]:     at new MongoStore (/app/node_modules/connect-mongo/lib/connect-mongo.js:114:19)
2016-01-14T14:15:41.185739+00:00 app[web.1]:     at Hook.SessionHook.initialize (/app/node_modules/sails/lib/hooks/session/index.js:169:37)
2016-01-14T14:15:41.185743+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:441:17
2016-01-14T14:15:41.185745+00:00 app[web.1]:     at Immediate.taskComplete (/app/node_modules/async/lib/async.js:440:13)
2016-01-14T14:15:41.185741+00:00 app[web.1]:     at /app/node_modules/sails/lib/hooks/index.js:74:14
2016-01-14T14:15:41.185746+00:00 app[web.1]: 
2016-01-14T14:15:41.185742+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:451:17
2016-01-14T14:15:41.185745+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:383:17)
2016-01-14T14:15:41.185747+00:00 app[web.1]: Try running the following command in your project's root directory:
2016-01-14T14:15:41.185747+00:00 app[web.1]: Do you have the Connect session adapter installed in this project?
2016-01-14T14:15:41.185744+00:00 app[web.1]:     at _each (/app/node_modules/async/lib/async.js:46:13)
2016-01-14T14:15:41.185741+00:00 app[web.1]:     at Hook.bound [as initialize] (/app/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
2016-01-14T14:15:41.185749+00:00 app[web.1]: 
2016-01-14T14:15:41.185749+00:00 app[web.1]: (Note: Make sure the version of the Connect adapter you install is compatible with Express 3/Sails v0.10)
2016-01-14T14:15:41.185736+00:00 app[web.1]: Error from adapter:
2016-01-14T14:15:41.185737+00:00 app[web.1]: TypeError: _.assign is not a function
2016-01-14T14:15:41.185748+00:00 app[web.1]: npm install connect-mongo
2016-01-14T14:15:41.182572+00:00 app[web.1]: A hook (`session`) failed to load!
2016-01-14T14:15:41.557171+00:00 app[web.1]: A hook (`orm`) failed to load!
2016-01-14T14:16:36.222217+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2016-01-14T14:16:36.222217+00:00 heroku[web.1]: Stopping process with SIGKILL
2016-01-14T14:16:37.102017+00:00 heroku[web.1]: State changed from starting to crashed
2016-01-14T14:16:37.097839+00:00 heroku[web.1]: Process exited with status 137
```

**Comment by mikermcneil** [comment]
@ram-you @frutality more info re: connect-mongo and the latest version of Sails here: https://github.com/balderdashy/sails/issues/3486


@parkeragee hmm - I'd suggest clearing the Heroku NPM cache (it looks like something could be going on with npm 3 and flattened deps, since it's trying to access a lodash method which doesn't exist, indicating it might be using a different version)  If you continue to see this, would you open a new issue?

**Comment by ram-you** [comment]
Hi @mikermcneil , in the update https://github.com/balderdashy/sails-docs/commit/fdad9983f9cd1300886b66f4facb67af18a93fb0 
you saied : 

 > For example to use Mongo as your session store, you should use version 0.8.4 of `connect-mongo`.  First, run the following from your project's directory:
  
>npm install sails-mongo@0.8.4 --save

But there are neither `0.8.4` version of `connect-mongo` nor of `sails-mongo`

Thanks.
