### ISSUE TITLE
[unit test] when sails is really ready

### ISSUE THREAD

**Issue by stormslowly** [balderdashy/sails#1937]
in my test case i lower the sails when it's lifted. but error thrown.
here is code. and the workaround is to set a timeout to lower it.
so in my opinion when the callback in the lift is called,  the sails is not really ready.

is there any to determing if the sails is really ready( lowerable ?)

thx a lot

```
describe('sails:liftandlower', function() {
  it('shoud be no error', function(done) {
    sails.lift({
        rootPath: process.cwd(),
        log: {
          level: 'info'
        },
      },
      function(err, sailsApp) {
        console.log('================ ready ?');
        // setTimeout(function(){
        sailsApp.lower(done);
        // },1000 );
      });
  });
});

```

```
sails -v
info: v0.9.16
```

outpout
```
.error: Trying to start server on port 1337...But something else is already running on that port!Please disable the other server, or choose a different port, and try again.
.

  1 passing (993ms)
  1 failing

  1) sails:liftandlower shoud be no error:
     Uncaught Error: Trying to start server on port 1337...But something else is already running on that port!Please disable the other server, or choose a different port, and try again.
      at Array.async.auto.verify [as 1] (D:\userdata\pshu\Application Data\npm\node_modules\sails\lib\express\start.js:49:12)
      at listener (D:\userdata\pshu\Application Data\npm\node_modules\sails\node_modules\async\lib\async.js:462:46)
      at D:\userdata\pshu\Application Data\npm\node_modules\sails\node_modules\async\lib\async.js:416:17
      at Array.forEach (native)
      at _each (D:\userdata\pshu\Application Data\npm\node_modules\sails\node_modules\async\lib\async.js:32:24)
      at Object.taskComplete (D:\userdata\pshu\Application Data\npm\node_modules\sails\node_modules\async\lib\async.js:415:13)
      at processImmediate [as _immediateCallback] (timers.js:330:15)
```
j

**Comment by stormslowly** [comment]
sails v0.10.x  solve this problem.
