### ISSUE TITLE
Cross-Origin Resource Sharing problem

### ISSUE THREAD

**Issue by jyoungrok** [balderdashy/sails#1952]
Hello I commented  below writing at https://github.com/balderdashy/sails/issues/1206#issuecomment-48582352
 
Please check it!
thank you
 
Hello @mikermcneil 
I launched server (version = v0.10.0-rc8 )
I have same error likes below.
(As casoetan says, I can emit this error after browser to localhost:1337)

error: Could not load session for socket #qjtt-C4ZSeotyh9Kexut
error: The socket's cookie could not be parsed into a sessionID.
error: Unless you're overriding the authorization function, make sure you pass in a valid sails.sidcookie
error: (or omit the cookie altogether to have a new session created and an encrypted cookie sent in the response header to your socket.io upgrade request)
error: TypeError: Cannot call method 'indexOf' of undefined
at exports.parseSignedCookie (/usr/src/nodejs/lib/node_modules/sails/node_modules/express/node_modules/connect/lib/utils.js:199:19)
at Object.Session.fromSocket (/usr/src/nodejs/lib/node_modules/sails/lib/hooks/session/index.js:339:38)
at SocketNamespace.onConnect (/usr/src/nodejs/lib/node_modules/sails/lib/hooks/sockets/lib/connection.js:45:18)
at SocketNamespace.emit as $emit
at connect (/usr/src/nodejs/lib/node_modules/sails/node_modules/socket.io/lib/namespace.js:292:10)
at /usr/src/nodejs/lib/node_modules/sails/node_modules/socket.io/lib/namespace.js:308:13
at SocketNamespace.authorize (/usr/src/nodejs/lib/node_modules/sails/node_modules/socket.io/lib/namespace.js:252:5)
at SocketNamespace.handlePacket (/usr/src/nodejs/lib/node_modules/sails/node_modules/socket.io/lib/namespace.js:302:14)
at Manager.handleClient (/usr/src/nodejs/lib/node_modules/sails/node_modules/socket.io/lib/manager.js:721:32)
at Manager.handleUpgrade (/usr/src/nodejs/lib/node_modules/sails/node_modules/socket.io/lib/manager.js:641:8) [TypeError: Cannot call method 'indexOf' of undefined]
error: Could not load session for socket #qjtt-C4ZSeotyh9Kexut
error: The socket's cookie could not be parsed into a sessionID.
error: Unless you're overriding the authorization function, make sure you pass in a valid sails.sidcookie
error: (or omit the cookie altogether to have a new session created and an encrypted cookie sent in the response header to your socket.io upgrade request)
error: TypeError: Cannot call method 'indexOf' of undefined
at exports.parseSignedCookie (/usr/src/nodejs/lib/node_modules/sails/node_modules/express/node_modules/connect/lib/utils.js:199:19)
at Object.Session.fromSocket (/usr/src/nodejs/lib/node_modules/sails/lib/hooks/session/index.js:339:38)
at interpretSocketReq (/usr/src/nodejs/lib/node_modules/sails/lib/hooks/sockets/lib/interpreter/interpret.js:542:19)
at Socket. (/usr/src/nodejs/lib/node_modules/sails/lib/hooks/sockets/lib/connection.js:95:5)
at Socket.emit as $emit
at SocketNamespace.handlePacket (/usr/src/nodejs/lib/node_modules/sails/node_modules/socket.io/lib/namespace.js:335:22)
at Manager.onClientMessage (/usr/src/nodejs/lib/node_modules/sails/node_modules/socket.io/lib/manager.js:518:38)
at WebSocket.Transport.onMessage (/usr/src/nodejs/lib/node_modules/sails/node_modules/socket.io/lib/transport.js:369:20)
at Parser. (/usr/src/nodejs/lib/node_modules/sails/node_modules/socket.io/lib/transports/websocket/hybi-16.js:39:10)
at Parser.emit (events.js:95:17) [TypeError: Cannot call method 'indexOf' of undefined]

I saw you say this error is fixed in sails beta version.
But it still exists.
Please comment!

**Comment by timestep** [comment]
@loicsaintroch @jyoungrok  Can you guys open this issue again? This hasn't been resolved.

**Comment by loicsaintroch** [comment]
Top, sorry for the delay.

**Comment by sgress454** [comment]
It's a bit hard to comment on this without having more background.  If you don't have sockets and sessions pointed to a datastore like Redis, then this will absolutely happen whenever Sails is lowered / re-lifted while clients are connected, because `sails.io.js` automatically attempts to reconnect and either the socket, session or both are no longer accessible to the server.  Depending on your deployment scenario, your server could be cycling periodically (this would happen on a Heroku app scaled to a single dyno, for example), causing clients to become disconnected until they refresh their pages.

**Comment by sgress454** [comment]
Without more info (and confirmation that this is still an issue in Sails v0.11.x), I'm closing this issue.  Happy to re-open if more info comes to light.

**Comment by livimonte** [comment]
I have the same issue on sails v0.11. Trying to solve now.

**Comment by jyoungrok** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

jyr3357@naver.com 님께 보내신 메일 <Re: [sails] Cross-Origin Resource Sharing problem (#1952)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by livimonte** [comment]
I have the same problem when i make deploy on Heroku, I solved this by forcing transports for websocket:

http://stackoverflow.com/questions/32220349/sails-socket-io-websocket-blocked-how-to-fall-back/32260040#32260040
