### ISSUE TITLE
Action named "identity" breaks sails

### ISSUE THREAD

**Issue by RWOverdijk** [balderdashy/sails#2170]
Hey sailors :p

Look at this beauty: 

```
verbose: responses hook loaded successfully.

/usr/local/lib/node_modules/sails/node_modules/sails-build-dictionary/index.js:120
            module.identity = module.identity.toLowerCase();
                                              ^
TypeError: Object function (req, res) {
    res.ok({identity: req.token.user});
  } has no method 'toLowerCase'
    at /usr/local/lib/node_modules/sails/node_modules/sails-build-dictionary/index.js:120:38
    at forOwn (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:2105:15)
    at Function.forEach (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:3302:9)
    at buildDictionary (/usr/local/lib/node_modules/sails/node_modules/sails-build-dictionary/index.js:74:4)
    at Function.module.exports.optional (/usr/local/lib/node_modules/sails/node_modules/sails-build-dictionary/index.js:160:9)
    at Hook.loadControllers (/usr/local/lib/node_modules/sails/lib/hooks/moduleloader/index.js:223:23)
    at Hook.bound [as loadControllers] (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Hook.loadAndRegisterControllers (/usr/local/lib/node_modules/sails/lib/hooks/controllers/index.js:57:18)
    at Hook.bound [as loadAndRegisterControllers] (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Hook.initialize (/usr/local/lib/node_modules/sails/lib/hooks/controllers/index.js:42:9)
nodejs/dock [ sails lift --verbose                                                                                                                                                                                   feature/auth * ]
```

All I had to do, was create an action called identity. Here's the controller:

``` javascript
/**
 * UserController
 *
 * @description :: Server-side logic for managing users
 * @help        :: See http://links.sailsjs.org/docs/controllers
 */

var helpers = require('request-helpers');

module.exports = {
  authenticate : function (req, res) {

    helpers.pickParams(['username', 'password'], req, function(missing, params) {

      if (missing) {
        return res.badRequest('missing_param', missing);
      }

      sails.models.user.findOne({username: params.username, password: params.password}, function (error, user) {
        if (error) {
          return res.negotiate(error);
        }

        if (!user) {
          return res.badRequest('invalid_credentials');
        }

        res.ok({
          token: sails.services.jwtservice.issueToken({user: user.id})
        });
      });
    });
  },

  identity : function(req, res) {
    res.ok({identity: req.token.user});
  }
};
```

**Comment by Enethion** [comment]
`identity` is used to create RESTful routes. You can change identity of Model/Controller to force this behaviour. 
[Blueprint API doc](http://sailsjs.org/documentation/reference/blueprint-api#?restful-routes)
