### ISSUE TITLE
Calling PUT blueprint route with different data id than id in url crashes the server.

### ISSUE THREAD

**Issue by louim** [balderdashy/sails#2175]
Hello!

Maybe i'm doing something wrong, but it seems like if I call PUT on `localhost:1337/pet/6`with this data: 

```javascript
{
  "name": "Fido",
  "createdAt": "2014-09-01T07:13:17.663Z",
  "updatedAt": "2014-09-01T07:13:17.663Z",
  "id": 7
}
```

The server crash with this error message:
```
warn: Unexpected output from `Pet.update`.
TypeError: Cannot read property 'id' of undefined
    at updated (/rootFolder/backend/node_modules/sails/lib/hooks/blueprints/actions/update.js:81:42)
    at bound (/rootFolder/backend/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/rootFolder/backend/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:416:80)
    at wrappedCallback (/rootFolder/backend/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:315:18)
    at _normalizeCallback.callback.success (/rootFolder/backend/node_modules/sails/node_modules/waterline/node_modules/node-switchback/lib/normalize.js:33:31)
    at _switch (/rootFolder/backend/node_modules/sails/node_modules/waterline/node_modules/node-switchback/lib/factory.js:35:28)
    at /rootFolder/backend/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/update.js:224:9
    at Object.async.each (/rootFolder/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:121:20)
    at /rootFolder/backend/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/update.js:215:13
    at bound.updatedNestedAssociations (/rootFolder/backend/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/update.js:252:12)
```

I'm using sails 0.10.5. 
If I check in the database, the id is switched to the data id (7 in my example). I'm using mysql as the database if that changes anything?

Thanks

**Comment by sgress454** [comment]
Confirmed this is still an issue in v0.11.x.  This has to do with the way `sails-mysql` does its "update" logic (possibly other adapters too).  Most logical solution to me is to disallow changing the primary key via blueprints--you should just drop/recreate the record if that's what you really need...

**Comment by narf** [comment]
Same problem.
The error is very simple to target in the code:

    var updatedRecord = records[0];

    // If we have the pubsub hook, use the Model's publish method
      // to notify all subscribers about the update.
      if (req._sails.hooks.pubsub) {
        if (req.isSocket) { Model.subscribe(req, records); }
        Model.publishUpdate(pk, _.cloneDeep(values), !req.options.mirror && req, {
          previous: matchingRecord.toJSON()
        });
      }

    var Q = Model.findOne(updatedRecord[Model.primaryKey]);


Simply, update did not updated anything, returned an empty array, updatedRecord is undefined, crash.
A simple if can save everythig.
Will you hear us?

**Comment by sgress454** [comment]
@narf you've been heard (see https://github.com/balderdashy/sails/commit/94e3762431e936df95c4e547be54446b594388f6)

Starting with the next release, Sails will no longer allow you to change a record's primary key via the update blueprint.  It's just bad practice.
