### ISSUE TITLE
Cannot generate coffeescript API after a `sails new project --coffee`

### ISSUE THREAD

**Issue by mdarveau** [balderdashy/sails#2262]
Hi,

I generated an new project using `sails new myproject --coffee` which created a `.sailsrc.` files that contains:
```
{
  "generators": {
    "modules": {
      "model": "sails-generate-model-coffee",
      "controller": "sails-generate-controller-coffee"
    }
  }
}
```

However, when I execute `sails generate api League --coffee` I get:
```
error: Error: Generator Error: Failed to load "sails-generate-model-coffee"... (Error: Cannot find module '/Users/mdarveau/git_workspace/maligue/node_modules/sails-generate-model-coffee')
    at parseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:264:7)
    at tryToParseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:44:7)
    at Object.async.until (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:647:13)
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:651:23
    at /usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:47:16
    at parseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:192:16)
    at tryToParseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:44:7)
    at Object.async.until (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:647:13)
    at generateTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:39:9)
    at /usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/generate.js:143:15 [Error: Generator Error: Failed to load "sails-generate-model-coffee"... (Error: Cannot find module '/Users/mdarveau/git_workspace/maligue/node_modules/sails-generate-model-coffee')]
```

I tried to `npm install sails-generate-model-coffee` but it was not found:
```
npm http GET https://registry.npmjs.org/sails-generate-model-coffee
npm http 404 https://registry.npmjs.org/sails-generate-model-coffee
npm ERR! 404 'sails-generate-model-coffee' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "sails-generate-model-coffee"
npm ERR! cwd /Users/mdarveau/git_workspace/maligue
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/mdarveau/git_workspace/maligue/npm-debug.log
npm ERR! not ok code 0
```

However, if I execute `sails generate api MyModel --coffee`, it generates the API in coffeescript.

Is the content of `.sailsrc.` invalid. I don't know if `sails-generate-model-coffee` is supported or even exists anymore as the github project is not reachable anymore.

Thanks!

**Comment by shaunc** [comment]
Hmm.. seems like a moving target. I needed to do: 

    sails new project --linker
    cd project
    npm install coffee-script
    npm install sails-generate-controller-coffee sails-generate-model-coffee

... and then I could

    sails generate api project --coffee
