### ISSUE TITLE
'sails' is undefined in res.view

### ISSUE THREAD

**Issue by typp** [balderdashy/sails#2281]
Hi,

I'm experiencing some trouble with sails v0.10.5.
The logs show an error with GET params when the server lift : 

Error
===
```
TypeError: Cannot read property 'config' of undefined
    at ServerResponse._addResViewMethod.res.view (/home/payname.fr/web/www/node_modules/sails/lib/hooks/views/res.view.js:152:14)
    at module.exports.jeu (/home/payname.fr/web/www/api/controllers/LandingController.js:63:9)
    at routeTargetFnWrapper (/home/payname.fr/web/www/node_modules/sails/lib/router/bind.js:178:5)
    at callbacks (/home/payname.fr/web/www/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/home/payname.fr/web/www/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at pass (/home/payname.fr/web/www/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/home/payname.fr/web/www/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/home/payname.fr/web/www/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /home/payname.fr/web/www/node_modules/sails/lib/router/bind.js:186:7
    at alwaysAllow (/home/payname.fr/web/www/node_modules/sails/lib/hooks/policies/index.js:209:11)
```

Going a bit deeper, I log every user agent which throw this error, and a lot are from differents robots (Google bot and so on), and / or don't have any user agent.

Any help would be very appreciated.

**Comment by CWyrtzen** [comment]
@typp  Does the problem still exists in the latest release?

**Comment by typp** [comment]
The problem is solved.
