### ISSUE TITLE
Object #<ServerResponse> has no method 'view'

### ISSUE THREAD

**Issue by Josebaseba** [balderdashy/sails#2315]
Hi guys, I've a Sails app in production, and when I check the logs I sometimes find this error:

```
index: function(req, res){
  return res.view("home/homepage", {layout: "home/layout.ejs"});
}
```

Error:

```
error: Server Error (500)
error: TypeError: Object #<ServerResponse> has no method 'view'
    at module.exports.index (/www/kuaderno/api/controllers/MainController.js:12:63)
    at routeTargetFnWrapper (/www/kuaderno/node_modules/sails/lib/router/bind.js:178:5)
    at callbacks (/www/kuaderno/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/www/kuaderno/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at pass (/www/kuaderno/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/www/kuaderno/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/www/kuaderno/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /www/kuaderno/node_modules/sails/lib/router/bind.js:186:7
    at alwaysAllow (/www/kuaderno/node_modules/sails/lib/hooks/policies/index.js:209:11)
    at routeTargetFnWrapper (/www/kuaderno/node_modules/sails/lib/router/bind.js:178:5)
```

The same thing happens in other simple web sites that I've made with Sails, and only with this code in routes.js file:

```
module.exports.routes = {

  '/': {
    view: 'homepage'
  },

  'post /contact' : 'MailerController.send'

};
```

In this case this is the error:

```
Sending 500 ("Server Error") response:
 TypeError: Object #<ServerResponse> has no method 'view'
    at serveView (/vervet/xabi-web/node_modules/sails/lib/hooks/views/actions.js:105:8)
    at routeTargetFnWrapper (/vervet/xabi-web/node_modules/sails/lib/router/bind.js:178:5)
    at callbacks (/vervet/xabi-web/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/vervet/xabi-web/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at pass (/vervet/xabi-web/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/vervet/xabi-web/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/vervet/xabi-web/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /vervet/xabi-web/node_modules/sails/lib/router/bind.js:186:7
    at rememberViewId (/vervet/xabi-web/node_modules/sails/lib/hooks/views/actions.js:102:4)
    at routeTargetFnWrapper (/vervet/xabi-web/node_modules/sails/lib/router/bind.js:178:5) [TypeError
```

Sails version 0.10.5, with no CSRF. I have spent a long time trying to find in which cases could the error  appear and I have  found a way to trigger the error but I can't understand why does it happens.

I can force the error using this platform -> https://isitup.org that sends a json asking for website status code.

I have checked the res object when the error happens and I still have access to, res.ok, res.negotiate, res.json etc... The only method that is undefined is res.view().

Any idea why this happens ? Any way to fix it in a clean way?

Thanks!

**Comment by zand3rs** [comment]
Can this fix be applied to v0.10.x as well? I saw this fix included in v0.11.x already but this is also useful for others who are still running on v0.10.x.
