### ISSUE TITLE
Unable to create entity using sails-mysql

### ISSUE THREAD

**Issue by AndrewEastwood** [balderdashy/sails#2320]
I'm trying to add new record through ```http://localhost:1337/test/new?name=3``` and I get this:
```
error: Sending 500 ("Server Error") response: 
 Error (E_UNKNOWN) :: Encountered an unexpected error
: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (/devdata/Develop/github/trans/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:30:14)
    at Query.ErrorPacket (/devdata/Develop/github/trans/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
    at Protocol._parsePacket (/devdata/Develop/github/trans/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:213:24)
    at Parser.write (/devdata/Develop/github/trans/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:62:12)
    at Protocol.write (/devdata/Develop/github/trans/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:37:16)
    at Socket.<anonymous> (/devdata/Develop/github/trans/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:75:28)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:745:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:407:10)
    --------------------
    at Protocol._enqueue (/devdata/Develop/github/trans/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:110:48)
    at PoolConnection.Connection.query (/devdata/Develop/github/trans/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:166:25)
    at __FIND__ (/devdata/Develop/github/trans/node_modules/sails-mysql/lib/adapter.js:825:20)
    at afterwards (/devdata/Develop/github/trans/node_modules/sails-mysql/lib/connections/spawn.js:86:5)
    at /devdata/Develop/github/trans/node_modules/sails-mysql/lib/connections/spawn.js:40:7
    at Ping._callback (/devdata/Develop/github/trans/node_modules/sails-mysql/node_modules/mysql/lib/Pool.js:81:7)
    at Ping.Sequence.end (/devdata/Develop/github/trans/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:24)
    at Ping.Sequence.OkPacket (/devdata/Develop/github/trans/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:87:8)
    at Protocol._parsePacket (/devdata/Develop/github/trans/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:213:24)
    at Parser.write (/devdata/Develop/github/trans/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:62:12)

Details:  Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'

```

I have the model: 
```
module.exports = {

    attributes: {
        name: {
            type: 'string'
        }
    }
};
```
and these configs:
```
module.exports.connections = {
    localDiskDb: {
        adapter: 'sails-mysql'
    },

    someMysqlServer: {
        adapter: 'sails-mysql',
        host: '127.0.0.1',
        user: 'root',
        password: '1111',
        database: 'ditrans',
        // Optional
        charset: 'utf8',
        collation: 'utf8_bin'
    }
}
```
```
module.exports.models = {
    connection: 'someMysqlServer',
    migrate: 'alter'
};
```
and here is created mysql table:
```
-- phpMyAdmin SQL Dump
-- version 4.2.2deb2.precise~ppa.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Oct 18, 2014 at 12:55 AM
-- Server version: 5.5.37-0ubuntu0.12.04.1
-- PHP Version: 5.3.10-1ubuntu3.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Database: `demo`
--

-- --------------------------------------------------------

--
-- Table structure for table `test`
--

CREATE TABLE IF NOT EXISTS `test` (
  `name` varchar(255) COLLATE utf8_bin DEFAULT NULL,
`id` int(11) NOT NULL,
  `createdAt` datetime DEFAULT NULL,
  `updatedAt` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1 ;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `test`
--
ALTER TABLE `test`
 ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `test`
--
ALTER TABLE `test`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
```

The sails-mysql was installed successfully and it creates/updates the test table every time I lift the app.
Maybe somebody has resolved such problem or know what to do coz I can't come up with

**Comment by Dallas62** [comment]
Hello,

If you use blueprints' shorcuts the route is
```http://[server]/:model/create```
And NOT
```http://[server]/:model/new``` => This will try to select the model with at id "new"(=> Not a Number) with name "3"

refer to: http://sailsjs.org/#/documentation/reference/sails.config/sails.config.blueprints.html

**Comment by loicsaintroch** [comment]
Thank you for your help @Dallas62 and @gpedro.

**Comment by AndrewEastwood** [comment]
Thanks guys!
