### ISSUE TITLE
Error: Cannot find module 'depd'

### ISSUE THREAD

**Issue by davesag** [balderdashy/sails#2380]
I've just come back to my Sails project after a few weeks of neglect and now when I try to `sails lift` I get the error `Error: Cannot find module 'depd'`

It seems to be an issue with Express.

Anyone else seeing this?  How should I fix it?

dave

```
sails lift

info: Starting app...

module.js:340
    throw err;
    ^
Error: Cannot find module 'depd'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/davesag/src/mysailsproject/node_modules/sails/node_modules/express/lib/express.js:5:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by nilssolanki** [comment]
@ronelliott awesome, thank you. Your comment saved me quite some trouble.

**Comment by mohammadwali** [comment]
@davesag thanks man, cheers! :)

**Comment by abhijeet24patil** [comment]
@davesag fixed my problem as well with body-parser in node, thanks alot!

**Comment by michaeltansy** [comment]
which node_modules that you delete? Tried to delete the folder inside npm folder and rerunning npm install but it did not work

**Comment by davesag** [comment]
Just delete the node_modules folder from the root of your project and run non install.

**Comment by ferdaous1993** [comment]
Thank you davesag your solution saved my problem

**Comment by lrkwz** [comment]
No luck.
Happened after

    sudo npm install sails@~0.12 --force --save

I've also tried to get back to

    sudo npm install sails@~0.11 --force --save

with no luck.

**Comment by buhtib** [comment]
thanks!
