### ISSUE TITLE
Grunt issue when deploying to Heroku

### ISSUE THREAD

**Issue by teamshultz** [balderdashy/sails#2403]
When I deploy my app to Heroku, Grunt isn't building my production.min.css file the same way it does when I build locally. It seems to add a ton of css which causes my front end to display terribly. Right now, I'm not using SASS, just static css files that need to be included in a certain order. It looks as though several more files are included when I deploy to Heroku. See screenshots below.

Heroku:
![heroku](https://cloud.githubusercontent.com/assets/9423680/5060353/63f35c42-6d16-11e4-98da-996d6c4b1164.PNG)

Local:
![local](https://cloud.githubusercontent.com/assets/9423680/5060354/6966e8e2-6d16-11e4-8ca6-a7a95d40ffdb.PNG)

**Comment by sgress454** [comment]
Hi @teamshultz, not 100% sure what the specific issue is here, but there are known issues with Grunt on Heroku.  I would try using [heroku-buildpack-nodejs-grunt](https://github.com/mbuchetics/heroku-buildpack-nodejs-grunt) on your project; it's helped us in the past.  You'll need to add a `BUILDPACK_URL` environment var in your app; you can do it in the Heroku dashboard or on the command line with:

```
heroku config:add BUILDPACK_URL=https://github.com/mbuchetics/heroku-buildpack-nodejs-grunt.git
```

then in the `tasks/register/prod.js` file, copy the existing `prod` tasks but rename it to `heroku:production`, e.g.:

```
	grunt.registerTask('heroku:production', [
		'compileAssets',
		'concat',
		'uglify',
		'cssmin',
		'sails-linker:prodJs',
		'sails-linker:prodStyles',
		'sails-linker:devTpl',
		'sails-linker:prodJsJade',
		'sails-linker:prodStylesJade',
		'sails-linker:devTplJade'
	]);
```

**Comment by granteagon** [comment]
We are seeing this issue intermittently when deploying to Heroku as well.  Sometimes the deploy works, sometimes it doesn't.

Using this buildpack: https://elements.heroku.com/buildpacks/bemyapptech/heroku-buildpack-nodejs-grunt-compass

Heroku logs:
```
2016-06-15T16:21:47.052821+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2016-06-15T16:21:47.052833+00:00 app[web.1]: designed for a production environment, as it will leak
2016-06-15T16:21:47.052834+00:00 app[web.1]: memory, and will not scale past a single process.
2016-06-15T16:22:06.973469+00:00 app[web.1]: Error: The hook `grunt` is taking too long to load.
2016-06-15T16:22:06.973479+00:00 app[web.1]: Make sure it is triggering its `initialize()` callback, or else set `sails.config.grunt._hookTimeout to a higher value (currently 20000)
2016-06-15T16:22:06.973481+00:00 app[web.1]:     at Timeout.tooLong [as _onTimeout] (/app/node_modules/sails/lib/app/private/loadHooks.js:85:21)
2016-06-15T16:22:06.973482+00:00 app[web.1]:     at tryOnTimeout (timers.js:224:11)
2016-06-15T16:22:06.973482+00:00 app[web.1]:     at Timer.listOnTimeout (timers.js:198:5) { [Error: The hook `grunt` is taking too long to load.
2016-06-15T16:22:06.973484+00:00 app[web.1]: Make sure it is triggering its `initialize()` callback, or else set `sails.config.grunt._hookTimeout to a higher value (currently 20000)] code: 'E_HOOK_TIMEOUT' }
2016-06-15T16:22:08.082861+00:00 heroku[web.1]: Process exited with status 0
2016-06-15T16:22:08.088624+00:00 heroku[web.1]: State changed from starting to crashed
```
