### ISSUE TITLE
Blueprint made request on invalid route

### ISSUE THREAD

**Issue by Dallas62** [balderdashy/sails#2406]
Hi!

I was trying to add an action in my controller ( UserController.foo ),
and unfortunately forgot to put my route ('POST /api/user/foo') and when I did the POST on /api/user/foo I got the following stacktrace (see bellow).

Here some informations:
 - User model has associations
 - mysql-adapter
 - Reproduce with GET /api/user/[what ever you want expect an ID]

config/blueprint.js
```
module.exports = {
  actions: false,
  rest: true,
  shortcuts: false,
  prefix: '/api'
};
```

StackTrace
```
error: Sending 500 ("Server Error") response: 
 Error (E_UNKNOWN) :: Encountered an unexpected error
: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
  at Query.Sequence._packetToError ([sails_project]/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:30:14)
  at Query.ErrorPacket ([sails_project]/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
  at Protocol._parsePacket ([sails_project]/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:213:24)
  at Parser.write ([sails_project]/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:62:12)
  at Protocol.write ([sails_project]/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:37:16)
  at Socket.<anonymous> ([sails_project]/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:75:28)
  at Socket.EventEmitter.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:526:21)

    --------------------
  at Protocol._enqueue ([sails_project]/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:110:48)
  at PoolConnection.Connection.query ([sails_project]/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:166:25)
  at Array.async.auto.processParent [as 0] ([sails_project]/node_modules/sails-mysql/lib/adapter.js:588:24)
  at [sails_project]/node_modules/sails-mysql/node_modules/async/lib/async.js:487:38
  at Array.forEach (native)
  at _each ([sails_project]/node_modules/sails-mysql/node_modules/async/lib/async.js:46:24)
  at Object.async.auto ([sails_project]/node_modules/sails-mysql/node_modules/async/lib/async.js:458:9)
  at Cursor.populateBuffers [as $populateBuffers] ([sails_project]/node_modules/sails-mysql/lib/adapter.js:585:19)
  at Cursor.run ([sails_project]/node_modules/sails-mysql/node_modules/waterline-cursor/cursor/cursor.js:45:8)
  at runJoins ([sails_project]/node_modules/sails-mysql/node_modules/waterline-cursor/index.js:51:10)
  at __JOIN__ ([sails_project]/node_modules/sails-mysql/lib/adapter.js:518:9)
  at afterwards ([sails_project]/node_modules/sails-mysql/lib/connections/spawn.js:86:5)
  at [sails_project]/node_modules/sails-mysql/lib/connections/spawn.js:40:7
  at Ping._callback ([sails_project]/node_modules/sails-mysql/node_modules/mysql/lib/Pool.js:81:7)
  at Ping.Sequence.end ([sails_project]/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:24)
  at Ping.Sequence.OkPacket ([sails_project]/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:87:8)
  at Protocol._parsePacket ([sails_project]/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:213:24)
  at Parser.write ([sails_project]/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:62:12)
  at Protocol.write ([sails_project]/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:37:16)
  at Socket.<anonymous> ([sails_project]/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:75:28)
  at Socket.EventEmitter.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:526:21)


Details:  Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
```

Server response
```
{
    "error": "E_UNKNOWN",
    "status": 500,
    "summary": "Encountered an unexpected error",
    "raw": {
        "code": "ER_BAD_FIELD_ERROR",
        "errno": 1054,
        "sqlState": "42S22",
        "index": 0
    }
}
```

When I put my route, it's work fine, but GET on /api/user/bar still produce a mysql request.
I think this could be a way for DDoS a service (useless request).

EDIT:

Should be a problem in mysql adapter it self, cause mongodb should return string ID, but still an error.

**Comment by jdcauley** [comment]
@Dallas62 you may need to submit this as an issue on the [Sails-MySql](https://github.com/balderdashy/sails-mysql) Repo as well

Are you using any policies in conjunction with the custom routes?

**Comment by Dallas62** [comment]
@jdcauley 

Sorry, we left Sails for our project, but yes, this issue should be report on sails-mysql.

I think sails-mysql should check the type of the ID before requesting the database server if it's not done nowadays.
