### ISSUE TITLE
Getting error when trying to use with devil

### ISSUE THREAD

**Issue by ProLoser** [balderdashy/sails#2454]
Devil is a GUI for node inspector. This is the error I get when trying to launch my app through it:

Devil: https://github.com/newton-software/devil

```
/Users/dean/Sites/COH_node/node_modules/sails/lib/hooks/i18n/index.js:78
			.run(function() {
			 ^
TypeError: Cannot call method 'run' of undefined
    at Hook.module.exports.initialize (/Users/dean/Sites/COH_node/node_modules/sails/lib/hooks/i18n/index.js:78:5)
    at Hook.bound [as initialize] (/Users/dean/Sites/COH_node/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at module.exports.load (/Users/dean/Sites/COH_node/node_modules/sails/lib/hooks/index.js:132:16)
    at async.auto.task (/Users/dean/Sites/COH_node/node_modules/sails/node_modules/async/lib/async.js:425:17)
    at async.auto.taskComplete (/Users/dean/Sites/COH_node/node_modules/sails/node_modules/async/lib/async.js:419:17)
    at Array.forEach (native)
    at _each (/Users/dean/Sites/COH_node/node_modules/sails/node_modules/async/lib/async.js:32:24)
    at Object.async.auto.taskComplete [as _onImmediate] (/Users/dean/Sites/COH_node/node_modules/sails/node_modules/async/lib/async.js:418:13)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by jdcauley** [comment]
@ProLoser is this true for current a current version of Sails? Which OS were you using for this?

**Comment by ProLoser** [comment]
OSX
