### ISSUE TITLE
sails.renderView throws an error

### ISSUE THREAD

**Issue by kaiusee** [balderdashy/sails#2456]
When I call sails.renderView or sails.hooks.views.render
I get the following error

```
/root/sails/node_modules/sails/lib/hooks/views/consolidate.js:359
      fn(err);
      ^
TypeError: undefined is not a function
    at Function.fns.ejs.render (/root/sails/node_modules/sails/lib/hooks/views/consolidate.js:359:7)
    at /root/sails/node_modules/sails/lib/hooks/views/consolidate.js:187:23
    at /root/sails/node_modules/sails/lib/hooks/views/consolidate.js:140:7
    at fs.js:268:14
    at /usr/lib/nodejs/graceful-fs/graceful-fs.js:103:5
    at Object.oncomplete (fs.js:107:15)
```

**Comment by GeeWee** [comment]
I also get the same error. Any solutions?

**Comment by GeeWee** [comment]
Seems to happen when there's no callback provided.
