### ISSUE TITLE
Can not connect to Mysql

### ISSUE THREAD

**Issue by geomagilles** [balderdashy/sails#2483]
On a brand new sails projet, I've added:
 
````
 localMysql: {
    adapter: 'sails-mysql',
    host: 'localhost',
    user: 'homestead',
    password: 'secret',
    database: 'sails'
  },
````

on config.connections.js, and:

````
connection: 'localMysql',
migrate: 'alter'
````

on config.models.js. A user model is set on api/models/User.js:

````
// api/models/User.js
module.exports = {

  schema: true,

  attributes: {

    appid: {
      type: 'string'
    },

    uid: {
      type: 'string'
    },

    hid: {
      type: 'string'
    },

    params: {
      type: 'string'
    }
 }
}
````
When running, sails lift, I obtain:

````
error: A hook (`orm`) failed to load!
error: Error (E_UNKNOWN) :: Encountered an unexpected error
: Could not connect to MySQL:
Error: connect ECONNREFUSED
    at afterwards (/home/vagrant/sails/track/node_modules/sails-mysql/lib/connections/spawn.js:75:13)
    at /home/vagrant/sails/track/node_modules/sails-mysql/lib/connections/spawn.js:40:7
    at Pool.<anonymous> (/home/vagrant/sails/track/node_modules/sails-mysql/node_modules/mysql/lib/Pool.js:47:16)
    at Handshake.Sequence.end (/home/vagrant/sails/track/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:24)
    at Protocol.handleNetworkError (/home/vagrant/sails/track/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:282:14)
    at PoolConnection.Connection._handleNetworkError (/home/vagrant/sails/track/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:303:18)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickDomainCallback (node.js:463:13)
```

Meanwhile, on same folder I ran sails, I can successfully connect to mysql (sails database is currently empty) by:

````
mysql --user=homestead --password=secret --host=localhost --database=sails
````

Both sails and mysql are running within a vagrant box.

Any suggestion ?

**Comment by geomagilles** [comment]
Ok - this is solved. Thanks for your help.
Not sure to understand the details, but it was due to the bind-address parameter in  /etc/mysql/my.cnf
Two to solve this:
- comment #bind-address in /etc/mysql/my.cnf and restart mysql (sudo service mysql restart)
- modify the host in connection.js to match the bind-address parameter in  /etc/mysql/my.cnf

**Comment by rutvik18** [comment]
I am using WAMP. and could not find "bind-address" in my my.ini file. Any other work around?
