### ISSUE TITLE
Could not load session for socket 

### ISSUE THREAD

**Issue by billyshena** [balderdashy/sails#2554]
Hello everyone. I've been working with sails 0.10.5 version and sometimes I get an error like this:

error: Could not load session for socket #F4O-lvWICcs6uQTYREOc
error: The socket's cookie could not be parsed into a sessionID.
error: Unless you're overriding the authorization function, make sure you pass in a valid sails.sid cookie
error: (or omit the cookie altogether to have a new session created and an encrypted cookie sent in the response header to your socket.io upgrade request)
error: TypeError: Cannot call method 'indexOf' of undefined
at exports.parseSignedCookie (/Users/bshen/Desktop/educloud-v20/backend/node_modules/sails/node_modules/express/node_modules/connect/lib/utils.js:199:19)
at Object.Session.fromSocket (/Users/bshen/Desktop/educloud-v20/backend/node_modules/sails/lib/hooks/session/index.js:339:38)
at interpretSocketReq (/Users/bshen/Desktop/educloud-v20/backend/node_modules/sails/lib/hooks/sockets/lib/interpreter/interpret.js:542:19)
at Socket. (/Users/bshen/Desktop/educloud-v20/backend/node_modules/sails/lib/hooks/sockets/lib/connection.js:95:5)
at Socket.emit as $emit
at SocketNamespace.handlePacket (/Users/bshen/Desktop/educloud-v20/backend/node_modules/sails/node_modules/socket.io/lib/namespace.js:335:22)
at Manager.onClientMessage (/Users/bshen/Desktop/educloud-v20/backend/node_modules/sails/node_modules/socket.io/lib/manager.js:518:38)
at WebSocket.Transport.onMessage (/Users/bshen/Desktop/educloud-v20/backend/node_modules/sails/node_modules/socket.io/lib/transport.js:369:20)
at Parser. (/Users/bshen/Desktop/educloud-v20/backend/node_modules/sails/node_modules/socket.io/lib/transports/websocket/hybi-16.js:39:10)
at Parser.emit (events.js:95:17) [TypeError: Cannot call method 'indexOf' of undefined]

It might be some Cookies that are being in conflict with the socket one but not sure.

Does anyone have an idea?
Regards,

**Comment by sgress454** [comment]
This can happen if you lower / relift the server while you still have browser pages pointing to your app; those sockets will try to reconnect, but their sessions are lost.  Refreshing the page should fix the issue.

**Comment by billyshena** [comment]
Hi sgress, thanks for your answer ! Is there a way to avoid that?

**Comment by sgress454** [comment]
Sure--close your windows before restarting the server.

**Comment by Dallas62** [comment]
@sgress454 Have you a tip to avoid session corruption when you lift more than one server on the same "domain"?

Because when you have one on 127.0.0.1:8080 and one on 127.0.0.1:1337, and then the first server redirect the user on the second, if you came back to the first one, you can connect with websocket but you lost your session. (I have to use localhost:8080 and 127.0.0.1:1337 to prevent this bug, cause of cookies).

_user_ is on 127.0.0.1:8080
_user_ asks for "index.html" and has a `req.session.toto = "had access to home"`
then user asks over websocket for `req.session.toto` the result is `"had access to home"`

127.0.0.1:8080 => redirect to => 127.0.0.1:1337 (both using websocket)
_user_ go to 127.0.0.1:8080

_user_ is on 127.0.0.1:8080
_user_ asks for "index.html" and has a `req.session.toto = "had access to home"`
then _user_ asks over websocket for `req.session.toto` the result is `undefined`

if _user_ is on localhost:8080
_user_ asks for "index.html" and has a `req.session.toto = "had access to home"`
then user asks over websocket for `req.session.toto` the result is `"had access to home"`

This is only when using on my own laptop, there is no problem when I use subdomain.

**Comment by sgress454** [comment]
The problem is that cookies are valid per *domain*, not per *domain and port*.  This would be an issue with any webserver.  If you want to run two Sails apps locally on different ports and not have cookie collisions, use different domains (or subdomains).  On Linux systems this is easy to set up using `/etc/hosts`; not sure how it's done in Windows these days.

**Comment by Dallas62** [comment]
@sgress454 Thanks

I had the same idea, but it's not friendly when you have to share the project.

**Comment by randallmeeker** [comment]
In windows 7, Server 2010 its C:\Windows\System32\drivers\etc\hosts

**Comment by sgress454** [comment]
@Dallas62 as long as it's two different Sails apps, you can always have one of them use a different session key by configuring `sails.config.session.key`.

**Comment by Dallas62** [comment]
@sgress454 Awesome! Thanks a lot! :+1:
