### ISSUE TITLE
Issue creating new SailsJs app

### ISSUE THREAD

**Issue by wayne-o** [balderdashy/sails#2567]
Full output:

http://pastebin.com/KbxTYins

TL;DR:

```
error: 
------------------------------------------------------------------------
Aborted due to warnings.
Running "less:dev" (less) task
Warning: Cannot read property 'contents' of undefined 
------------------------------------------------------------------------

error: Looks like a Grunt error occurred--
error: Please fix it, then **restart Sails** to continue running tasks (e.g. watching for changes in assets)
error: Or if you're stuck, check out the troubleshooting tips below.

error: Troubleshooting tips:
error: 
error:  *-> Are "grunt" and related grunt task modules installed locally?  Run `npm install` if you're not sure.
error: 
error:  *-> You might have a malformed LESS, SASS, CoffeeScript file, etc.
error: 
error:  *-> Or maybe you don't have permissions to access the `.tmp` directory?
error:      e.g., `/Users/waynedouglas/sonatribe/src/sonatribe-api/.tmp` ?
error: 
error:      If you think this might be the case, try running:
error:      sudo chown -R 501 /Users/waynedouglas/sonatribe/src/sonatribe-api/.tmp
```

This is a fresh install of yosemite, nvm and Node@0.10.13

**Comment by wayne-o** [comment]
Just did ctrl c on the terminal and got this extra bit oof output:

```
error: A hook (`orm`) failed to load!
error: Error: canceled
    at Interface.<anonymous> (/Users/waynedouglas/.nvm/v0.10.13/lib/node_modules/sails/node_modules/prompt/node_modules/read/lib/read.js:66:13)
    at Interface.EventEmitter.emit (events.js:92:17)
    at Interface._ttyWrite (readline.js:620:16)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.EventEmitter.emit (events.js:98:17)
    at emitKey (readline.js:1095:12)
    at ReadStream.onData (readline.js:840:14)
    at ReadStream.EventEmitter.emit (events.js:95:17)
    at ReadStream.<anonymous> (_stream_readable.js:736:14)
    at ReadStream.EventEmitter.emit (events.js:92:17) [Error: canceled]
error: Error: canceled
    at Interface.<anonymous> (/Users/waynedouglas/.nvm/v0.10.13/lib/node_modules/sails/node_modules/prompt/node_modules/read/lib/read.js:66:13)
    at Interface.EventEmitter.emit (events.js:92:17)
    at Interface._ttyWrite (readline.js:620:16)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.EventEmitter.emit (events.js:98:17)
    at emitKey (readline.js:1095:12)
    at ReadStream.onData (readline.js:840:14)
    at ReadStream.EventEmitter.emit (events.js:95:17)
    at ReadStream.<anonymous> (_stream_readable.js:736:14)
    at ReadStream.EventEmitter.emit (events.js:92:17) [Error: canceled]
```

**Comment by wayne-o** [comment]
Updating to Node 0.10.35 and using sails@0.11.0-rc2 fixed this
