### ISSUE TITLE
Error with a put request to the mysql database

### ISSUE THREAD

**Issue by smartcris** [balderdashy/sails#2618]
I'm using Postman to test RESTFUL queries to Sails.js configured with defaults blueprints and sals-mysql. When I send a GET request to this address http://localhost:1337/bookings/6397, I receive the correct data. When I select a PUT request with the same URL ad the proper payload I receive this error:

    error: Sending 500 ("Server Error") response:
    Error (E_UNKNOWN) :: Encountered an unexpected error
    : .findOne() requires a criteria. If you want the first record try .find().limit(1)
    at module.exports.findOne (C:\prestigeweb\node_modules\sails\node_modules\waterline\lib\waterline\adapter\dql.js:143:56)
    at _runOperation (C:\prestigeweb\node_modules\sails\node_modules\waterline\lib\waterline\query\finders\operations.js:400:29)
    at run (C:\prestigeweb\node_modules\sails\node_modules\waterline\lib\waterline\query\finders\operations.js:69:8)
    at bound.module.exports.findOne (C:\prestigeweb\node_modules\sails\node_modules\waterline\lib\waterline\query\finders\basic.js:66:1 )
    at bound [as findOne] (C:\prestigeweb\node_modules\sails\node_modules\lodash\dist\lodash.js:729:21)
    at Deferred.exec (C:\prestigeweb\node_modules\sails\node_modules\waterline\lib\waterline\query\deferred.js:501:16)
    at updated (C:\prestigeweb\node_modules\sails\lib\hooks\blueprints\actions\update.js:83:9)
    at bound (C:\prestigeweb\node_modules\sails\node_modules\lodash\dist\lodash.js:957:21)
    at applyInOriginalCtx (C:\prestigeweb\node_modules\sails\node_modules\waterline\lib\waterline\utils\normalize.js:416:80)
    at wrappedCallback (C:\prestigeweb\node_modules\sails\node_modules\waterline\lib\waterline\utils\normalize.js:315:18)
    at _normalizeCallback.callback.success (C:\prestigeweb\node_modules\sails\node_modules\waterline\node_modules\switchback\lib\normalize.     js:33:31)
    at _switch (C:\prestigeweb\node_modules\sails\node_modules\waterline\node_modules\switchback\lib\factory.js: 48:28)
    at C:\prestigeweb\node_modules\sails\node_modules\waterline\lib\waterline\query\dql\update.js:224:9
    at done (C:\prestigeweb\node_modules\sails\node_modules\waterline\node_modules\async\lib\async.js:135:1)
    at C:\prestigeweb\node_modules\sails\node_modules\waterline\node_modules\async\lib\async.js:32:16
    at C:\prestigeweb\node_modules\sails\node_modules\waterline\node_modules\async\lib\async.js:157:25

    Details:  Error: .findOne() requires a criteria. If you want the first record try .find().limit(1)

**Comment by MBrouns** [comment]
Could you provide a snippet of what you're doing as to make it easier to find the cause

**Comment by smartcris** [comment]
Please have a look here :
http://stackoverflow.com/questions/28287283/angular-js-put-request-fails-with-sails-js-and-mysql-database

**Comment by smartcris** [comment]
Sorry my bad I didn't look to the waterline docs. Adding some extra code to my model fixed the issue: 
     
    module.exports = {
      ...
    autoPK: false,

    attributes: {
        id: {
            type: 'integer',
            autoIncrement: true,
            primaryKey: true
        },
        ...
      }
     }
