### ISSUE TITLE
Error from require() doesn't show

### ISSUE THREAD

**Issue by 0x80** [balderdashy/sails#2629]
I just ran into a situation where Sails wouldn't lift anymore but was not giving me any errors even in verbose mode. Turns out this happens if you put a require statement in one of the model files and it doesn't resolve.

Try adding ```var foo = require('bar');``` on top of a model file.

You can potentially waste a lot of time tracking something like this down.

**Comment by kevinburkeshyp** [comment]
what kind of output do you get? what's your sails config i could have sworn I ran into this last week, now it's displaying a stack trace, for both `require('bar')` and a relative import like `require('./bar')`

**Comment by 0x80** [comment]
No output whatsoever. What kind of config are you interested in? I haven't made many changes to the defaults. I'm using the mongodb adapter, and development env settings with log level info...

**Comment by kevinburkeshyp** [comment]
Guess I was curious about the log levels more than anything. 

If you put a `console.trace()` right above the bad require, what do you get?

**Comment by sgress454** [comment]
Hm, I don't know @0x80, if I put a bad require at the top of a model file and do `sails lift`, I get:

```
info: Starting app...


module.js:340
    throw err;
    ^
Error: Cannot find module 'bar'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
...etc..
```

as expected.

Is your require at the very top, or in some other code?

**Comment by 0x80** [comment]
I dunno maybe I somehow messed this up by tweaking the build config. I will try with a fresh sails app soon. Meanwhile here's my trace output:

```
Trace
    at Object.<anonymous> (/Users/me/myproject/api/models/Project.js:10:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/me/myproject/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/Users/me/myproject/node_modules/include-all/index.js:44:9)
    at buildDictionary (/Users/me/myproject/node_modules/sails/node_modules/sails-build-dictionary/index.js:68:14)
    at Function.module.exports.optional (/Users/me/myproject/node_modules/sails/node_modules/sails-build-dictionary/index.js:160:9)
    at Hook.loadModels (/Users/me/myproject/node_modules/sails/lib/hooks/moduleloader/index.js:261:23)
    at Hook.bound [as loadModels] (/Users/me/myproject/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Array.async.auto.models [as 0] (/Users/me/myproject/node_modules/sails/lib/hooks/orm/load-user-modules.js:23:23)
    at /Users/me/myproject/node_modules/sails/node_modules/async/lib/async.js:459:38
```

**Comment by 0x80** [comment]
I just realized 0.11 is out so I tried that and it still doesn't give me the error from require but at least it's telling me this:

```
error: Error: The hook `orm` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 20000)
    at tooLong [as _onTimeout] (/Users/me/.nvm/versions/node/v0.12.0/lib/node_modules/sails/lib/app/private/loadHooks.js:92:21)
    at Timer.listOnTimeout (timers.js:110:15)
```

But when I tried it on a clean Sails project I do get the error ```Error: Cannot find module 'foo'``` so I'm thinking it's something in my build pipeline or config that's messing things up. Will investigate further but I'm a bit swamped atm so might take a while.

**Comment by sgress454** [comment]
Ok--closing for now as you can't recreate on v0.11 (and I could never recreate anywhere!)
