### ISSUE TITLE
Error when using PostgreSQL Schemas

### ISSUE THREAD

**Issue by MBrouns** [balderdashy/sails#2634]
We use PostgreSQL as a database and divided this database in multiple schema. In our model file we use the following settings to let our model refer to this schema:

```
module.exports = {
    tableName: 'organisation',
    meta: {
        schemaName: 'people'
    },
    attributes: {
....
     }
...
```

However, when we want to retrieve the data from this model we get the following error: 

```
Details:  error: relation "people.organisation" does not exist

error: Sending 500 ("Server Error") response:
Error (E_UNKNOWN) :: Encountered an unexpected error
error: relation "people.organisation" does not exist
    at Connection.parseE (D:\dev_webstorm\OTPBackEnd\node_modules\sails-postgresql\node_modules\pg.js\lib\connection.js:535:11)
    at Connection.parseMessage (D:\dev_webstorm\OTPBackEnd\node_modules\sails-postgresql\node_modules\pg.js\lib\connection.js:362:17)
    at Socket.<anonymous> (D:\dev_webstorm\OTPBackEnd\node_modules\sails-postgresql\node_modules\pg.js\lib\connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)

```

Some digging around shows that the following query gets executed

```
SELECT "organisation"."organisation_id", "organisation"."name", "organisation"."contactable_id", "organisation"."created_at", "organisation"."updated_at", "organisatio
n"."type" FROM "organisation" AS "organisation"   LIMIT 30 OFFSET 0
``` 

This is indeed incorrect as it does not reference the schema name in the FROM field. Can someone verify we're going at this correctly and this is indeed a bug

**Comment by sgress454** [comment]
HI @MBrouns, yup, looks like a bug to me.  Please post this in the [sails-postgresql](https://github.com/balderdashy/sails-postgresql) issues and ping @particlebanana!

**Comment by Samrudhi** [comment]
Hi,

I am facing the same issue when using sails-postgresql adapter to connect to my postgre DB. Can someone point if this issue is fixed in sails and what version? I am currently using sails v0.11.0.

Thanks!
Samrudhi
