### ISSUE TITLE
Error on guessView

### ISSUE THREAD

**Issue by Globegitter** [balderdashy/sails#2635]
For some odd reason I (and some other people using sane) are getting sometimes an error when accessing some models. 
I think it is due to my latest changes of setting `"hooks": { "views": false }` in the `.sailsrc` as well as actually deleting the `views` folder for every project. A simple workaround is to remove every bit of code that tries to access any views. But I wonder why it is even trying that in the first place and `req.wantsJSON` is `undefined`.

Here the error I just got on a testproject:
```js
project/server/api/responses/ok.js:17
    return res.guessView({data: data}, function couldNotGuessView() {
               ^
TypeError: undefined is not a function
    at Object.sendOK (project/server/api/responses/ok.js:17:16)
    at ServerResponse.bound [as ok] (project/server/node_modules/lodash/dist/lodash.js:729:21)
    at found (project/server/api/blueprints/find.js:22:9)
    at bound (project/server/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (project/server/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:416:80)
    at wrappedCallback (project/server/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:315:18)
    at callback.success (project/server/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (project/server/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at returnResults (project/server/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:356:9)
    at project/server/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:251:16
    at project/server/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:82:7
    at Object.async.each (project/server/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:121:20)
    at project/server/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:425:11
    at project/server/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:564:5
    at Object.async.each (project/server/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:121:20)
    at _buildChildOpts (project/server/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:453:9)
    at _execChildOpts (project/server/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:421:8)
    at project/server/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:80:10
    at bound (project/server/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (project/server/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:416:80)
    at wrappedCallback (project/server/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:315:18)
    at callback.success (project/server/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (project/server/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at project/server/node_modules/sails-disk/lib/adapter.js:88:19
    at null._onTimeout (project/server/node_modules/sails-disk/lib/adapter.js:179:10)
```

**Comment by sgress454** [comment]
Yeah, the default responses do seem to be a bit tied-in to the views hook, so if you turn that off you'll  have to fine-tune the response accordingly.  Would be [open to a PR](https://github.com/balderdashy/sails-generate-backend/tree/master/templates/api/responses) that checks that the views hook is enabled before even attempting anything view-related!
