### ISSUE TITLE
sails generate api file .. causes blueprints to fail

### ISSUE THREAD

**Issue by phishy** [balderdashy/sails#2638]
I ran: sails generate api file with sails 0.11.0-rc5

Tried to access the endpoint from the browser, and received this message in the console.

/usr/local/lib/node_modules/sails/node_modules/sails-hook-sockets/node_modules/socket.io/node_modules/has-binary-data/index.js:30
         (global.File && obj instanceof File)
                                        ^
TypeError: Expecting a function in instanceof check, but got file,[object Object]
    at _hasBinary (/usr/local/lib/node_modules/sails/node_modules/sails-hook-sockets/node_modules/socket.io/node_modules/has-binary-data/index.js:30:41)
    at hasBinary (/usr/local/lib/node_modules/sails/node_modules/sails-hook-sockets/node_modules/socket.io/node_modules/has-binary-data/index.js:56:10)
    at Namespace.emit (/usr/local/lib/node_modules/sails/node_modules/sails-hook-sockets/node_modules/socket.io/lib/namespace.js:210:9)
    at Object.broadcastToRoom [as broadcast] (/usr/local/lib/node_modules/sails/node_modules/sails-hook-sockets/lib/sails.sockets/broadcast-to-room.js:51:33)
    at bound.broadcast (/usr/local/lib/node_modules/sails/lib/hooks/pubsub/index.js:122:23)
    at bound.publishCreate (/usr/local/lib/node_modules/sails/lib/hooks/pubsub/index.js:1192:14)
    at bound [as publishCreate] (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)

**Comment by redBaronNc** [comment]
Hi, I also had previously generated a file model. Now I get the same error as you, since I updated to sails 0.11.0
Here is the message I get:
/Users/ghbaron/node_modules/sails/node_modules/sails-hook-sockets/node_modules/socket.io/node_modules/has-binary-data/index.js:30
         (global.File && obj instanceof File)
                                        ^
TypeError: Expecting a function in instanceof check, but got [object Object]
    at _hasBinary (/Users/ghbaron/node_modules/sails/node_modules/sails-hook-sockets/node_modules/socket.io/node_modules/has-binary-data/index.js:30:41)
    at hasBinary (/Users/ghbaron/node_modules/sails/node_modules/sails-hook-sockets/node_modules/socket.io/node_modules/has-binary-data/index.js:56:10)
    at Object.socketIOClientCallback (/Users/ghbaron/node_modules/sails/node_modules/sails-hook-sockets/node_modules/socket.io/lib/socket.js:349:16)
    at MockServerResponse._clientCallback (/Users/ghbaron/node_modules/sails/node_modules/sails-hook-sockets/lib/receive-incoming-sails-io-msg.js:217:17)
    at MockClientResponse.<anonymous> (/Users/ghbaron/node_modules/sails/lib/router/res.js:72:18)
    at MockClientResponse.EventEmitter.emit (events.js:117:20)
    at finishMaybe (_stream_writable.js:360:12)
    at endWritable (_stream_writable.js:367:3)
    at MockClientResponse.Writable.end (_stream_writable.js:345:5)
    at MockServerResponse.onend (_stream_readable.js:482:10)
    at MockServerResponse.g (events.js:180:16)
    at MockServerResponse.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickDomainCallback (node.js:463:13)

**Comment by redBaronNc** [comment]
It looks like there is a conflict between the File class generated by sails and the File type checked in the blueprint ?

**Comment by redBaronNc** [comment]
I removed the file "file.js" from the model directory since I actually didn't use it and it solves the problem for me, but I think this might cause some issues for people who wants a model called "file".

**Comment by sgress454** [comment]
Yes, this is an issue with the latest version of Socket.io (which is included with Sails v0.11.x) uses the Javascript "File" object, and Sails automatically globalizes the names of all models.  The only workaround I can think of for now (besides not naming your model `File`) is turning off model globals in `config/globals.js`.
