### ISSUE TITLE
`function lower(boolean) does not exist` when overriding blueprint `where` property

### ISSUE THREAD

**Issue by dylanpyle** [balderdashy/sails#2645]
I was looking for a nice solution to inject some default parameters into a blueprint route, and came across http://stackoverflow.com/questions/25080201/waterline-default-query-condition suggesting that I can use a `where` block in my existing route config.

If this a documented configuration setting, I can't find any more info about it. The documentation site seems rather broken anyway though.

Anyway, it doesn't seem to work completely; though it does limit the blueprint query to items where those parameters match, making queries that override it seem to reliably throw a database error.

```
$ curl -i 'localhost:8080/discounts?isDeleted=true' -u $me

HTTP/1.1 500 Internal Server Error
Server: The Black Pearl/0.6.2
Content-Type: application/json; charset=utf-8
Content-Length: 411
Vary: Accept-Encoding
Date: Wed, 11 Feb 2015 23:37:48 GMT
Connection: keep-alive

{
  "error": "E_UNKNOWN",
  "status": 500,
  "summary": "Encountered an unexpected error",
  "raw": {
    "name": "error",
    "length": 201,
    "severity": "ERROR",
    "code": "42883",
    "hint": "No function matches the given name and argument types. You might need to add explicit type casts.",
    "position": "161",
    "file": "parse_func.c",
    "line": "516",
    "routine": "ParseFuncOrColumn"
  }
}
```

And, from the logs:
```
error: Sending 500 ("Server Error") response:
 Error (E_UNKNOWN) :: Encountered an unexpected error
error: function lower(boolean) does not exist
  at [object Object].Connection.parseE (/opt/vendor/node_modules/sails-postgresql/node_modules/pg.js/lib/connection.js:526:11)
  at [object Object].Connection.parseMessage (/opt/vendor/node_modules/sails-postgresql/node_modules/pg.js/lib/connection.js:356:17)
  at Socket.<anonymous> (/opt/vendor/node_modules/sails-postgresql/node_modules/pg.js/lib/connection.js:105:22)
  at Socket.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:765:14)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at emitReadable (_stream_readable.js:423:5)
  at readableAddChunk (_stream_readable.js:166:9)
  at Socket.Readable.push (_stream_readable.js:128:10)
  at TCP.onread (net.js:529:21)
```

**Comment by sgress454** [comment]
Hm, I think you might have some outdated dependencies.  Try re-installing Sails with:

```
sudo npm uinstall -g sails
npm cache clean
sudo npm install -g sails
```

**Comment by dylanpyle** [comment]
@sgress454 That didn't resolve it unfortunately. We're currently on v0.10.5 FWIW - checking out a v0.11 upgrade now to see if that fixes things. We're seeing it on other blueprint-based endpoints in seemingly unrelated situations, so the `where` filter might have been a red herring.
