### ISSUE TITLE
Error in new project generated with sails-generate-new body is not defined

### ISSUE THREAD

**Issue by yohanesyuen** [balderdashy/sails#2773]
I was trying to generate new projects using sails-generate-new on a Windows 8.1 machine.
The last time I tried without problems was barely a week ago, but within the past few days it has been giving me the same problem when I generate with or without linker.

Here is the full stack trace of the error

```
error: Sending 500 ("Server Error") response:
 ReferenceError: C:\Users\Yuen\My Documents\Programming\WebDev\file_uploader\views\layout.ejs:37
    35|
    36|   <body>
 >> 37|     <%- body %>
    38|
    39|
    40|

body is not defined
  at eval (<anonymous>:11:21)
  at C:\Users\Yuen\AppData\Roaming\npm\node_modules\ejs\lib\ejs.js:482:14
  at Object.exports.renderFile (C:\Users\Yuen\AppData\Roaming\npm\node_modules\ejs\lib\ejs.js:348:31
)
  at module.exports (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\ejs-locals\in
dex.js:85:7)
  at C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\ejs-locals\index.js:131:7
  at Object.exports.renderFile (C:\Users\Yuen\AppData\Roaming\npm\node_modules\ejs\lib\ejs.js:353:10
)
  at [object Object].module.exports [as engine] (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sail
s\node_modules\ejs-locals\index.js:85:7)
  at [object Object].View.render (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\
express\lib\view.js:76:8)
  at Function.app.render (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\
lib\application.js:523:10)
  at ServerResponse.res.render (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\ex
press\lib\response.js:827:7)
  at ServerResponse.res.view (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\hooks\views\r
es.view.js:237:16)
  at serveView (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\hooks\views\actions.js:105:
8)
  at routeTargetFnWrapper (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:1
79:5)
  at callbacks (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:164:37)
  at param (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\ind
ex.js:138:11)
  at pass (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\inde
x.js:145:5)
  at nextRoute (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:100:7)
  at callbacks (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:167:11)
  at C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:187:7
  at rememberViewId (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\hooks\views\actions.js
:102:4)
  at routeTargetFnWrapper (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:1
79:5)
  at callbacks (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:164:37)
  at param (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\ind
ex.js:138:11)
  at pass (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\inde
x.js:145:5)
  at nextRoute (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:100:7)
  at callbacks (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:167:11)
  at C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:187:7
  at clearHeaders (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\hooks\cors\index.js:209:
3)
  at routeTargetFnWrapper (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:1
79:5)
  at callbacks (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:164:37)
  at param (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\ind
ex.js:138:11)
  at pass (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\inde
x.js:145:5)
  at nextRoute (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:100:7)
  at callbacks (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:167:11)
  at C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:187:7
  at sails.router.bind._middlewareType (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\hoo
ks\csrf\index.js:102:11)
  at routeTargetFnWrapper (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:1
79:5)
  at callbacks (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:164:37)
  at param (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\ind
ex.js:138:11)
  at pass (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\inde
x.js:145:5)
  at nextRoute (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:100:7)
  at callbacks (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:167:11)
  at C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:187:7
  at _addResViewMethod (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\hooks\views\res.vie
w.js:325:3)
  at routeTargetFnWrapper (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:1
79:5)
  at callbacks (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:164:37)
  at param (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\ind
ex.js:138:11)
  at pass (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\inde
x.js:145:5)
  at nextRoute (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:100:7)
  at callbacks (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:167:11)
  at C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:187:7
  at C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\hooks\i18n\index.js:35:7
  at Object.i18nInit [as init] (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\i1
8n\i18n.js:89:5)
  at addLocalizationMethod (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\hooks\i18n\inde
x.js:33:11)
  at routeTargetFnWrapper (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:1
79:5)
  at callbacks (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:164:37)
  at param (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\ind
ex.js:138:11)
  at pass (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\inde
x.js:145:5)
  at nextRoute (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:100:7)
  at callbacks (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:167:11)
  at C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:187:7
  at addResponseMethods (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\hooks\responses\in
dex.js:178:11)
  at routeTargetFnWrapper (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:1
79:5)
  at callbacks (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:164:37)
  at param (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\ind
ex.js:138:11)
  at pass (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\inde
x.js:145:5)
  at nextRoute (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:100:7)
  at callbacks (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:167:11)
  at C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:187:7
  at C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\hooks\request\index.js:107:13
  at C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\connect-flash\lib\flash.js:21
:5
  at addMixins (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\hooks\request\index.js:86:1
1)
  at routeTargetFnWrapper (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:1
79:5)
  at callbacks (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router
\index.js:164:37)
  at param (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\ind
ex.js:138:11)
  at pass (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\router\inde
x.js:145:5)
  at Router._dispatch (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib
\router\index.js:173:5)
  at Object.router (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\lib\ro
uter\index.js:33:10)
  at next (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\node_modules\co
nnect\lib\proto.js:169:15)
  at Object.xPoweredBy [as handle] (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\hooks\h
ttp\middleware\defaults.js:193:7)
  at next (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\node_modules\co
nnect\lib\proto.js:169:15)
  at Object.methodOverride [as handle] (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_mo
dules\method-override\index.js:63:14)
  at next (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\node_modules\co
nnect\lib\proto.js:169:15)
  at next (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\node_modules\co
nnect\lib\proto.js:171:9)
  at Object._parseHTTPBody [as handle] (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_mo
dules\skipper\index.js:62:14)
  at next (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\node_modules\co
nnect\lib\proto.js:169:15)
  at C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\hooks\http\middleware\defaults.js:52:2
2
  at session (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\node_modules
\connect\node_modules\express-session\index.js:318:7)
  at Object._.defaults.session [as handle] (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib
\hooks\http\middleware\defaults.js:50:11)
  at next (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\node_modules\co
nnect\lib\proto.js:169:15)
  at Object.cookieParser [as handle] (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modu
les\express\node_modules\connect\node_modules\cookie-parser\index.js:48:5)
  at next (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\node_modules\co
nnect\lib\proto.js:169:15)
  at Object.startRequestTimer [as handle] (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\lib\
hooks\http\middleware\defaults.js:72:7)
  at next (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\node_modules\co
nnect\lib\proto.js:169:15)
  at Object.expressInit [as handle] (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modul
es\express\lib\middleware.js:30:5)
  at next (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\node_modules\co
nnect\lib\proto.js:169:15)
  at Object.query [as handle] (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\exp
ress\node_modules\connect\lib\middleware\query.js:45:5)
  at next (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\node_modules\co
nnect\lib\proto.js:169:15)
  at Function.app.handle (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\
node_modules\connect\lib\proto.js:177:3)
  at Server.app (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\express\node_modu
les\connect\lib\connect.js:66:37)
  at Server.<anonymous> (C:\Users\Yuen\AppData\Roaming\npm\node_modules\sails\node_modules\sails-hoo
k-sockets\node_modules\socket.io\node_modules\engine.io\lib\server.js:369:22)
  at Server.emit (events.js:110:17)
  at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
  at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
  at Socket.socketOnData (_http_server.js:343:22)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at Socket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:529:20)
 { [ReferenceError: C:\Users\Yuen\My Documents\Programming\WebDev\file_uploader\views\layout.ejs:37
    35|
    36|   <body>
 >> 37|     <%- body %>
    38|
    39|
    40|

body is not defined]
  path: 'C:\\Users\\Yuen\\My Documents\\Programming\\WebDev\\file_uploader\\views\\layout.ejs' }
```

**Comment by sgress454** [comment]
Works for me™!  You may have something weird linked.  Try:

```
npm uninstall -g sails
npm cache clear
npm install -g sails
```

In general, if it worked a week ago, and it doesn't work now, and you haven't updated Sails or any of its dependencies in the meantime, then the issue *probably* isn't within Sails.

**Comment by yohanesyuen** [comment]
Thanks! It did work! :grinning:
