### ISSUE TITLE
Hook before route no view method

### ISSUE THREAD

**Issue by jaumard** [balderdashy/sails#2799]
Hi,

I'm trying to create an installable hook how make some ACL verifications and when I use res.forbidden, res.notFound or res.view I have an error : 

```javascript
error: Sending 500 ("Server Error") response: 
 TypeError: Object #<ServerResponse> has no method 'view'
    at Object.forbidden (/Users/jaumard/Documents/workspaceIDE/KikiLib/api/responses/forbidden.js:56:19)
    at ServerResponse.bound [as forbidden] (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at isRouteAllowed (/Users/jaumard/Documents/workspaceIDE/KikiLib/api/hooks/acl.js:66:18)
    at routeTargetFnWrapper (/usr/local/lib/node_modules/sails/lib/router/bind.js:179:5)
    at callbacks (/usr/local/lib/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/usr/local/lib/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at pass (/usr/local/lib/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/usr/local/lib/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/usr/local/lib/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /usr/local/lib/node_modules/sails/lib/router/bind.js:187:7
    at /usr/local/lib/node_modules/sails/lib/hooks/i18n/index.js:35:7
    at Object.i18nInit [as init] (/usr/local/lib/node_modules/sails/node_modules/i18n/i18n.js:89:5)
    at addLocalizationMethod (/usr/local/lib/node_modules/sails/lib/hooks/i18n/index.js:33:11)
    at routeTargetFnWrapper (/usr/local/lib/node_modules/sails/lib/router/bind.js:179:5)
    at callbacks (/usr/local/lib/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/usr/local/lib/node_modules/sails/node_modules/express/lib/router/index.js:138:11) [TypeError: Object #<ServerResponse> has no method 'view']
error: Server Error:
error: TypeError: Object #<ServerResponse> has no method 'view'
    at Object.forbidden (/Users/jaumard/Documents/workspaceIDE/KikiLib/api/responses/forbidden.js:56:19)
    at ServerResponse.bound [as forbidden] (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at isRouteAllowed (/Users/jaumard/Documents/workspaceIDE/KikiLib/api/hooks/acl.js:66:18)
    at routeTargetFnWrapper (/usr/local/lib/node_modules/sails/lib/router/bind.js:179:5)
    at callbacks (/usr/local/lib/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/usr/local/lib/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at pass (/usr/local/lib/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/usr/local/lib/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/usr/local/lib/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /usr/local/lib/node_modules/sails/lib/router/bind.js:187:7
    at /usr/local/lib/node_modules/sails/lib/hooks/i18n/index.js:35:7
    at Object.i18nInit [as init] (/usr/local/lib/node_modules/sails/node_modules/i18n/i18n.js:89:5)
    at addLocalizationMethod (/usr/local/lib/node_modules/sails/lib/hooks/i18n/index.js:33:11)
    at routeTargetFnWrapper (/usr/local/lib/node_modules/sails/lib/router/bind.js:179:5)
    at callbacks (/usr/local/lib/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/usr/local/lib/node_modules/sails/node_modules/express/lib/router/index.js:138:11) [TypeError: Object #<ServerResponse> has no method 'view']
```
Under index.js I have : 
```
routes     : {
      before : {
        "/office" : function (req, res, view)
        {
          .....
          res.forbidden();
        }
      }
    },
```
I don't use policies cause policies only apply to routes and want to add more possibilities.
Is there a workaround for this ? Or maybe I make an error somewhere ? 

http://stackoverflow.com/questions/29317329/sails-hook-route-forbidden?noredirect=1#comment46875764_29317329

**Comment by jaumard** [comment]
Just found a workaround : 

```
var _addResViewMethod = require("../sails/lib/hooks/views/res.view.js");
routes     : {
      before : {
        "/office" : function (req, res, view)
        {
          .....
          _addResViewMethod(req, res, function(){
               res.forbidden();
          });
        }
      }
    },
```

**Comment by sgress454** [comment]
Hi @jaumard, this issue arises because the views hook waits until after the `i18n` hook loads before binding routes, and the only way to do this is to use the `sails.router.bind` method to bind routes directly instead of utilizing the hook API's built-in `routes` option.  The good news is, you can do the exact same thing in your hook.  Instead of using `routes: {}`, put the following in the `initialize` function:

```

// Wait for the router to be initialized     
sails.on('router:before', function () {

    // Wait for the views hook to load, so that its routes get bound first 
    // (including the one that mixes in res.view)
    sails.after('hook:views:loaded', function () {
      // Bind your routes here
      sails.router.bind('/office', officeHandler, 'get', {});
    });

    function officeHandler(req, res) {...res.forbidden()...}

    return cb();
});
```

This is preferable to adding the res.view method yourself.

**Comment by jaumard** [comment]
Thanks ! It's more cleaner than my workaround, I will test this.

**Comment by jaumard** [comment]
I have a E_HOOK_TIMEOUT error with your code.
To make it work I have to use this (call the callback out of router:before) : 

    initialize : function (next)
    {
        // Wait for the router to be initialized
        sails.on('router:before', function ()
        {
          // Wait for the views hook to load, so that its routes get bound first
          // (including the one that mixes in res.view)
          sails.after('hook:views:loaded', function ()
          {
            // Bind your routes here

            for (var route in  sails.config.routes)
            {
              sails.router.bind(route, officeHandler, 'get', {});
            }

          });

          function officeHandler(req, res)
          {
            res.forbidden();
          }

        });
        return next();
      
    },

**Comment by sgress454** [comment]
You're right--I mistyped in my post.  The callback needs to go outside the event handler, just as you have it.

**Comment by jaumard** [comment]
Thanks for your confirmation ! :D it works like a charm !
