### ISSUE TITLE
Maximum call stack size exceeded when using socket.io-redis as adapter for sockets.

### ISSUE THREAD

**Issue by WillDent** [balderdashy/sails#2813]
To recreate:
- [ ] Use Mongo for database.
- [ ] Install socket.io-redis and configure this in /config/socket.js
- [ ] Make PUT /modelname/:id request and the below message
i/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;
              ^
RangeError: Maximum call stack size exceeded

** If you comment out "adapter: 'socket.io-redis' then the put request will work with no errors.

I also pulled MASTER #2647 and tested with same above results. So it doesn't look like that solves this issue.

**Comment by tjwebb** [comment]
Have you tried this with other databases? This is being thrown from the actual mongo driver.

**Comment by Salakar** [comment]
Am getting a similar issue possibly related

I am using mongo for my sessions and database, and trying to use redis for the socket adapter. I get the following error:

```
/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:765
            return new ctor(+value);
                            ^
RangeError: Maximum call stack size exceeded
    at Date.valueOf (native)
    at baseClone (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:765:29)
    at Function.cloneDeep (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:1799:14)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/model/lib/defaultMethods/toObject.js:114:26
    at Array.forEach (native)
    at toObject.addProperties (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/model/lib/defaultMethods/toObject.js:112:27)
    at new module.exports (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/model/lib/defaultMethods/toObject.js:34:8)
    at prototypeFns.toObject (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/model/index.js:30:14)
    at prototypeFns.toJSON (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/model/index.js:112:20)
    at sizeof (/Users/Mike/Documents/Homestead/projects/accachatter/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:466:25)
    at sizeof (/Users/Mike/Documents/Homestead/projects/accachatter/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:466:12)
    at sizeof (/Users/Mike/Documents/Homestead/projects/accachatter/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:466:12)
    at sizeof (/Users/Mike/Documents/Homestead/projects/accachatter/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:466:12)
    at sizeof (/Users/Mike/Documents/Homestead/projects/accachatter/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:466:12)
    at sizeof (/Users/Mike/Documents/Homestead/projects/accachatter/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:466:12)
    at sizeof (/Users/Mike/Documents/Homestead/projects/accachatter/node_modules/socket.io-redis/node_modules/msgpack-js/msgpack.js:466:12)
```

**Comment by tjwebb** [comment]
possibly related to #2819?

**Comment by weblogixx** [comment]
Hi,

this may be the same problem as this waterline issue here: https://github.com/balderdashy/waterline/issues/891. Please adjust your toJSON methods accordingly and try it again.

**Comment by Salakar** [comment]
@weblogixx seems to do the trick for me! Cheers

**Comment by ricksixhops** [comment]
It is not working for me.  I have a simple model with no associations and no toJSON method defined.  If I try to use standard blueprints to update the model, I get an infinite regression error from msgpack in socket-io.redis.  It doesn't matter whether I add a toJSON method or not, it will always go into infinite regression in msgpack.

Right now it seems socket-io.redis and Waterline are simply not compatible.  This is highly frustrating since Sails seems to be requiring the use of both.  Is there any viable alternatives?

**Comment by particlebanana** [comment]
Seems to be an issue with the pub sub stuff in the update method of the restful blueprints. Wrapping the following line in a `_.cloneDeep()` seems to solve the issue. https://github.com/balderdashy/sails/blob/master/lib/hooks/blueprints/actions/update.js#L72

Not sure what's going but I suspect it has more to do with https://github.com/balderdashy/sails/pull/2647

**Comment by particlebanana** [comment]
Issued https://github.com/balderdashy/sails/pull/2865 which should fix this

**Comment by mikermcneil** [comment]
@particlebanana I'd rather we did this in the `sails.sockets.*` methods if that's where this problem is coming from.   @WillDent would you mind creating a failing test?

**Comment by mikermcneil** [comment]
@WillDent @particlebanana here are the `sails.sockets.*` tests we have so far: https://github.com/balderdashy/sails-hook-sockets/blob/master/test/sails.sockets.test.js

And here are instructions on how to run the tests: https://github.com/balderdashy/sails-hook-sockets/blob/master/README.md#running-the-tests

**Comment by granteagon** [comment]
This seems to still be happening for update queries in sails console.  I get:

```
at serializeObject 
... [thousansds of these lines ]...
(/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:548:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:548:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:548:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:548:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:548:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:548:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:548:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:548:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:548:17)
  at serializeObject (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:276:18)
  at serializeInto (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/parser/serializer.js:624:17)
  at [object Object].serialize (/Users/grant/Projects/v4/backend/node_modules/bson/lib/bson/bson.js:46:27)
  at [object Object].Query.toBin (/Users/grant/Projects/v4/backend/node_modules/mongodb-core/lib/connection/commands.js:123:25)
  at executeSingleOperation (/Users/grant/Projects/v4/backend/node_modules/mongodb-core/lib/topologies/server.js:741:28)
  at [object Object].Server.command (/Users/grant/Projects/v4/backend/node_modules/mongodb-core/lib/topologies/server.js:821:12)
  at executeWrite (/Users/grant/Projects/v4/backend/node_modules/mongodb-core/lib/wireprotocol/2_6_support.js:48:12)
  at [object Object].WireProtocol.update (/Users/grant/Projects/v4/backend/node_modules/mongodb-core/lib/wireprotocol/2_6_support.js:60:3)
  at [object Object].Server.update (/Users/grant/Projects/v4/backend/node_modules/mongodb-core/lib/topologies/server.js:968:37)
  at [object Object].Server.update (/Users/grant/Projects/v4/backend/node_modules/mongodb/lib/server.js:331:17)
  at updateDocuments (/Users/grant/Projects/v4/backend/node_modules/mongodb/lib/collection.js:967:19)
  at [object Object].Collection.update (/Users/grant/Projects/v4/backend/node_modules/mongodb/lib/collection.js:1005:44)
  at /Users/grant/Projects/v4/backend/node_modules/sails-mongo/lib/collection.js:231:16
  at handleCallback (/Users/grant/Projects/v4/backend/node_modules/mongodb/lib/utils.js:96:12)
  at /Users/grant/Projects/v4/backend/node_modules/mongodb/lib/cursor.js:835:16
  at handleCallback (/Users/grant/Projects/v4/backend/node_modules/mongodb-core/lib/cursor.js:244:5)
  at setCursorDeadAndNotified (/Users/grant/Projects/v4/backend/node_modules/mongodb-core/lib/cursor.js:548:3)
  at nextFunction (/Users/grant/Projects/v4/backend/node_modules/mongodb-core/lib/cursor.js:722:7)
  at [object Object].Cursor.next [as _next] (/Users/grant/Projects/v4/backend/node_modules/mongodb-core/lib/cursor.js:753:3)
  at fetchDocs (/Users/grant/Projects/v4/backend/node_modules/mongodb/lib/cursor.js:831:10)
  at /Users/grant/Projects/v4/backend/node_modules/mongodb/lib/cursor.js:854:7
  at handleCallback (/Users/grant/Projects/v4/backend/node_modules/mongodb-core/lib/cursor.js:244:5)
  at nextFunction (/Users/grant/Projects/v4/backend/node_modules/mongodb-core/lib/cursor.js:743:5)
  at /Users/grant/Projects/v4/backend/node_modules/mongodb-core/lib/cursor.js:668:7
  at queryCallback (/Users/grant/Projects/v4/backend/node_modules/mongodb-core/lib/cursor.js:321:5)
  at bound (domain.js:250:14)
  at runBound (domain.js:263:12)
  at [object Object].Callbacks.emit (/Users/grant/Projects/v4/backend/node_modules/mongodb-core/lib/topologies/server.js:95:3)
  at [object Object].messageHandler (/Users/grant/Projects/v4/backend/node_modules/mongodb-core/lib/topologies/server.js:243:23)
  at Socket.<anonymous> (/Users/grant/Projects/v4/backend/node_modules/mongodb-core/lib/connection/connection.js:262:22)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)


Details:  MongoError: Maximum call stack size exceeded
```

My update query is very simple.  Just a search on id, with a single param change.  Don't think it's related to that.
