### ISSUE TITLE
Number.js model name

### ISSUE THREAD

**Issue by zoell** [balderdashy/sails#2872]
Hi,

I just came accross a weird issue. I created a really simple model (content does not matter). Name it to Number.js, and I have received the following error upon lift:

```
verbose: Running the setup logic in `sails.config.bootstrap(cb)`...
error: The bootstrap function threw an error after its callback was called :: TypeError: object is not a function
    at toNumber (net.js:1051:36)
    at Server.listen (net.js:1211:14)
    at Array.async.auto.start (/var/www/dev/source/web/node_modules/sails/lib/hooks/http/start.js:29:35)
    at /var/www/dev/source/web/node_modules/sails/node_modules/async/lib/async.js:487:38
    at Array.forEach (native)
    at _each (/var/www/dev/source/web/node_modules/sails/node_modules/async/lib/async.js:46:24)
    at Object.async.auto (/var/www/dev/source/web/node_modules/sails/node_modules/async/lib/async.js:458:9)
    at Sails.startServer (/var/www/dev/source/web/node_modules/sails/lib/hooks/http/start.js:16:11)
    at Sails.emit (events.js:104:17)
    at Sails.emitter.emit (/var/www/dev/source/web/node_modules/sails/lib/app/private/after.js:50:11)
    at afterBootstrap (/var/www/dev/source/web/node_modules/sails/lib/app/private/initialize.js:56:11)
    at bootstrapDone (/var/www/dev/source/web/node_modules/sails/lib/app/private/bootstrap.js:51:14)
    at Object.module.exports.bootstrap (/var/www/dev/source/web/config/bootstrap.js:16:3)
    at Sails.runBootstrap (/var/www/dev/source/web/node_modules/sails/lib/app/private/bootstrap.js:44:25)
    at Sails.bound [as runBootstrap] (/var/www/dev/source/web/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Sails.initialize (/var/www/dev/source/web/node_modules/sails/lib/app/private/initialize.js:48:9) [TypeError: object is not a function]
```

Anyone else can reproduce this?

**Comment by particlebanana** [comment]
Yup, this is because by default sails globalizes your models so you can access them as `User.foo`, etc. In this case `Number` is a reserved word in js. You can get around this by turning off sails globals and accessing your model with sails.models.number.
