### ISSUE TITLE
Showing warning in pm2 log when started in production env.

### ISSUE THREAD

**Issue by nikhiljohn10** [balderdashy/sails#2903]
I used the code `NODE_ENV=production pm2 start app.js `

then i get the following warning

``` bash
app-0 (err): --------------------------------------------------------
app-0 (err): Warning: connect.session() MemoryStore is not
app-0 (err): designed for a production environment, as it will leak
app-0 (err): memory, and will not scale past a single process.
app-0 (err): Warning: connect.session() MemoryStore is not
app-0 (err): designed for a production environment, as it will leak
app-0 (err): memory, and will not scale past a single process.
app-0 (err): --------------------------------------------------------
app-0 (err): :: Sat May 02 2015 12:33:50 GMT-0700 (MST)
app-0 (err): Environment : production
app-0 (err): Port        : 4040
app-0 (err): --------------------------------------------------------

```

Is this gonna affect my server performance?

**Comment by tjwebb** [comment]
Are you not using redis or mongo for your session store? We recommend that you not keep session data in RAM, as it's insecure and makes horizontal scalability impossible.

**Comment by nikhiljohn10** [comment]
I tried redis, but that gave me connection error which i couldn't find a solution. Didn't tried mongo.  Anyway thank you.

**Comment by tjwebb** [comment]
> but that gave me connection error

There are millions of possible errors. If you let us know what it is, we might be able to help you work through it.

**Comment by nikhiljohn10** [comment]
the controller code i have is as follows
```javascript
module.exports = {

    index: function(req, res) {
        var uuid = require('node-uuid');
        req.session.sid = uuid.v1();
        return res.view("homepage", {
            userid: req.session.sid
        });
    },

    test: function(req, res){
        return res.send(200, req.session.sid);
    }
}
```

and i got following error..

```bash
debug: --------------------------------------------------------
debug: :: Sat May 02 2015 17:05:11 GMT-0700 (MST)

debug: Environment : development
debug: Port        : 4040
debug: --------------------------------------------------------
error: Error occurred in session middleware :: 'Redis connection gone from close event.'

http.js:689
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.res.setHeader (/usr/lib/node_modules/sails/node_modules/express/node_modules/connect/lib/patch.js:133:22)
    at ServerResponse.res.set.res.header (/srv/www/nikz_in/subdomains/jwala/node_modules/sails/node_modules/express/lib/response.js:577:10)
    at ServerResponse.res.send (/srv/www/nikz_in/subdomains/jwala/node_modules/sails/node_modules/express/lib/response.js:142:12)
    at Object.<anonymous> (/srv/www/nikz_in/subdomains/jwala/node_modules/sails/lib/hooks/http/middleware/defaults.js:56:24)
    at Object.immediate._onImmediate (timers.js:363:16)
    at processImmediate [as _immediateCallback] (timers.js:345:15)

```

**Comment by tjwebb** [comment]
>     throw new Error('Can\'t set headers after they are sent.');

This means that somewhere in your code, you are trying to send a response to the client more than once during a single request.

**Comment by tjwebb** [comment]
Also, why are you doing any of this to begin with? sails already generates session ids for you.

**Comment by nikhiljohn10** [comment]
Im new to sails. And couldn't find any clear doc on setting up sessions
with redis.
Is it "sails.sid" to access session id? Also How can i destroy a session
inside my code? I wanna use this variable for a form submittion. I need to
get a new userid for new form submittion.

**Comment by nikhiljohn10** [comment]
The second error was solved when i gave a name to the Redis db variable. But first error still persist.

**config/session.js**
```js
    adapter: 'connect-redis',
    host: 'localhost',
    port: 6379,
    ttl: 84000,
    db: 'jwala',
    pass: '********************************',
    prefix: 'sess:'
```

**config/policies.js**
```js
  '*': false,
  main: {
    'index': true,
    'order': true,
    'test': true
  },
  drops:{
    'dropped': true,
    'delete': true,
    'deleteAll': true
  }


```

**config/routes.js**
```js
  '/': 'Main.index',
  '/order': 'Main.order',
  '/main/index': {response: 'notFound'},
  '/test': 'Main.test',
  '/main/order': {response: 'notFound'}
```

**api/controllers/MainController.js**
```js
    index: function(req, res) {
        var uid ="xxxxxxxxx";
        return res.view("homepage", {
                userid: uid
        });
    }
```

**Comment by nikhiljohn10** [comment]
I reinstalled redis and everything is working fine now. In early redis config i tried to use unix socket to connect the redis server and sails app. i think that was the error responsible for that error.
