### ISSUE TITLE
Error: has no method 'cookie'

### ISSUE THREAD

**Issue by wewoor** [balderdashy/sails#2952]
I get this method from[http://sailsjs.org/#!/documentation/reference/res/res.cookie.html](http://sailsjs.org/#!/documentation/reference/res/res.cookie.html), but when i use this method, it's show me this error:

``` javascript
error: Sending 500 ("Server Error") response: 
 TypeError: Object #<MockServerResponse> has no method 'cookie'
    at Object.module.exports.logout (/home/ziv/workspace/lsd_web_angular/server/api/controllers/AccountController.js:501:9)
    at bound (/home/ziv/workspace/lsd_web_angular/server/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at routeTargetFnWrapper (/home/ziv/workspace/lsd_web_angular/server/node_modules/sails/lib/router/bind.js:179:5)
    at callbacks (/home/ziv/workspace/lsd_web_angular/server/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/home/ziv/workspace/lsd_web_angular/server/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at param (/home/ziv/workspace/lsd_web_angular/server/node_modules/sails/node_modules/express/lib/router/index.js:135:11)
    at pass (/home/ziv/workspace/lsd_web_angular/server/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/home/ziv/workspace/lsd_web_angular/server/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/home/ziv/workspace/lsd_web_angular/server/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /home/ziv/workspace/lsd_web_angular/server/node_modules/sails/lib/router/bind.js:187:7
    at module.exports (/home/ziv/workspace/lsd_web_angular/server/api/policies/authMenu.js:38:10)
    at routeTargetFnWrapper (/home/ziv/workspace/lsd_web_angular/server/node_modules/sails/lib/router/bind.js:179:5)
    at callbacks (/home/ziv/workspace/lsd_web_angular/server/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/home/ziv/workspace/lsd_web_angular/server/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at param (/home/ziv/workspace/lsd_web_angular/server/node_modules/sails/node_modules/express/lib/router/index.js:135:11)
    at pass (/home/ziv/workspace/lsd_web_angular/server/node_modules/sails/node_modules/express/lib/router/index.js:145:5) [TypeError: Object #<MockServerResponse> has no method 'cookie']
```
Here is my server code: 
```javascript
  logout: function(req, res) {
    req.session.token = '';
    res.cookie('PHPSESSID', '1', {
        expires: new Date(Date.now()- 900000),
        httpOnly: true
    });
    Ws.emit(req, 'logout');
  },
```
This request is by websocket, 
>  sails version: v0.11.0

**Comment by Josebaseba** [comment]
http://sailsjs.org/#!/documentation/reference/res

That method is not available for sockets.

**Comment by wewoor** [comment]
@Josebaseba Ok thank you!

**Comment by sergey-kudriavtsev** [comment]
If you provide an abstract router layer, then I don’t know how the client will connect.
#### Shouldn't you maintain your level of abstraction?
[0.12.sailsjs - response-res](https://0.12.sailsjs.com/documentation/reference/response-res)

> A nice side effect of this compatibility is that, in many cases, you can paste existing Node.js code into a Sails app and it will work. And since Sails implements a transport-agnostic request interpreter, the code in your Sails app is WebSocket-compatible as well.


You must eliminate this as stated in the description.
You must don`t throw this Error.


### example:
I am started supporting a previously written application,
REST API on 300 lines, about 50 controllers.

the client wrote his attachment by Angular6, but forgot about the web socket, and did not use sails.io.js

Now the client wants to provide third-party service access to own API via web socket.
We start checking, the web socket is not working.

Question -  when back-end was written,  your documentation was used, what was done wrong back-end developer?
