### ISSUE TITLE
 undefined is not a function on actionId = actionId.toLowerCase();

### ISSUE THREAD

**Issue by marlonpp** [balderdashy/sails#3024]
Hi, 
I'm using Sails with a database (HP Vertica) that doesn't have an adapter yet so I disabled orm, pubsub and blueprints.
To try to make my job easier and my code better organized I created a BaseController that has some basic CRUD methods. 

```javascript
module.exports = function(model){

  return {
    find: function(req, res){
      cb(model.find(req.params.id),res);
    },

    findAll: function(req, res){
      var queryParams = url.parse(req.url, true).query;
      cb(model.findAll(queryParams), res);
    },

    create: function(req, res){
      var newCustomer = req.body;
      cb(model.create(newCustomer), res);
    },

    update: function(req, res){
      var customer = req.body;
      cb(model.update(customer), res);
    }
  };

};
```
So in my real controllers, I just:
```javascript
//create a controller just specifying the Model 
module.exports = BaseController(Customer);
```

This BaseController.js file is inside Controllers folder but when it gets evaluated by the Controllers Hook, I get this error:
```javascript
/usr/local/lib/node_modules/sails/lib/hooks/controllers/index.js:93
						actionId = actionId.toLowerCase();
						                    ^
TypeError: undefined is not a function
    at /usr/local/lib/node_modules/sails/lib/hooks/controllers/index.js:93:27
    at Function.forEach (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:3297:15)
    at /usr/local/lib/node_modules/sails/lib/hooks/controllers/index.js:90:8
    at forOwn (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:2105:15)
    at Function.forEach (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:3302:9)
    at modulesLoaded (/usr/local/lib/node_modules/sails/lib/hooks/controllers/index.js:70:7)
    at /usr/local/lib/node_modules/sails/lib/hooks/moduleloader/index.js:499:14
    at buildDictionary (/usr/local/lib/node_modules/sails/node_modules/sails-build-dictionary/index.js:134:9)
    at Function.module.exports.optional (/usr/local/lib/node_modules/sails/node_modules/sails-build-dictionary/index.js:160:9)
    at Hook.loadControllers (/usr/local/lib/node_modules/sails/lib/hooks/moduleloader/index.js:241:23)
    at Hook.bound [as loadControllers] (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Hook.loadAndRegisterControllers (/usr/local/lib/node_modules/sails/lib/hooks/controllers/index.js:63:18)
    at Hook.bound [as loadAndRegisterControllers] (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Hook.initialize (/usr/local/lib/node_modules/sails/lib/hooks/controllers/index.js:42:9)
    at Hook.bound [as initialize] (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /usr/local/lib/node_modules/sails/lib/hooks/index.js:75:14
```

The problem is on this lines, starting on line 93:
```javascript
// action ids are case insensitive
actionId = actionId.toLowerCase();


// If the action is set to `false`, explicitly disable it
if (action === false) {
delete self.middleware[controllerId][actionId];
    return;
}
```

Two simple changes could fix the problem:
```javascript
// action ids are case insensitive
actionId = actionId ? actionId.toLowerCase() : '';


// If the action is set to `false`, explicitly disable it
if (!action || action === false) {
	delete self.middleware[controllerId][actionId];
	return;
}
```
But I don't know if it could cause others.
I could simply change the location of my BaseController, but I think it makes sense for it to leave inside controllers folder.

Thanks.

**Comment by sgress454** [comment]
Hi @marlonpp, changing the location of the BaseController file is the right answer.  Having all the files in the `api/controllers` folder be real Sails controllers that follow the same format allows us to keep the framework relatively simple and lightweight.  Putting your base controller in a `lib` folder  would be a fine way to get the result you want.
