### ISSUE TITLE
Sails failing to find module specified in .sailsrc globally

### ISSUE THREAD

**Issue by mtbvang** [balderdashy/sails#3026]
I'm following the instructions for the sails-generate-reactjs module and am getting the following error when I run:

`sails new <app name> --force`

With the following .sailsrc file:

`{
    "generators" : {
        "modules" : {
            "frontend" : "sails-generate-reactjs"
        }
    }
}`

Looks like sails is only looking for the module locally. How do I get it to look globally for it? The module is installed globally in /usr/local/lib/node_modules/sails-generate-reactjs.

error: Error: Generator Error: Failed to load "sails-generate-reactjs"... (Error: Cannot find module '/vagrant/node_modules/sails-generate-reactjs')
at parseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:264:7)
at tryToParseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:44:7)
at Object.async.until (/usr/local/lib/node_modules/sails/node_modules/sails-generate/node_modules/async/lib/async.js:647:13)
at /usr/local/lib/node_modules/sails/node_modules/sails-generate/node_modules/async/lib/async.js:651:23
at /usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:47:16
at parseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:192:16)
at tryToParseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:44:7)
at Object.async.until (/usr/local/lib/node_modules/sails/node_modules/sails-generate/node_modules/async/lib/async.js:647:13)
at generateTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:39:9)
at /usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/generate.js:143:15 [Error: Generator Error: Failed to load "sails-generate-reactjs"... (Error: Cannot find module '/vagrant/node_modules/sails-generate-reactjs')]

**Comment by mtbvang** [comment]
I don't know what why, but after installing some other packages on the same docker container I came back and ran the command again and it's working. I'll close for now since it seems to have resolved itself.
