### ISSUE TITLE
EADDRINUSE after programmatically lifting sails in fresh project

### ISSUE THREAD

**Issue by dbkaplun** [balderdashy/sails#3069]
```
 21:25:01  dan@elise:~ 
$ lsof -i:1337 # nothing running on 1337

 21:25:08  ✘ 1  dan@elise:~ 
$ sails new foo
info: Created a new Sails app `foo`!

 21:25:18  dan@elise:~ 
$ cd foo
.editorconfig  .sailsrc      README.md  app.js  config        package.json  views
.gitignore     Gruntfile.js  api        assets  node_modules  tasks

 21:25:22  dan@elise:~/foo 
$ node -p "require('sails').lift(require('rc')('sails'))"
undefined
info:
info:                .-..-.
info:
info:    Sails              <|    .-..-.
info:    v0.11.0             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------'
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info:
info: Server lifted in `/Users/dan/foo`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Tue Jul 07 2015 21:25:36 GMT-0400 (EDT)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------
error: Grunt :: debug: --------------------------------------------------------
error: Grunt :: debug: :: Tue Jul 07 2015 21:25:37 GMT-0400 (EDT)
error: Grunt :: debug: Environment : development
error: Grunt :: debug: Port        : 1337
debug: --------------------------------------------------------
error: Grunt :: events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
  at exports._errnoException (util.js:746:11)
  at Server._listen2 (net.js:1156:14)
  at listen (net.js:1182:10)
  at Server.listen (net.js:1267:5)
  at Array.async.auto.start (/usr/local/lib/node_modules/sails/lib/hooks/http/start.js:29:35)
  at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:487:38
  at Array.forEach (native)
  at _each (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:46:24)
  at Object.async.auto (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:458:9)
  at Sails.startServer (/usr/local/lib/node_modules/sails/lib/hooks/http/start.js:16:11)
  at Sails.emit (events.js:104:17)
  at Sails.emitter.emit (/usr/local/lib/node_modules/sails/lib/app/private/after.js:50:11)
  at afterBootstrap (/usr/local/lib/node_modules/sails/lib/app/private/initialize.js:56:11)
  at bootstrapDone (/usr/local/lib/node_modules/sails/lib/app/private/bootstrap.js:51:14)
  at Object.module.exports.bootstrap (/Users/dan/foo/config/bootstrap.js:16:3)
  at Sails.runBootstrap (/usr/local/lib/node_modules/sails/lib/app/private/bootstrap.js:44:25)
  at Sails.bound [as runBootstrap] (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
  at Sails.initialize (/usr/local/lib/node_modules/sails/lib/app/private/initialize.js:48:9)
  at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
  at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:610:21
  at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:249:17
  at iterate (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:149:13)
  at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:160:25
  at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:251:21
  at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:615:34
  at /usr/local/lib/node_modules/sails/lib/app/load.js:201:13
  at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:454:17
  at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:444:17
  at Array.forEach (native)
  at _each (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:46:24)
  at Immediate.taskComplete (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:443:13)
  at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by RWOverdijk** [comment]
I don't know why this happens, but I do wonder why you're even trying to do this. Could you share your motivation with me?

**Comment by dbkaplun** [comment]
I have a project in which I am trying to start SailsJS programmatically as a gulp task (I've disabled the grunt hook). Even when I try `require('./app')` in my gulp task with an unchanged `app.js` from `sails new`, I get the same `EADDRINUSE `. The same problem occurs in a fresh project. However I'm able to run with `sails lift` and `node app.js` directly. Very strange to me that it doesn't work, yet it doesn't?

**Comment by sgress454** [comment]
Must just be something in the way `node -p` works.  I can verify that this issue exists when running that command, but entering the node CLI and running the same command works fine, as does saving that command to a "test.js" file and then running `node test.js`.  So unless it's imperative that you run it with `node -p` I'd just close this out.

**Comment by sgress454** [comment]
Sorry, didn't see in your second comment that you're getting the same issue with `require`...that's strange.

**Comment by tjwebb** [comment]
This works fine for me: https://github.com/hashpanel/server/blob/master/server.js

Can you try running `npm start` in that project? (it might fail for other config-related reasons, but we care about the port right now). 

What version of node are you running?

**Comment by RWOverdijk** [comment]
I'm not getting the same issue when using require myself, so I'm curious if those are perhaps individual issues.

**Comment by dbkaplun** [comment]
I don't know why this happens, but when I try to use sails from gulp, I get the same `EADDRINUSE` as using it with `node -p`, so maybe there's a deeper issue here.

**Comment by dbkaplun** [comment]
Removed `sails-hook-gulp`, works now. No idea why `node -p` causes that behavior in a fresh project, but closing anyway.

**Comment by gilesbutler** [comment]
I'm getting the same error too. I removed the gulp folder from the hooks folder but that didn't fix it. I'm trying to start sails on AWS Ubuntu instance in production mode using ````sails lift --prod```` but it just returns this:
````
Lowering sails...
Shutting down HTTP server...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EACCES
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1112:19)
    at listen (net.js:1155:10)
    at Server.listen (net.js:1240:5)
    at Array.async.auto.start (/app/node_modules/sails/lib/hooks/http/start.js:29:35)
    at /app/node_modules/sails/node_modules/async/lib/async.js:484:38
    at _each (/app/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Object.async.auto (/app/node_modules/sails/node_modules/async/lib/async.js:455:9)
    at Sails.startServer (/app/node_modules/sails/lib/hooks/http/start.js:16:11)
    at Sails.emit (events.js:104:17)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:50:11)
    at afterBootstrap (/app/node_modules/sails/lib/app/private/initialize.js:56:11)
    at bootstrapDone (/app/node_modules/sails/lib/app/private/bootstrap.js:51:14)
    at Object.module.exports.bootstrap (/app/config/bootstrap.js:27:3)
    at Sails.runBootstrap (/app/node_modules/sails/lib/app/private/bootstrap.js:44:25)
    at Sails.bound [as runBootstrap] (/app/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
````

Any ideas?

**Comment by dbkaplun** [comment]
@gilesbutler you are probably trying to serve on `:80` or some other port number below 1024. Try running again with `sudo` or choosing a port number greater than 1023.

**Comment by gilesbutler** [comment]
@dbkaplun thanks for your help, yep I'm trying to serve it on 80 as it's a production instance. It works on 8080. 

I take it the best way to let the web access it is to forward requests for port 80 to port 8080?

**Comment by dbkaplun** [comment]
@gilesbutler I recommend using a random port for your Sails app, then reverse proxying to it via nginx (:+1:) or Apache. This has the added benefit of fast static hosting, SSL, as well as the ability to serve multiple sites from one host. (Reverse proxies can do this by looking at the `Host` of the HTTP request and subsequently passing along the request to the correct site.)

**Comment by gilesbutler** [comment]
awesome, thanks for the tips @dbkaplun really appreciate it!
