### ISSUE TITLE
Static object ids with Model.create returns invalid id (MongoDB)

### ISSUE THREAD

**Issue by cpmoser** [balderdashy/sails#3152]
Hi All,

I'm setting up a static Role table where I'd like to be able to load in static data from time to time (as well as to share this data with other devs so they can do likewise), thus my model ids need to be static as well.  I'm creating a model like this:

```javascript
var data = {
    id:   "55720d00b94bc08922146c9b",
    name: "admin"
};

Role.create(data).then(function (err, role)
{
    // do other stuff here
    
    console.log(role.id); // outputs "[Object object]"
});
```

I'm getting the string "[Object object]" as the model id, which sounds like Sails/Node is typing a MongoDB ObjectID to a string, and returning the incorrect value for the model id.

What really lead me down this path was trying to do a many to many association on permission models, like this:

```javascript
var data = {
    id:   "55720d00b94bc08922146c9b",
    name: "admin",

    // m2m associations
    permissions: [
        "55ce68a48b9fcb301a541840",  // static permission ids
        "55ce68a48b9fcb301a541841"
    ]
};

Role.create(data).then(function () {console.log("yay");});
```

But that results in:
```
Unhandled rejection Error (E_UNKNOWN) :: Encountered an unexpected error
    at new WLError (C:\Users\cmoser\AppData\Roaming\npm\node_modules\sails\node_modules\waterline\lib\waterline\error\WLError.js:26:15)
    at duckType (C:\Users\cmoser\AppData\Roaming\npm\node_modules\sails\node_modules\waterline\lib\waterline\error\index.js:67:10)
    at errorify (C:\Users\cmoser\AppData\Roaming\npm\node_modules\sails\node_modules\waterline\lib\waterline\error\index.js:39:10)
    at wrappedCallback (C:\Users\cmoser\AppData\Roaming\npm\node_modules\sails\node_modules\waterline\lib\waterline\utils\normalize.js:325:15)
    at callback.error (C:\Users\cmoser\AppData\Roaming\npm\node_modules\sails\node_modules\waterline\node_modules\switchback\lib\normalize.js:42:31)
    at _switch (C:\Users\cmoser\AppData\Roaming\npm\node_modules\sails\node_modules\waterline\node_modules\switchback\lib\factory.js:46:28)
    at C:\Users\cmoser\AppData\Roaming\npm\node_modules\sails\node_modules\waterline\lib\waterline\query\dql\create.js:227:22
    at C:\Users\cmoser\AppData\Roaming\npm\node_modules\sails\node_modules\waterline\lib\waterline\model\lib\defaultMethods\save.js:167:14
    at C:\Users\cmoser\AppData\Roaming\npm\node_modules\sails\node_modules\async\lib\async.js:454:17
    at C:\Users\cmoser\AppData\Roaming\npm\node_modules\sails\node_modules\async\lib\async.js:444:17
    at Array.forEach (native)
    at _each (C:\Users\cmoser\AppData\Roaming\npm\node_modules\sails\node_modules\async\lib\async.js:46:24)
    at Immediate.taskComplete (C:\Users\cmoser\AppData\Roaming\npm\node_modules\sails\node_modules\async\lib\async.js:443:13)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

Note that if I remove the "id" property from my static data object, everything works as expected.

I'm guessing that because the invalid object id is being returned from the create method, this is breaking the associating part.  This looks like a bug, anyone have any thoughts on this?

**Comment by cpmoser** [comment]
This looks like an issue with sails-mongo.  When a new model is created with an id, then sails-mongo will create a MongoDB ObjectID and pass that to Mongo, but what it gets back is a generic JS object, which (when converted using the toString() method) returns the wrong id value.

I've created https://github.com/balderdashy/sails-mongo/pull/322 to fix this.
