### ISSUE TITLE
Having Trouble with routes.js file . Routes not working.

### ISSUE THREAD

**Issue by prio101** [balderdashy/sails#3188]
I tried to make a new route as 
---
        ` '/admin': {view: 'admin/index'} `
but it didn't work and the error is : 
---

  `/home/prio/Desktop/kafal/config/routes.js:36
  '/admin': {view: 'admin/index'}
  ^^^^^^^^
SyntaxError: Unexpected string
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/lib/node_modules/sails/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/usr/lib/node_modules/sails/node_modules/include-all/index.js:44:9)
    at buildDictionary (/usr/lib/node_modules/sails/node_modules/sails-build-dictionary/index.js:68:14)
    at Function.module.exports.aggregate (/usr/lib/node_modules/sails/node_modules/sails-build-dictionary/index.js:190:9)
    at Array.loadOtherConfigFiles (/usr/lib/node_modules/sails/lib/hooks/moduleloader/index.js:164:27)
    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:484:38
    at _each (/usr/lib/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Object.async.auto (/usr/lib/node_modules/sails/node_modules/async/lib/async.js:455:9)
`
**Can anybody help**

**Comment by Josebaseba** [comment]
Paste here the full config/routes file. It looks like you forgot a comma or something like that.

**Comment by prio101** [comment]
The error was with comma.... and not the GET verb or anything .

**Comment by prio101** [comment]
now it is like 

  'GET /': { view: 'homepage' },

  'GET /admin': {view: 'admin/index'}
Thanks , But will you share , how could you say this can be the error .

**Comment by Josebaseba** [comment]
I've experience forgetting commas everywhere! At the end you get use to the error messages...

**Comment by prio101** [comment]
thanks
