### ISSUE TITLE
EADDRINUSE - Sails 0.11

### ISSUE THREAD

**Issue by narangrishab** [balderdashy/sails#3199]
Hi. I installed sails js 0.11 yesterday. Since then I have tried re-installing it multiple times. But I get error Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at Array.async.auto.start (/usr/local/lib/node_modules/sails/lib/hooks/http/start.js:29:35)
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:484:38
    at _each (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Object.async.auto (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:455:9)
    at Sails.startServer (/usr/local/lib/node_modules/sails/lib/hooks/http/start.js:16:11)
    at Sails.emit (events.js:104:17)
    at Sails.emitter.emit (/usr/local/lib/node_modules/sails/lib/app/private/after.js:50:11)
    at afterBootstrap (/usr/local/lib/node_modules/sails/lib/app/private/initialize.js:56:11)
    at bootstrapDone (/usr/local/lib/node_modules/sails/lib/app/private/bootstrap.js:51:14)
    at Object.module.exports.bootstrap (/Users/rishabh/Desktop/sails/config/bootstrap.js:16:3)
    at Sails.runBootstrap (/usr/local/lib/node_modules/sails/lib/app/private/bootstrap.js:44:25)
    at Sails.bound [as runBootstrap] (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)

I have to run killall -9 node everytime I need to do sails lift. How can I solve that?

**Comment by RWOverdijk** [comment]
@narangrishab I'm not sure why you have to run killall... So short check list:

- What OS?
- How do you start your sails application?
- What's the output of (assuming you're on some unix system, and you're using the default port 1337) `lsof -i :1337`?

**Comment by narangrishab** [comment]
@RWOverdijk 

1. Mac Yosemite.
2. sails lift to start the application.
3. 
<img width="878" alt="screen shot 2015-09-02 at 2 23 49 pm" src="https://cloud.githubusercontent.com/assets/9140727/9626894/434760f4-517e-11e5-8ef7-c54b350da3ce.png">

**Comment by RWOverdijk** [comment]
@narangrishab You're already running things with node... Try `sudo killall node -9` and shut down chrome. Then do `sails lift`. From there on out, keep track of what's running on which port. As to shutting down sails, use ctrl+c. I've never seen that not work before so you're probably doing something wrong.

Are you using ctrl+z? What happens when you type `jobs` in your terminal? If so, you're perhaps just suspending processes which would make sense. Or are you perhaps using screen? There are too manu possibilities.

**Comment by narangrishab** [comment]
When I type jobs I get this 

jobs
[2]+  Stopped                 sails lift

What can I do to override this behaviour? Will changing ports help? Why would node interfere with this anyway? @RWOverdijk

**Comment by RWOverdijk** [comment]
@narangrishab Ok. Small intro to jobs:

- Unix has `jobs`.
- You can suspend a job (anything running) by typing ctrl+z
- You can recover a job by typing either `fg` (bring back to front) or `bg` (to run in background).
- You can call the `jobs` command to see your suspended jobs.

Take a look at: http://superuser.com/questions/262942/whats-different-between-ctrlz-and-ctrlc-in-unix-command-line

**Comment by narangrishab** [comment]
@RWOverdijk  Would changing the localhost:1337 to some other port fix the problem because I am not very comfortable with suspending jobs?

**Comment by RWOverdijk** [comment]
@narangrishab Seriously, read it and learn what it's about. Make sure you get comfortable with it, or you'll have the same problem with a different port in the future. It's common knowledge, and important to have in your utility belt :)

**Comment by narangrishab** [comment]
@RWOverdijk  alright. Thanks man :)

**Comment by sgress454** [comment]
Thanks for your help @RWOverdijk!
