### ISSUE TITLE
sails lift trouble Issue - node_modules/bcrypt/node_modules/bindings/bindings.js:83

### ISSUE THREAD

**Issue by SpaceG** [balderdashy/sails#3202]
sails lift - notworking i have trouble here with my bcrypt file ? are you have a slove for this issue? Would like to starting my App here on localhost. but i get this out.. but i have githubed alot but dont found a slove  to fix this issue. Thanks alot. 

<br><br>

Space-Odysseys-Mac-Pro:www cyberspace$ sails lift

info: Starting app...

/Users/cyberspace/Desktop/www/node_modules/bcrypt/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: dlopen(/Users/cyberspace/Desktop/www/node_modules/bcrypt/build/Release/bcrypt_lib.node, 1): no suitable image found.  Did find:
	/Users/cyberspace/Desktop/www/node_modules/bcrypt/build/Release/bcrypt_lib.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Users/cyberspace/Desktop/www/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/cyberspace/Desktop/www/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/cyberspace/Desktop/www/config/passport.js:5:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
Space-Odysseys-Mac-Pro:www cyberspace$

**Comment by SpaceG** [comment]
trouble fixed in one way! <code> npm install bcrypt </code> !
