### ISSUE TITLE
Node v4.1.0 - broken dnode / weak 

### ISSUE THREAD

**Issue by wulfsolter** [balderdashy/sails#3254]
dnode's dep 'weak' is broken, resulting in failing npm install.

dnode has PR fix at https://github.com/substack/dnode/pull/172

Full gist up at https://gist.github.com/wulfsolter/6206773159c6628edaef but summary below
```
make: *** [Release/obj.target/weakref/src/weakref.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/4.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/wulfsolter/Code/wherewolf-backend/node_modules/weak
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
```

Interim workaround is to edit dnode's package.json (node_modules/dnode/package.json) and update dependencies and optionalDependencies to use latest weak of 1.0.0, then npm install will run node-gyp correctly.

**Comment by wulfsolter** [comment]
Ah shoot, dnode is a dependency of phantom (PhantomJS wrapper) not of Sails.

Please accept my apologies and close this issue!
