### ISSUE TITLE
User Model : 1 attribute is invalid

### ISSUE THREAD

**Issue by mshettysubbaiah** [balderdashy/sails#3327]
Just playing with latest sails 0.11.2. When creating the user it threw the following error message "1 attribute is invalid". 

UserModel:
attributes: {

      name: {
          type: 'string'
      },
      title: {
          type: 'string'
      },
      email: {
          type: 'string',
          email: true,
          unique: true
      },
      encryptedPassword: {
          type: 'string'
      }
  }

If email: true is removed, the user creation works just fine.

**Comment by crobinson42** [comment]
UserModel: 

should be:

UserModel: {

**Comment by tjwebb** [comment]
> When creating the user it threw the following error message "1 attribute is invalid".

Care to share with us the user model you are trying to create?

**Comment by mshettysubbaiah** [comment]
Hi guys,

Sorry about not providing sufficient details. My User model is a very basic structure with following attributes: 

module.exports = {
attributes: {
      name: {
          type: 'string',
          required: true
      },
      title: {
          type: 'string'
      },
      email: {
          type: 'string',
          email: true,
          required: true,
          unique: true
      },
      encryptedPassword: {
          type: 'string'
      }
  }
};

The POST submitted data to the database only to witness the error as provided below:
name: test
title: null
email: test@email.com

Error (E_VALIDATION) :: 1 attribute is invalid
    at WLValidationError.WLError (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/error/WLError.js:26:15)
    at new WLValidationError (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/error/WLValidationError.js:20:28)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/validate.js:46:43
    at allValidationsChecked (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/core/validations.js:210:5)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:49:16
    at done (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:239:19)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:40:16
    at validate (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/core/validations.js:147:49)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:162:20
    at /usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:230:13
    at _arrayEach (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:81:9)
    at _each (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:72:13)
    at Object.async.forEachOf.async.eachOf (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:229:9)
    at Object.async.forEach.async.each (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:206:22)
    at Validator.validate (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/core/validations.js:207:9)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/validate.js:42:25

Invalid attributes sent to User:
 • email
   • "email" validation rule failed for input: 'test@email.com'

I had to remove "email: true" inside my model to make it work. I am not sure what I am missing here. Would appreciate your feedback

regards,
Manjunath
