### ISSUE TITLE
Object.keys called on non-object on validations.js:77:12

### ISSUE THREAD

**Issue by kojilab** [balderdashy/sails#3356]
I'm following the docs and am getting the following when I do a sails lift or sails console.

```javascript
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at /opt/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/core/validations.js:77:12
    at Array.forEach (native)
    at Validator.initialize (/opt/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/core/validations.js:74:22)
    at Core._initialize (/opt/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/core/index.js:91:19)
    at module.exports (/opt/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/core/index.js:50:20)
    at module.exports (/opt/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/collection/index.js:44:8)
    at new child (/opt/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/extend.js:17:39)
    at initialize (/opt/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/collection/loader.js:37:10)
    at loadCollection (/opt/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:112:29)
    at /opt/local/lib/node_modules/sails/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/opt/local/lib/node_modules/sails/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/opt/local/lib/node_modules/sails/node_modules/async/lib/async.js:124:9)
    at Array.async.auto.loadCollections (/opt/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:125:13)
    at /opt/local/lib/node_modules/sails/node_modules/async/lib/async.js:487:38
```

This is my model config

```javascript
module.exports = {

  attributes: {
  	name: {
  		type: 'STRING',
  		required: true
  	},
  	autoCreatedAt: true,
  	autoUpdatedAt: true
  	
  }
};
```

Thanks a lot

**Comment by kojilab** [comment]
My bad. Found the issue

**Comment by krekhovetsky** [comment]
you can read more info about Sails ORM in oficial Waterline docs, it's often useful for me
https://github.com/balderdashy/waterline#options
