### ISSUE TITLE
Captains-log module not found

### ISSUE THREAD

**Issue by OwaysisApp** [balderdashy/sails#3366]
module.js:339
    throw err;
    ^

Error: Cannot find module 'captains-log'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/sails/bin/sails-lift.js:10:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

-Tried to "npm install captains-log", removing the node modules and reinstalling them but to no avail.  My ship is sunk :(

**Comment by crobinson42** [comment]
show some code... What environment are you running?

**Comment by tdietrich513** [comment]
I'm also getting this issue. Captains-Log was not automatically installed under node_modules/sails/node_modules, and even if you go into the sails folder and install captains-log, it still gives this error. This was working yesterday but failed after moving out my node_modules and bower folders to simulate a fresh install from source- even after moving those back into my project directory the error persists.

**Comment by ronenteva** [comment]
Same here.
New sails app (0.11.2), `sails lift` resulted in:

    Error: Cannot find module 'captains-log'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:289:25)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (C:\Users\Ronen\AppData\Roaming\npm\node_modules\sails\bin\sails-lift.js:10:16)
        at Module._compile (module.js:425:26)
        at Object.Module._extensions..js (module.js:432:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:313:12)
        at Module.require (module.js:366:17)

**Comment by ronenteva** [comment]
Seems that it happens after upgrading Node version, the new folder structure somehow deletes the global sails folder.

To solve this issue:
1. delete `node_modules` folder.
2. `npm cache clear`
3. `npm install sails -g`
4. `npm install`

**Comment by ronenteva** [comment]
Update:

The actual issue here is that `sails new` deletes the global sails folder.

**Comment by OwaysisApp** [comment]
This is the correct answer ^
