### ISSUE TITLE
sails-auth module gives “Cannot read property 'loadStrategies' of undefined” on update

### ISSUE THREAD

**Issue by drj-io** [balderdashy/sails#3385]
This is from a repository that I originally started in sails .11.0.0.  Later cloning my app repo and doing `npm install` breaks my app.  

$ sails lift

info: Starting app...

```
/home/david/x/webapp/node_modules/sails-auth/api/hooks/sails-auth.js:4
      sails.services.passport.loadStrategies();
                              ^
TypeError: Cannot call method 'loadStrategies' of undefined
    at Hook.initialize (/home/david/x/webapp/node_modules/sails-auth/api/hooks/sails-auth.js:4:31)
    at Hook.bound [as initialize] (/home/david/x/webapp/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /home/david/x/webapp/node_modules/sails/lib/hooks/index.js:75:14
    at /home/david/x/webapp/node_modules/sails/node_modules/async/lib/async.js:451:17
    at /home/david/x/webapp/node_modules/sails/node_modules/async/lib/async.js:441:17
    at _each (/home/david/x/webapp/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Object.taskComplete (/home/david/x/webapp/node_modules/sails/node_modules/async/lib/async.js:440:13)
    at processImmediate [as _immediateCallback] (timers.js:363:15)
```

This was working fine with sails-auth 1.0.10 but broke with sails-auth 1.2.3 .

Would love to be current.  I answered this SO issue here too: http://stackoverflow.com/questions/32792853/sails-auth-module-gives-cannot-read-property-loadstrategies-of-undefined

**Comment by hellowin** [comment]
This is more to `sails-auth` problems rather than sails it self.

**Comment by drj-io** [comment]
agreed is this not the proper place for that?

**Comment by hellowin** [comment]
I think you should post on the `sails-auth` issue https://github.com/tjwebb/sails-auth

**Comment by drj-io** [comment]
Will do thanks.
