### ISSUE TITLE
ER_HOST_IS_BLOCKED

### ISSUE THREAD

**Issue by vivekduddempudi** [balderdashy/sails#3443]
I am using sailjs that connected to mysql. its getting blocked frequently. Can please suggest some thing to resolve this issue

Error (E_UNKNOWN) :: Encountered an unexpected error
: Could not connect to MySQL:
Error: ER_HOST_IS_BLOCKED: Host '192.168.xxxx.xx' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'
    at afterwards (/home/xxxx/node_modules/sails-mysql/lib/connections/spawn.js:72:13)
    at /home/xxxx/node_modules/sails-mysql/lib/connections/spawn.js:40:7
    at Handshake.onConnect (/home/xxxx/node_modules/sails-mysql/node_modules/mysql/lib/Pool.js:54:9)
    at Handshake.Sequence.end (/home/xxxx/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Handshake.ErrorPacket (/home/xxxx/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Handshake.js:103:8)
    at Protocol._parsePacket (/home/xxxx/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/home/xxxx/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/home/xxxx/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/xxxx/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

Details:  Error: Could not connect to MySQL:
Error: ER_HOST_IS_BLOCKED: Host '192.168.xxxx' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'

**Comment by einfallstoll** [comment]
This has nothing to do with sails.js. Flush the blocked hosts on your database (as suggested in the error message) and try again. If it still happens, check wether your password is correct, the user has enough privileges and if you're even allowed to authenticate to that user with your current IP address.

**Comment by sgress454** [comment]
Thanks @einfallstoll!

@vivekduddempudi, thanks for using Sails!  This forum is reserved for reporting bugs on the Sails core; for support issues like these, please try our [Google Group](https://groups.google.com/forum/#!forum/sailsjs), [live chat](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or [StackOverflow](http://stackoverflow.com).
