### ISSUE TITLE
`unique` constraint not work in MariaDB

### ISSUE THREAD

**Issue by chenweiyj** [balderdashy/sails#3451]
I have a model with an attribute defined with `unique: true` and my model migrate is 'alter'. However, when I run my application, it shows me following errors:

```
error: A hook (`orm`) failed to load!
error: Error (E_UNKNOWN) :: Encountered an unexpected error
: ER_INDEX_COLUMN_TOO_LONG: Index column size too large. The maximum column size is 767 bytes.
    at Query.Sequence._packetToError (/Users/chenwei/Documents/workspace/yontact/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/Users/chenwei/Documents/workspace/yontact/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/Users/chenwei/Documents/workspace/yontact/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:274:23)
    at Parser.write (/Users/chenwei/Documents/workspace/yontact/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/chenwei/Documents/workspace/yontact/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chenwei/Documents/workspace/yontact/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
    --------------------
    at Protocol._enqueue (/Users/chenwei/Documents/workspace/yontact/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at PoolConnection.query (/Users/chenwei/Documents/workspace/yontact/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:201:25)
    at __DEFINE__ (/Users/chenwei/Documents/workspace/yontact/node_modules/sails-mysql/lib/adapter.js:227:20)
    at afterwards (/Users/chenwei/Documents/workspace/yontact/node_modules/sails-mysql/lib/connections/spawn.js:84:5)
    at /Users/chenwei/Documents/workspace/yontact/node_modules/sails-mysql/lib/connections/spawn.js:40:7
    at Ping.onOperationComplete [as _callback] (/Users/chenwei/Documents/workspace/yontact/node_modules/sails-mysql/node_modules/mysql/lib/Pool.js:99:5)
    at Ping.Sequence.end (/Users/chenwei/Documents/workspace/yontact/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Ping.Sequence.OkPacket (/Users/chenwei/Documents/workspace/yontact/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
    at Protocol._parsePacket (/Users/chenwei/Documents/workspace/yontact/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:274:23)
    at Parser.write (/Users/chenwei/Documents/workspace/yontact/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/chenwei/Documents/workspace/yontact/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chenwei/Documents/workspace/yontact/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)

Details:  Error: ER_INDEX_COLUMN_TOO_LONG: Index column size too large. The maximum column size is 767 bytes.
```

How could I solve it?

**Comment by particlebanana** [comment]
Hey @chenweiyj could you post this over on [Waterline](https://github.com/balderdashy/waterline) with a copy of the model. Might be a long attribute name that we need to cut down when building the index.

**Comment by mikermcneil** [comment]
@chenweiyj if you wouldn't mind posting a link back here when you post that issue, it'll automatically create a back-reference here for anyone who might be arriving at this issue via search engine.

Thanks!

**Comment by chenweiyj** [comment]
I have solved this problem. Because the 'string' is 'varchar(255)' in mysql, and I use utf8mb4 encoding, the unique index will exceed 767 bytes. This causes the problem.

**Comment by mikermcneil** [comment]
@chenweiyj appreciate you taking the time to post back here-- it'll help other folks in the future if they run into a similar problem.  If you think of a useful addition to the docs that would have saved you time, please feel free to submit a PR to sails-docs.  Thanks!

**Comment by chenweiyj** [comment]
@mikermcneil thank you for mentioning me to submit a PR to sails-docs. It is done by PR #612

**Comment by mikermcneil** [comment]
Thanks @chenweiyj!
