### ISSUE TITLE
Error: Cannot find module 'node_modules/sails/node_modules/captains-log

### ISSUE THREAD

**Issue by leosuncin** [balderdashy/sails#3532]
After run ``npm install`` and then run ``sails lift`` appear the next error stack.
```
error: Error: Cannot find module '/home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/captains-log'
  at Function.Module._resolveFilename (module.js:339:15)
  at Function.Module._load (module.js:290:25)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Object.<anonymous> (/home/leosuncin/Workspaces/github/student/node_modules/sails-hook-winston/index.js:6:19)
  at Module._compile (module.js:413:34)
  at Object.Module._extensions..js (module.js:422:10)
  at Module.load (/home/leosuncin/Workspaces/github/student/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at /home/leosuncin/Workspaces/github/student/node_modules/sails/lib/hooks/moduleloader/index.js:463:26
  at /home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/lodash/index.js:2523:13
  at /home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/lodash/index.js:3073:15
  at baseForOwn (/home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/lodash/index.js:2046:14)
  at /home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/lodash/index.js:3043:18
  at baseReduce (/home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/lodash/index.js:2520:7)
  at Function.<anonymous> (/home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/lodash/index.js:3446:13)
  at /home/leosuncin/Workspaces/github/student/node_modules/sails/lib/hooks/moduleloader/index.js:417:29
  at /home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/async/lib/async.js:52:16
  at /home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/async/lib/async.js:548:17
  at /home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/async/lib/async.js:542:17
  at _arrayEach (/home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/async/lib/async.js:85:13)
  at Immediate.taskComplete (/home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/async/lib/async.js:541:13)
  at processImmediate [as _immediateCallback] (timers.js:383:17)
```
I think sails try to find `captains-log` inside ``sails/node_modules``, but is in ``../node_modules``. I tried to fix with these:
```bash
cd node_modules/sails
npm install
```
But then appear:
```
/home/leosuncin/Workspaces/github/student/node_modules/sails/lib/app/private/loadHooks.js:148
          async.each(_.without(_.keys(hooks), 'userconfig', 'moduleloader', 'userhooks'), function (id, cb) {
                ^

TypeError: async.each is not a function
  at Object.async.series.prepare (/home/leosuncin/Workspaces/github/student/node_modules/sails/lib/app/private/loadHooks.js:148:17)
  at /home/leosuncin/Workspaces/github/student/node_modules/async/lib/async.js:499:25
  at iterate (/home/leosuncin/Workspaces/github/student/node_modules/async/lib/async.js:108:13)
  at /home/leosuncin/Workspaces/github/student/node_modules/async/lib/async.js:119:25
  at /home/leosuncin/Workspaces/github/student/node_modules/async/lib/async.js:505:21
  at nextTickCallbackWith0Args (node.js:452:9)
  at process._tickDomainCallback (node.js:422:13)
```
I have to run ``npm install async`` inside `node_modules/sails` in order to fix the problem.
My current enviroment:
> sails 0.12.0-rc7
> node 5.5.0
> npm 3.3.12

I am the only one with these issue.

**Comment by sgress454** [comment]
Hi @leosuncin, NPM 3.3.12 unfortunately has some issues.  See our [blog post on the issue](http://blog.sailsjs.org/), and the [bug report on the NPM repo](https://github.com/npm/npm/issues/10458).  Please try installing the latest NPM with `npm install -g npm@latest`, then re-install Sails with:

```
npm uninstall -g sails
npm cache clean
npm install -g sails
```

**Comment by sgress454** [comment]
(Or if you're not installing Sails globally, skip the `-g` option)

**Comment by leosuncin** [comment]
The problem persist after ``npm install -g npm@latest`` with:
> npm 3.6.0
> node 5.5.0
> sails 0.12.0-rc7

```
error: Error: Cannot find module '/home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/captains-log'
  at Function.Module._resolveFilename (module.js:339:15)
  at Function.Module._load (module.js:290:25)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Object.<anonymous> (/home/leosuncin/Workspaces/github/student/node_modules/sails-hook-winston/index.js:6:19)
  at Module._compile (module.js:413:34)
  at Object.Module._extensions..js (module.js:422:10)
  at Module.load (/home/leosuncin/Workspaces/github/student/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at /home/leosuncin/Workspaces/github/student/node_modules/sails/lib/hooks/moduleloader/index.js:463:26
  at /home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/lodash/index.js:2523:13
  at /home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/lodash/index.js:3073:15
  at baseForOwn (/home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/lodash/index.js:2046:14)
  at /home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/lodash/index.js:3043:18
  at baseReduce (/home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/lodash/index.js:2520:7)
  at Function.<anonymous> (/home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/lodash/index.js:3446:13)
  at /home/leosuncin/Workspaces/github/student/node_modules/sails/lib/hooks/moduleloader/index.js:417:29
  at /home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/async/lib/async.js:52:16
  at /home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/async/lib/async.js:548:17
  at /home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/async/lib/async.js:542:17
  at _arrayEach (/home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/async/lib/async.js:85:13)
  at Immediate.taskComplete (/home/leosuncin/Workspaces/github/student/node_modules/sails/node_modules/async/lib/async.js:541:13)
  at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by sgress454** [comment]
Hm, on second look, it seems like the error is coming from the `sails-hook-winston` plugin you have installed.  You'll have to contact that project maintainer directly.  It may have compatibility issues with the latest version of Sails.

**Comment by sgress454** [comment]
Yup, this line:

```
var captain     = require(path.resolve('node_modules/sails/node_modules/captains-log'));
```

will not work with NPM 3.  They'll need to patch that!

**Comment by leosuncin** [comment]
Thanks @sgress454
