### ISSUE TITLE
Upgrading sails to 0.12 breaks handlebars

### ISSUE THREAD

**Issue by sebastiankruk** [balderdashy/sails#3559]
I wanted to get rid of the sails 0.11.x dependency on the express-handlebars 2.x.x which depended on handlebars < 4. 

> warn: Using Handlebars v3.x; Versions < 4.0.0 may introduce security risks (see https://snyk.io/test/npm/handlebars/3).
> warn: When an updated version becomes available, you should be able to install it by updating your copy of Sails with `npm update`.

Apparently sails 0.12 does the trick, but it also breaks express-handlebars. I have the same problems as in #3232. When I upgrade to express-handlebars 3.0.0 and sails 0.12, I'm getting:

```
$PATH/node_modules/express-handlebars/lib/express-handlebars.js:38
    if (this.extname.charAt(0) !== '.') {
                    ^

TypeError: Cannot read property 'charAt' of undefined
    at new ExpressHandlebars ($PATH/node_modules/express-handlebars/lib/express-handlebars.js:38:21)
    at Function.create ($PATH/node_modules/express-handlebars/index.js:22:12)
    at layoutshim ($PATH/node_modules/sails/lib/hooks/views/layoutshim.js:36:26)
    at Hook.initialize ($PATH/node_modules/sails/lib/hooks/views/index.js:70:7)
    at Hook.wrapper [as initialize] ($PATH/node_modules/lodash/index.js:3095:19)
    at $PATH/node_modules/sails/lib/hooks/index.js:73:14
    at $PATH/node_modules/sails/node_modules/async/lib/async.js:52:16
    at $PATH/node_modules/sails/node_modules/async/lib/async.js:548:17
    at $PATH/node_modules/sails/node_modules/async/lib/async.js:542:17
    at _arrayEach ($PATH/node_modules/sails/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete ($PATH/node_modules/sails/node_modules/async/lib/async.js:541:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

**Comment by olivierl** [comment]
+1

**Comment by sgress454** [comment]
Try adding this to your `config/views.js` file:
```
extension: 'handlebars'
```
I'll take a look at why it's not working automatically.

**Comment by sebastiankruk** [comment]
It works! Thanks :)

**Comment by sgress454** [comment]
0.12.1 has been released with this fix!
