### ISSUE TITLE
I can not locate the error when it occured a SyntaxError

### ISSUE THREAD

**Issue by k3win** [balderdashy/sails#3788]
**Sails version**:0.12.3
**Node version**:v5.10.1
**NPM version**:3.8.3
**Operating system**:Mac OS X 10.11.5

<hr/>

I can not locate the error when it occured a SyntaxError, and I can't get any suggestions like this:
`error: SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /usr/local/lib/node_modules/sails/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/usr/local/lib/node_modules/sails/node_modules/include-all/index.js:44:9)
    at /usr/local/lib/node_modules/sails/node_modules/include-all/index.js:54:23
    at Array.forEach (native)
    at requireAll (/usr/local/lib/node_modules/sails/node_modules/include-all/index.js:44:9)
    at /usr/local/lib/node_modules/sails/node_modules/include-all/index.js:54:23
    at Array.forEach (native)
    at requireAll (/usr/local/lib/node_modules/sails/node_modules/include-all/index.js:44:9)`

**Comment by metzuda** [comment]
Hi @k3win, I encountered this a while ago.

The `require-all` module requires objects to be exported from Controllers, Models & Services. I would check each of these to make sure they're exporting an object.

Hope that helps.

**Comment by mikermcneil** [comment]
@metzuda thanks!

@k3win We could definitely use a better error message here.  If someone would like to send a patch that adds a better error (i.e. a try/catch around the call to includeall in the moduleloader hook), that'd be helpful.  Thanks!

**Comment by mikermcneil** [comment]
Took care of this and some related improvements last night https://github.com/balderdashy/include-all/commit/a1bb435c85cbcfbc92b10e40e52c571630c8c042  https://github.com/balderdashy/sails-build-dictionary/commit/ff6319fb4f5cda2d0557c0c4f1ba1cb92e925b31
