### ISSUE TITLE
I lose my database data in migrate:safe mode.

### ISSUE THREAD

**Issue by Last-Order** [balderdashy/sails#3827]
**Sails version**: 0.12.4
**Node version**:6.4.0
**NPM version**:3.10.3
**Operating system**:Ubuntu 14.04 LTS

<hr/>

I set my migrate setting to "safe" in /config/env/development.js.
Here are my settings.
```
module.exports = {

  /***************************************************************************
   * Set the default database connection for models in the development       *
   * environment (see config/connections.js and config/models.js )           *
   ***************************************************************************/

  models: {
    connection: 'sqlServer',
    migrate: 'safe'
  },
  connections: {
    sqlServer: {
        adapter: 'sails-mysql',
        **********DATABASE SETTINGS******
    }
  }
};
```

I am also using the plugin "sails-hook-autoreload". I change my code and then upload to the remote server without turning sails off. It seems that sometimes, after I uploading my files, sails will get a crash and then I will lose some of my database data. (I didn't change model definitions.)

Here are my output:

```
debug: -------------------------------------------------------
debug: :: Thu Sep 01 2016 02:48:26 GMT+0000 (UTC)

debug: Environment : development
debug: Port        : 1337
debug: -------------------------------------------------------
error: Grunt :: (node:5037) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Waterline encountered a fatal error when trying to perform the `alter` auto-migration strategy.
In a couple of seconds, the data (cached in memory) will be logged to stdout.
(a failsafe put in place to preserve development data)

In the mean time, here's the error:

Error (E_UNKNOWN) :: Encountered an unexpected error
: Cannot enqueue Query after invoking quit.
    at Protocol._validateEnqueue (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:202:16)
    at Protocol._enqueue (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:135:13)
    at PoolConnection.query (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:201:25)
    at /root/Shiny/node_modules/sails-mysql/lib/adapter.js:458:22
    at /root/Shiny/node_modules/sails-mysql/node_modules/async/lib/async.js:181:20
    at iterate (/root/Shiny/node_modules/sails-mysql/node_modules/async/lib/async.js:262:13)
    at /root/Shiny/node_modules/sails-mysql/node_modules/async/lib/async.js:274:29
    at /root/Shiny/node_modules/sails-mysql/node_modules/async/lib/async.js:44:16
    at Query._callback (/root/Shiny/node_modules/sails-mysql/lib/adapter.js:461:13)
    at Query.Sequence.end (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.OkPacket (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:78:10)
    at Protocol._parsePacket (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)

Details:  Error: Cannot enqueue Query after invoking quit.



================================
Data backup:
================================

...My Data...

error: Failed to reload ORM hook.  Details: Error: Failed to reinitialize ORM because the `initialize()` method of the ORM hook returned an error.  
Details:
Error (E_UNKNOWN) :: Encountered an unexpected error
: Cannot enqueue Query after invoking quit.
    at Protocol._validateEnqueue (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:202:16)
    at Protocol._enqueue (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:135:13)
    at PoolConnection.query (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:201:25)
    at /root/Shiny/node_modules/sails-mysql/lib/adapter.js:458:22
    at /root/Shiny/node_modules/sails-mysql/node_modules/async/lib/async.js:181:20
    at iterate (/root/Shiny/node_modules/sails-mysql/node_modules/async/lib/async.js:262:13)
    at /root/Shiny/node_modules/sails-mysql/node_modules/async/lib/async.js:274:29
    at /root/Shiny/node_modules/sails-mysql/node_modules/async/lib/async.js:44:16
    at Query._callback (/root/Shiny/node_modules/sails-mysql/lib/adapter.js:461:13)
    at Query.Sequence.end (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.OkPacket (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:78:10)
    at Protocol._parsePacket (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/Shiny/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
    at /root/.nvm/versions/node/v6.4.0/lib/node_modules/sails/node_modules/sails-hook-orm/lib/reload.js:32:29
    at /root/.nvm/versions/node/v6.4.0/lib/node_modules/sails/node_modules/sails-hook-orm/node_modules/async/lib/async.js:52:16
    at /root/.nvm/versions/node/v6.4.0/lib/node_modules/sails/node_modules/sails-hook-orm/node_modules/async/lib/async.js:570:21
    at /root/.nvm/versions/node/v6.4.0/lib/node_modules/sails/node_modules/sails-hook-orm/node_modules/async/lib/async.js:167:37
    at /root/.nvm/versions/node/v6.4.0/lib/node_modules/sails/node_modules/sails-hook-orm/lib/initialize.js:389:27
    at _afterInitializingWaterline (/root/.nvm/versions/node/v6.4.0/lib/node_modules/sails/node_modules/sails-hook-orm/lib/build-waterline-ontology.js:99:25)
    at /root/.nvm/versions/node/v6.4.0/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:208:23
    at /root/.nvm/versions/node/v6.4.0/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:52:16
    at /root/.nvm/versions/node/v6.4.0/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:264:21
    at /root/.nvm/versions/node/v6.4.0/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:44:16
    at /root/.nvm/versions/node/v6.4.0/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/index.js:68:23
    at Timeout._onTimeout (/root/.nvm/versions/node/v6.4.0/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/alter.js:268:12)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)


```

I am wondering that:
1. I was running the Sails in migration setting 'safe' but why the Sails still performed the `alter` auto-migration strategy? 
2. Without restarting the Sails, why the Sails started trying to perform a migration?

Thank you.

**Comment by sgress454** [comment]
Hi @Last-Order,

To answer your second question first, Sails tried to perform a migration because, as you said, you have `sails-hook-autoreload` active, and it's trying to reload your models.  As far as why it's trying to perform a migration while in `safe` mode, it's because that hook ignores your migration settings by default, in order to actually do its job and reload your models.  From the README for `sails-hook-autoreload`:

> sails-hook-autoreload will, by default, use the migrate: alter strategy when reloading model files unless you explicitly set the overrideMigrateSetting config to false. This allows you to change models without losing your development data when you have migrate: drop set.

**Comment by Last-Order** [comment]
@sgress454 Thank you.
