### ISSUE TITLE
migration failed with charset utf8mb4

### ISSUE THREAD

**Issue by mazyvan** [balderdashy/sails#3951]
**Sails version**: 0.12.11
**Node version**: 6.9.2
**NPM version**: 4.0.5
**Operating system**: Windows 10

<hr/>
I want to store emoticons on my database fields. So I set 

```
    charset: 'utf8mb4',
    collation: 'utf8mb4_unicode_ci'
```

on conections. but when trying to migrate this happens:

```
error: Error (E_UNKNOWN) :: Encountered an unexpected error
: ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
    at Query.Sequence._packetToError (C:\NODEJS\SAILSJS\keepup\node_modules\sails-mysql\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (C:\NODEJS\SAILSJS\keepup\node_modules\sails-mysql\node_modules\mysql\lib\protocol\sequences\Query.js:83:18)
    at Protocol._parsePacket (C:\NODEJS\SAILSJS\keepup\node_modules\sails-mysql\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (C:\NODEJS\SAILSJS\keepup\node_modules\sails-mysql\node_modules\mysql\lib\protocol\Parser.js:73:12)
    at Protocol.write (C:\NODEJS\SAILSJS\keepup\node_modules\sails-mysql\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\NODEJS\SAILSJS\keepup\node_modules\sails-mysql\node_modules\mysql\lib\Connection.js:96:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
    --------------------
    at Protocol._enqueue (C:\NODEJS\SAILSJS\keepup\node_modules\sails-mysql\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at PoolConnection.query (C:\NODEJS\SAILSJS\keepup\node_modules\sails-mysql\node_modules\mysql\lib\Connection.js:201:25)
    at __DEFINE__ (C:\NODEJS\SAILSJS\keepup\node_modules\sails-mysql\lib\adapter.js:227:20)
    at afterwards (C:\NODEJS\SAILSJS\keepup\node_modules\sails-mysql\lib\connections\spawn.js:84:5)
    at C:\NODEJS\SAILSJS\keepup\node_modules\sails-mysql\lib\connections\spawn.js:40:7
    at Ping.onOperationComplete [as _callback] (C:\NODEJS\SAILSJS\keepup\node_modules\sails-mysql\node_modules\mysql\lib\Pool.js:99:5)
    at Ping.Sequence.end (C:\NODEJS\SAILSJS\keepup\node_modules\sails-mysql\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Ping.Sequence.OkPacket (C:\NODEJS\SAILSJS\keepup\node_modules\sails-mysql\node_modules\mysql\lib\protocol\sequences\Sequence.js:105:8)
    at Protocol._parsePacket (C:\NODEJS\SAILSJS\keepup\node_modules\sails-mysql\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (C:\NODEJS\SAILSJS\keepup\node_modules\sails-mysql\node_modules\mysql\lib\protocol\Parser.js:73:12)
    at Protocol.write (C:\NODEJS\SAILSJS\keepup\node_modules\sails-mysql\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\NODEJS\SAILSJS\keepup\node_modules\sails-mysql\node_modules\mysql\lib\Connection.js:96:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

```

Thanks

**Comment by sgress454** [comment]
Hi @mazyvan, this isn't really a Sails issue, but an issue with updating your database to use utf8mb4.  Sails migrations are really about your keeping your schema in sync with your Sails modles, but they're not intended to make these kind of low-level modifications to your database.  

I found a [related article](http://tech.taskrabbit.com/blog/2014/04/24/active-record-mysql-and-emoji/) discussing the issue for a Rails project, and it looks what you need to do is:

>1. change the DB’s encoding entirely, so new tables will be created in utf8mb4
>2. alter all existing tables
>3. explicitly update text-type columns 

So if your database is named `foo`, you'd do something like:

```
ALTER DATABASE `foo` CHARACTER SET utf8mb4;
```

and for each table:

```
ALTER TABLE `my_table_name` CHARACTER SET = utf8mb4;
```

If you don't have any TEXT or BLOB table columns, you're done.  If you do, then for each such column you need to do:

```
ALTER TABLE `my_table_name` CHANGE `my_column_name` `my_column_name` TEXT  CHARACTER SET utf8mb4  NULL;
```

changing `TEXT` to `BLOB` where appropriate.

Hope this helps!

**Comment by mazyvan** [comment]
Yep. I did that. Just I thought that on migration it should do the thing. But it's ok. anyway Thanks for replying

**Comment by tomercagan** [comment]
[Here](https://mathiasbynens.be/notes/mysql-utf8mb4)'s another very good explanation of the issue and what need to be changed - same steps as @sgress454 pointed out with more detailed description of overview of the issue.

Also, there's a note about indexes in the sails.js documentation [here](http://sailsjs.com/documentation/concepts/models-and-orm/attributes) discussing unique attributes (fields) and how they should be handled when using utf8mb4.

**Comment by mikermcneil** [comment]
@tomercagan Thanks!
