### ISSUE TITLE
Model validations

### ISSUE THREAD

**Issue by nehalist** [balderdashy/sails#3959]
**Sails version**: 1.0.0-19
**Node version**: v6.3.0
**NPM version**: 3.10.8
**Operating system**: Win10

<hr/>

I'm not completely sure if this shouldn't be a Waterline issue, but nevertheless:

```
// api/models/Test.js

module.exports = {
  attributes: {
    test: {
      type: 'string',
      alphanumeric: true
    }
  }
}
```

Results in:

```
error: A hook (`orm`) failed to load!
error:
error: Error: The attribute `test` on the `test` model contains invalid properties. The property `alphanumeric` isn't a recognized property.
    at parseProperties (D:\Node\sailsv1test\node_modules\waterline-schema\lib\waterline-schema\schema.js:224:17)
    at D:\Node\sailsv1test\node_modules\@sailshq\lodash\lib\index.js:3228:15
    at baseForOwn (D:\Node\sailsv1test\node_modules\@sailshq\lodash\lib\index.js:2199:14)
    at D:\Node\sailsv1test\node_modules\@sailshq\lodash\lib\index.js:3198:18
    at Function.<anonymous> (D:\Node\sailsv1test\node_modules\@sailshq\lodash\lib\index.js:3501:13)
    at parseAttributes (D:\Node\sailsv1test\node_modules\waterline-schema\lib\waterline-schema\schema.js:222:9)
    at D:\Node\sailsv1test\node_modules\@sailshq\lodash\lib\index.js:3228:15
    at baseForOwn (D:\Node\sailsv1test\node_modules\@sailshq\lodash\lib\index.js:2199:14)
    at D:\Node\sailsv1test\node_modules\@sailshq\lodash\lib\index.js:3198:18
    at Function.<anonymous> (D:\Node\sailsv1test\node_modules\@sailshq\lodash\lib\index.js:3501:13)
    at normalizeCollection (D:\Node\sailsv1test\node_modules\waterline-schema\lib\waterline-schema\schema.js:157:7)
    at arrayEach (D:\Node\sailsv1test\node_modules\@sailshq\lodash\lib\index.js:1439:13)
    at Function.<anonymous> (D:\Node\sailsv1test\node_modules\@sailshq\lodash\lib\index.js:3500:13)
    at schemaBuilder (D:\Node\sailsv1test\node_modules\waterline-schema\lib\waterline-schema\schema.js:33:5)
    at new WaterlineSchema (D:\Node\sailsv1test\node_modules\waterline-schema\lib\waterline-schema.js:35:12)
    at Object.initialize (D:\Node\sailsv1test\node_modules\waterline\lib\waterline.js:133:24)
```

According to the [docs](http://sailsjs.com/documentation/concepts/models-and-orm/validations) this should be possible, at least follwing the `unique` example at top. Side note: _there's no validations example for listed validators_. 

Following the [waterline docs](https://github.com/balderdashy/waterline-docs/blob/master/models/validations.md) (another side note: the [Anchor Validations](https://github.com/sailsjs/anchor/blob/master/lib/match/rules.js) link is dead) it should be okay to use it like `attribute: { validationName: true }`, __but__:

[valid-attribute-properties.js (from waterline-schema)](https://github.com/balderdashy/waterline-schema/blob/master/accessible/valid-attribute-properties.js) just contains `validations`, not any of the validators listed in the docs, which kinda explains the error. This brought me to the idea of either using attribute validators either as object or as array (didn't find anything in the docs about this ominous `validations` keyword):

```
module.exports = {
  attributes: {
    test: {
      type: 'string',
      validations: {
        alphanumeric: true
      }
    }
  }
}

// or

module.exports = {
  attributes: {
    test: {
      type: 'string',
      validations: ['alphanumeric']
    }
  }
}
```

Both attempts lead to:

```
error: A hook (`orm`) failed to load!
error:
error: TypeError: Cannot read property 'expectedTypes' of undefined
    at D:\Node\sailsv1test\node_modules\sails-hook-orm\lib\validate-model-def.js:294:27
    at arrayEach (D:\Node\sailsv1test\node_modules\lodash\index.js:1289:13)
    at Function.<anonymous> (D:\Node\sailsv1test\node_modules\lodash\index.js:3345:13)
    at updateProperties (D:\Node\sailsv1test\node_modules\sails-hook-orm\lib\validate-model-def.js:292:7)
    at D:\Node\sailsv1test\node_modules\lodash\index.js:3073:15
    at baseForOwn (D:\Node\sailsv1test\node_modules\lodash\index.js:2046:14)
    at D:\Node\sailsv1test\node_modules\lodash\index.js:3043:18
    at Function.<anonymous> (D:\Node\sailsv1test\node_modules\lodash\index.js:3346:13)
    at validateModelDef (D:\Node\sailsv1test\node_modules\sails-hook-orm\lib\validate-model-def.js:159:5)
    at D:\Node\sailsv1test\node_modules\sails-hook-orm\lib\initialize.js:393:36
    at arrayEach (D:\Node\sailsv1test\node_modules\lodash\index.js:1289:13)
    at Function.<anonymous> (D:\Node\sailsv1test\node_modules\lodash\index.js:3345:13)
    at async.auto._normalizeModelDefs (D:\Node\sailsv1test\node_modules\sails-hook-orm\lib\initialize.js:391:11)
    at runTask (D:\Node\sailsv1test\node_modules\async\dist\async.js:1660:17)
    at D:\Node\sailsv1test\node_modules\async\dist\async.js:1602:17
    at processQueue (D:\Node\sailsv1test\node_modules\async\dist\async.js:1612:17)
```

I still think that the initial attempt, `attribute: { validationName: ... }` is the right approach, since custom validators are used the same way.

Maybe it's just too late, but something's wrong here I guess.

**Comment by mikermcneil** [comment]
@nehalist Thanks for the heads up-- looking into it

**Comment by mikermcneil** [comment]
@nehalist Oops, my bad-- I hadn't realized you were using the v1.0 prerelease.  Would you try running `rm -rf node_modules && npm install`?  

If that doesn't solve the problem, would you post your `sails-hook-orm` version?  Now that the standalone hooks have been federated, they're direct dependencies of your app.  

_(Note to self:  update the issue template accordingly and consider finally doing that little command that spits out all the versions of all the things, prbly borrowing some of the code from `kit deps`)_

**Comment by nehalist** [comment]
Re-installing npm dependencies didn't help, errors remain the same. `sails-hook-orm` version is `2.0.0-5`. And just in case:

- Waterline `0.13.0-3`
- Waterline schema `1.0.0-2`
- Anchor `1.1.1`

**Comment by sgress454** [comment]
Hi @nehalist, this is a bad error message on our part.  The `alphanumeric` validation is no longer supported in Sails 1.0.  We're updating this now so that the error message will better explain what's going on, and suggest that you use the `custom` validation instead; in your case something like:

```
test: {
  type: 'string',
  custom: function (val) {
    return /^[0-9A-Z]+$/i.test(val);
  }
}
```

or, since the test can be done with a regex, you could do:
```
test: {
  type: 'string',
  regex: /^[0-9A-Z]+$/i
}
```


The current (in-development) Sails 1.0 documentation is at https://github.com/balderdashy/sails-docs/tree/1.0.  The list of Sails 1.0 validations is at https://github.com/balderdashy/sails-docs/blob/1.0/concepts/ORM/Validations.md.

Thanks for the heads-up!

**Comment by sgress454** [comment]
Also, if you have any suggestion for how we can improve the error message in [waterline-schema](https://github.com/balderdashy/waterline-schema/blob/b942db061981cb8299f3a460a43dbbdc7d600f48/lib/waterline-schema/schema.js#L224) when the attribute really _does_ have an unrecognized property (as opposed to a no-longer-supported validation), please let us know or do a PR!

**Comment by nehalist** [comment]
Oh, didn't know that. I guess the way you've handled the `email` validation should be fine for removed or changed validations:

```
debug: The `email` validation is now `isEmail`.
debug: Please add it as `validations: { isEmail: true }` instead.
```
