### ISSUE TITLE
"Callback was already called" in unique model attributes

### ISSUE THREAD

**Issue by nehalist** [balderdashy/sails#3970]
**Sails version**: v1.0.0-19
**Node version**: v6.3.0
**NPM version**: v3.10.8
**Operating system**: Win10

<hr/>

Not specifying `required` in `unique` model attributes cause the actual error

```
error: A hook (`orm`) failed to load!
error:
error: Error:
In attribute `username` of model `user`:
When using sails-disk, any attribute with `unique: true` must also have `required: true`
```

to get lost and instead this shows up:
```
error: A hook (`orm`) failed to load!
D:\Node\sailstest\node_modules\async\dist\async.js:844
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at D:\Node\sailstest\node_modules\async\dist\async.js:844:36
    at D:\Node\sailstest\node_modules\sails-disk\index.js:130:24
    at D:\Node\sailstest\node_modules\@sailshq\lodash\lib\index.js:3228:15
    at baseForOwn (D:\Node\sailstest\node_modules\@sailshq\lodash\lib\index.js:2199:14)
    at D:\Node\sailstest\node_modules\@sailshq\lodash\lib\index.js:3198:18
    at Function.<anonymous> (D:\Node\sailstest\node_modules\@sailshq\lodash\lib\index.js:3501:13)
    at D:\Node\sailstest\node_modules\sails-disk\index.js:119:13
    at D:\Node\sailstest\node_modules\async\dist\async.js:3047:20
    at eachOfArrayLike (D:\Node\sailstest\node_modules\async\dist\async.js:1002:13)
    at eachOf (D:\Node\sailstest\node_modules\async\dist\async.js:1052:9)
    at Object.eachLimit (D:\Node\sailstest\node_modules\async\dist\async.js:3111:7)
    at D:\Node\sailstest\node_modules\sails-disk\index.js:98:15
    at Object._configuredExits.success (D:\Node\sailstest\node_modules\machinepack-fs\node_modules\machine\lib\Machine.constructor.js:344:14)
    at afterwards (D:\Node\sailstest\node_modules\machinepack-fs\node_modules\machine\lib\intercept-exit-callbacks.js:160:21)
    at Timeout._onTimeout (D:\Node\sailstest\node_modules\machinepack-fs\node_modules\machine\lib\intercept-exit-callbacks.js:111:20)
    at tryOnTimeout (timers.js:224:11)
```

Can be easily reproduced by having a model like

```
attributes: {
    username: {
      type: 'string',
      unique: true,
    },
    email: {
      type: 'string',
      unique: true,
      isEmail: true,
    },
    passports: {
      collection: 'Passport',
      via: 'user'
    }
  },
```

Adding `required: true` to either `username` or `email` causes the error to change (from "callback already called" to "attribute must have required: true").

It's just about error labels, but this can be a bit tricky to find.

**Comment by sgress454** [comment]
Hi @nehalist, thanks for trying out Sails 1.0.  Can you try upgrading to the latest version of `sails-hook-orm` in your project and trying again?

```
npm install sails-hook-orm@beta --force
```

I can't reproduce this behavior with the latest version (2.0.0-9).  Thanks!

**Comment by tobernguyen** [comment]
I can confirm that the problem solved with the following deps:
```
sails-hook-orm: 2.0.0-12
sails-postgresql: 1.0.0-8
```

**Comment by sgress454** [comment]
Thanks @tobernguyen!
