### ISSUE TITLE
skipper-adapter-tests: Wrong path in test on Windows

### ISSUE THREAD

**Issue by mikermcneil** [balderdashy/sails#4212]
_From @disharmonized on March 20, 2015 12:10_

During the test '/file-metadata.test.js' we have got not passing test with such output in Windows:

```
 after uploading a file using this adapter, Skipper each file metadata object file descriptor (`fd`) should be within the specified `dirname` if one was provided:
     AssertionError: Expected fd (C:\tmp\avatar-uploads\ddd8cfd8-436f-4b55-b6e8-350f6911bdb7.7302) to be inside the specified dirname (/tmp/avatar-uploads)
      at C:\git\skipper-disk\node_modules\skipper-adapter-tests\tests\file-metadata.test.js:80:13
      at Function.forEach (C:\git\skipper-disk\node_modules\lodash\dist\lodash.js:3297:15)
      at Context.<anonymous> (C:\git\skipper-disk\node_modules\skipper-adapter-tests\tests\file-metadata.test.js:77:11)
      at callFn (C:\git\skipper-disk\node_modules\skipper-adapter-tests\node_modules\mocha\lib\runnable.js:223:21)
      at Test.Runnable.run (C:\git\skipper-disk\node_modules\skipper-adapter-tests\node_modules\mocha\lib\runnable.js:216:7)
      at Runner.runTest (C:\git\skipper-disk\node_modules\skipper-adapter-tests\node_modules\mocha\lib\runner.js:374:10)
      at C:\git\skipper-disk\node_modules\skipper-adapter-tests\node_modules\mocha\lib\runner.js:452:12
      at next (C:\git\skipper-disk\node_modules\skipper-adapter-tests\node_modules\mocha\lib\runner.js:299:14)
      at C:\git\skipper-disk\node_modules\skipper-adapter-tests\node_modules\mocha\lib\runner.js:309:7
      at next (C:\git\skipper-disk\node_modules\skipper-adapter-tests\node_modules\mocha\lib\runner.js:247:23)
```

It seems to be that dirname has wrong slashes or whatever, [link to source](https://github.com/balderdashy/skipper-adapter-tests/blob/master/tests/file-metadata.test.js#L80):

```
var expectedDirname = '/tmp/avatar-uploads';
assert(obj.fd.indexOf(expectedDirname) === 0, require('util').format('Expected fd (%s) to be inside the specified dirname (%s)', obj.fd, expectedDirname));
```

Btw i think you should check other tests for such behaviour (we found it [here](https://github.com/balderdashy/skipper-adapter-tests/blob/master/tests/file-metadata.test.js#L94), [here](https://github.com/balderdashy/skipper-adapter-tests/blob/master/tests/file-metadata.test.js#L109))

_Copied from original issue: balderdashy/skipper-adapter-tests#1_

**Comment by mikermcneil** [comment]
Thanks for the heads up, @disharmonized.  We'll get around to tweaking this when we can (if any windows users have time to send a PR w/ a patch in the mean time, that'd be awesome!)

**Comment by mikermcneil** [comment]
update: skipper-adapter-tests will be getting some more love over the next week or so.  Tracked in https://trello.com/c/qHH4x1zc

**Comment by mikermcneil** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [INTERNAL TASK: update skipper adapter tests](https://trello.com/c/qHH4x1zc/305-internal-task-update-skipper-adapter-tests)
