### ISSUE TITLE
Difficult debugging inside of controllers, limited stack trace

### ISSUE THREAD

**Issue by drj-io** [balderdashy/sails#4400]
**Sails version**: 1.0.1
**Node version**: 9.11.1
**NPM version**: 6.0.0
**DB adapter name**: N/A disk/mysql
**DB adapter version**: N/A 
**Operating system**: osx/ubuntu

<hr/>

It was suggested I submit this here.  Given a pretty basic controller file, it's pretty difficult for us to stack trace down to typical syntax and type errors.  With this controller:

```javascript
module.exports = {
  forestay: require('sails-generate-forestay').forestay.router,
  test:function(req,res){
    Car.find().exec(function(err,car){
      car.forEach(function(c){
        console.log(foo)
      })
      res.send('we found some things', car.length)
    })
  }
}
```

the `.find` returns a result, but `foo` is not defined.  Obviously this would need to be fixed. but the stack trace shows:
```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
WARNING: Something seems to be wrong with this function.
It is trying to signal that it has finished AGAIN, after
already resolving/rejecting once.
(silently ignoring this...)

To assist you in hunting this down, here is a stack trace:
```
    at Object.releaseConnection (/Users/david/dev/sgf-test/node_modules/sails-mysql/helpers/private/connection/release-connection.js:27:9)
    at runQueryCb (/Users/david/dev/sgf-test/node_modules/sails-mysql/helpers/select.js:150:28)
    at Object.success (/Users/david/dev/sgf-test/node_modules/sails-mysql/helpers/private/query/run-query.js:127:14)
    at /Users/david/dev/sgf-test/node_modules/machine/lib/private/help-build-machine.js:1354:30
    at _tryToRunCb (/Users/david/dev/sgf-test/node_modules/parley/lib/private/Deferred.js:520:18)
    at /Users/david/dev/sgf-test/node_modules/parley/lib/private/Deferred.js:755:16
    at /Users/david/dev/sgf-test/node_modules/machine/lib/private/help-build-machine.js:966:24
    at Function.handlerCbs.success (/Users/david/dev/sgf-test/node_modules/machine/lib/private/help-build-machine.js:826:26)
    at Query.query [as _callback] (/Users/david/dev/sgf-test/node_modules/machinepack-mysql/machines/send-native-query.js:320:20)
    at Query.Sequence.end (/Users/david/dev/sgf-test/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/Users/david/dev/sgf-test/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.EofPacket (/Users/david/dev/sgf-test/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
    at Protocol._parsePacket (/Users/david/dev/sgf-test/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/david/dev/sgf-test/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/Users/david/dev/sgf-test/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/david/dev/sgf-test/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
```

 [?] For more help, visit https://sailsjs.com/support
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

what I'd really be looking for is 
`ReferenceError: foo is not defined`

With a line number.  

Obviously it would be great if I could write my code correctly the first time.  Sometimes this works

> Please work first try!!! 

And if it does, I get a cookie.  If it doesn't, I fix the issue.  And then I get a cookie!

More cookies!

Thanks!

**Comment by drj-io** [comment]
Another thing that I'd like to mention is that the error just stops the request route in it's tracks, so the user never sees a response.  Ideally, syntax errors like these would result in some sort of `serverError` like message for the user.

**Comment by drj-io** [comment]
as another note, I see this stuff a lot in policies and models, too.

**Comment by mikermcneil** [comment]
@drj-io thanks for writing that up -- what release of sails-mysql are you on?

**Comment by drj-io** [comment]
@mikermcneil any update on this? It's pretty frustrating.  I've tried to look into it a little bit but I'm not really sure where to start...

**Comment by drj-io** [comment]
@mikermcneil see https://github.com/balderdashy/sails-mysql/pull/352

**Comment by wulfsolter** [comment]
This is duplicate of my earlier issue https://github.com/balderdashy/sails/issues/4377 which includes workaround and what to do to fix it properly (Mike's PR on my replication repo, last comment)

If you're unsure of where to start, try looking at existing issues. 😉

**Comment by krishna0102** [comment]
sails-mongo has also same issues

**Comment by mikermcneil** [comment]
@wulfsolter 🙌 

direct link: https://github.com/wulfsolter/stack-swallow-test/pull/1/files

**Comment by saif-git** [comment]
I can not release this issue I also have the some problem with sails 1.0.2 any help please

**Comment by hebusa** [comment]
That's really nasty for migrating an old project.

**Comment by drj-io** [comment]
@mikermcneil I hate to be persistent on this one. I understand that going to async/await is a preferred way to fix this, but keep in mind that callback structured javascript is still valid javascript... Even you said that we should be able to expect an appropriate stack trace for debugging.

For now my mysql hack in my PR balderdashy/sails-mysql#352 seems to give me a more reliable stack trace, which has probably saved me days of debugging.  Does that patch have any caveats? 

Let me know if I'm missing something. And thank you.

**Comment by johnabrams7** [comment]
@drj-io  Thanks for the [PR mysql hack ](https://github.com/balderdashy/sails-mysql/pull/352) that provides a workaround for the stack trace.  I welcome everyone else's thoughts and tests on this one too.

**Comment by wulfsolter** [comment]
The hack should not be considered for merging. The PR'd hack does not actually address the cause of problem - `parley` not logging the error correctly - nor does it even work for all people (everyone else running a non-MySQL database, including the default `sails-disk`, Mongo, Postgres etc) and only works for a limited number of people.

The problem is that when using old callback-style DB calls like `Model.action(...).exec()` is that `parley` is discarding `errCbArg` - the original error argument - instead of logging the error out, the first method argument (errCbArg) is never used as can be seen in code linked immediately below. 
https://github.com/mikermcneil/parley/blob/5a52095c3d922984348df444ff35656addf04d4a/lib/private/Deferred.js#L785-L813

Functional patch to `parley` referenced above, but will link it here in comments too https://github.com/mikermcneil/parley/pull/6/files
