### ISSUE TITLE
process.nextTick(function() { throw err; });  ReferenceError: users is not defined

### ISSUE THREAD

**Issue by SpaceG** [balderdashy/sails#4404]
Hello, I'm back here. want to start my small app. got this. : whats that mean with ?

```
    process.nextTick(function() { throw err; });
                                  ^
ReferenceError: users is not defined
```

here is my  sails lift : 

```
codes-Mac-mini:oauthy Kopie jh$ sails lift

 info: Starting app...

debug: In attribute `state` of  model `user`:
debug:   The `enum` validation rule is now `isIn` (changing it for you this time).

debug: In attribute `provider` of  model `user`:
debug:   The `enum` validation rule is now `isIn` (changing it for you this time).

 info: ·• Auto-migrating...  (alter)
 info:    Hold tight, this could take a moment.
 info:  ✓ Auto-migration complete.

 info: 
 info:                .-..-.
 info: 
 info:    Sails              <|    .-..-.
 info:    v1.0.1              |\
 info:                       /|.\
 info:                      / || \
 info:                    ,'  |'  \
 info:                 .-'.-==|/_--'
 info:                 `--'-------' 
 info:    __---___--___---___--___---___--___
 info:  ____---___--___---___--___---___--___-__
 info: 
 info: Server lifted in `/Users/jh/Desktop/new/oauthy Kopie`
 info: To shut down Sails, press <CTRL> + C at any time.
 info: Read more at https://sailsjs.com/support.

debug: -------------------------------------------------------
debug: :: Mon May 14 2018 12:16:42 GMT+0200 (CEST)

debug: Environment : development
debug: Port        : 1337
debug: -------------------------------------------------------
/Users/jh/Desktop/new/oauthy Kopie/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

ReferenceError: users is not defined
    at /Users/jh/Desktop/new/oauthy Kopie/config/passport.js:17:13
    at _afterPotentiallyRunningAfterLC (/Users/jh/Desktop/new/oauthy Kopie/node_modules/waterline/lib/waterline/methods/find-one.js:328:20)
    at _maybeRunAfterLC (/Users/jh/Desktop/new/oauthy Kopie/node_modules/waterline/lib/waterline/methods/find-one.js:322:20)
    at _afterFetchingRecords (/Users/jh/Desktop/new/oauthy Kopie/node_modules/waterline/lib/waterline/methods/find-one.js:324:13)
    at _afterGettingPopulatedPhysicalRecords (/Users/jh/Desktop/new/oauthy Kopie/node_modules/waterline/lib/waterline/utils/query/help-find.js:754:12)
    at /Users/jh/Desktop/new/oauthy Kopie/node_modules/waterline/lib/waterline/utils/query/help-find.js:151:16
    at /Users/jh/Desktop/new/oauthy Kopie/node_modules/sails-mongo/lib/private/do-with-connection.js:239:16
    at /Users/jh/Desktop/new/oauthy Kopie/node_modules/sails-mongo/lib/private/do-with-connection.js:123:18
    at Object.success (/Users/jh/Desktop/new/oauthy Kopie/node_modules/sails-mongo/lib/private/build-std-adapter-method.js:61:47)
    at afterMaybeArtificiallyWaiting (/Users/jh/Desktop/new/oauthy Kopie/node_modules/sails-mongo/node_modules/machine/lib/private/intercept-exit-callbacks.js:406:21)
    at maybeArtificiallyWait (/Users/jh/Desktop/new/oauthy Kopie/node_modules/sails-mongo/node_modules/machine/lib/private/intercept-exit-callbacks.js:220:20)
    at afterPotentiallyCaching (/Users/jh/Desktop/new/oauthy Kopie/node_modules/sails-mongo/node_modules/machine/lib/private/intercept-exit-callbacks.js:240:11)
    at _cacheIfAppropriate (/Users/jh/Desktop/new/oauthy Kopie/node_modules/sails-mongo/node_modules/machine/lib/private/intercept-exit-callbacks.js:98:18)
    at Function._interceptExit [as success] (/Users/jh/Desktop/new/oauthy Kopie/node_modules/sails-mongo/node_modules/machine/lib/private/intercept-exit-callbacks.js:111:9)
    at findCb (/Users/jh/Desktop/new/oauthy Kopie/node_modules/sails-mongo/lib/private/machines/find-records.js:138:20)
    at handleCallback (/Users/jh/Desktop/new/oauthy Kopie/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:120:56)
    at /Users/jh/Desktop/new/oauthy Kopie/node_modules/sails-mongo/node_modules/mongodb/lib/cursor.js:860:16
    at handleCallback (/Users/jh/Desktop/new/oauthy Kopie/node_modules/sails-mongo/node_modules/mongodb-core/lib/cursor.js:171:5)
    at setCursorDeadAndNotified (/Users/jh/Desktop/new/oauthy Kopie/node_modules/sails-mongo/node_modules/mongodb-core/lib/cursor.js:505:3)
    at nextFunction (/Users/jh/Desktop/new/oauthy Kopie/node_modules/sails-mongo/node_modules/mongodb-core/lib/cursor.js:651:7)
    at Cursor.next [as _next] (/Users/jh/Desktop/new/oauthy Kopie/node_modules/sails-mongo/node_modules/mongodb-core/lib/cursor.js:692:3)
    at fetchDocs (/Users/jh/Desktop/new/oauthy Kopie/node_modules/sails-mongo/node_modules/mongodb/lib/cursor.js:856:10)
codes-Mac-mini:oauthy Kopie jh$ 
```

here is my package.json file : 

```
{
  "name": "oauthy",
  "private": true,
  "version": "0.0.0",
  "description": "a Sails application",
  "keywords": [],
  "dependencies": {
    "@sailshq/connect-redis": "^3.2.1",
    "@sailshq/lodash": "^3.10.3",
    "@sailshq/socket.io-redis": "^5.2.0",
    "async": "2.0.1",
    "bcrypt": "^2.0.1",
    "bcrypt-nodejs": "0.0.3",
    "grunt": "1.0.1",
    "jsonwebtoken": "^8.2.1",
    "mongodb": "^3.0.7",
    "passport": "^0.4.0",
    "passport-github2": "^0.1.11",
    "passport-local": "^1.0.0",
    "passport-twitter": "^1.0.4",
    "sails": "^1.0.1",
    "sails-hook-grunt": "^3.0.2",
    "sails-hook-orm": "^2.0.0-16",
    "sails-hook-sockets": "^1.4.0",
    "sails-mongo": "^1.0.0"
  },
  "devDependencies": {
    "@sailshq/eslint": "^4.19.3"
  },
  "scripts": {
    "start": "NODE_ENV=production node app.js",
    "test": "npm run lint && npm run custom-tests && echo 'Done.'",
    "lint": "eslint . --max-warnings=0 --report-unused-disable-directives && echo '✔  Your .js files look good.'",
    "custom-tests": "echo \"(No other custom tests yet.)\" && echo"
  },
  "main": "app.js",
  "repository": {
    "type": "git",
    "url": "git://github.com/jh/oauthy.git"
  },
  "author": "jh",
  "license": "",
  "engines": {
    "node": ">=8.10"
  }
}

```

**Sails version*1.0.1*:
**Node version*v8.10.0*:
**NPM version*6.0.0*:
**DB adapter name*sails-mongo*: N/A
**DB adapter version**: N/A
**Operating system**:

**Comment by NachtRitter** [comment]
Main error information in part with text:
> ReferenceError: users is not defined
    at /Users/jh/Desktop/new/oauthy Kopie/config/passport.js:17:13

You use undefined variable `users` in the file config/passport.js at the line 17.

**Comment by NachtRitter** [comment]
Also remember, that github issues are for bug reporting.
This is not a bug. This is your mistake.
Please use stackoverflow for such questions.

**Comment by mikermcneil** [comment]
@NachtRitter @SpaceG 🙇
