### ISSUE TITLE
"message": "Could not render view \"\".  Tried locating view file @ \"

### ISSUE THREAD

**Issue by SpaceG** [balderdashy/sails#4426]
Hello SailsJS World.

I got this error back after acceptance the oauth for facebook, when i want callback to the homepage or startpage! would be great to get fit with it. here is my stackoverflow!! [https://stackoverflow.com/questions/50589084/sailsjs-message-could-not-render-view-e-view-failed-status-500](https://stackoverflow.com/questions/50589084/sailsjs-message-could-not-render-view-e-view-failed-status-500)

```
{
  "message": "Could not render view \"\".  Tried locating view file @ \"/Users/jh/Desktop/new/oauthy Kopie/views\". Layout configured as \"layout\", so tried using layout @ \"/Users/jh/Desktop/new/oauthy Kopie/views/layout\")",
  "code": "E_VIEW_FAILED",
  "status": 500,
  "view": {
    "defaultEngine": "ejs",
    "ext": ".ejs",
    "name": "",
    "root": "/Users/jh/Desktop/new/oauthy Kopie/views"
  }
}

```

and this is my AuthController.js file 

```

// oAuth beginning here 

facebook: function(req, res){

  passport.authenticate('facebook')(req,res);

},

facebookCallback: function(req, res){
  
   passport.authenticate('facebook', { failureRedirect: '/login' }, function(err, user) {
    req.logIn(user, function(err) {

      if (err) {
        console.log(err);
        res.view('/');
        return;
      }


      res.redirect('/');
      return;
    });
  })(req, res);

},


};

```

in this case when i remove this part 

```
      if (err) {
        console.log(err);
        res.view('/');
        return;
      }

```

does it work, but this isn't the right way, where i have to include the view files? and which view files are missing there? 

in my sailsjs app , the structure are like this

`Views=>Pages=>homepage.ejs`

and the layouts like below 

`Views=>layouts=>layout.ejs`

and this also my terminal

```
codes-Mac-mini:oauthy Kopie jh$ sails lift

 info: Starting app...

 info: ·• Auto-migrating...  (alter)
 info:    Hold tight, this could take a moment.
 info:  ✓ Auto-migration complete.

 info: 
 info:                .-..-.
 info: 
 info:    Sails              <|    .-..-.
 info:    v1.0.1              |\
 info:                       /|.\
 info:                      / || \
 info:                    ,'  |'  \
 info:                 .-'.-==|/_--'
 info:                 `--'-------' 
 info:    __---___--___---___--___---___--___
 info:  ____---___--___---___--___---___--___-__
 info: 
 info: Server lifted in `/Users/jh/Desktop/new/oauthy Kopie`
 info: To shut down Sails, press <CTRL> + C at any time.
 info: Read more at https://sailsjs.com/support.

debug: -------------------------------------------------------
debug: :: Tue May 29 2018 18:00:30 GMT+0200 (CEST)

debug: Environment : development
debug: Port        : 1337
debug: -------------------------------------------------------
TypeError: Cannot read property 'id' of undefined
    at /Users/jh/Desktop/new/oauthy Kopie/config/passport.js:17:17
    at pass (/Users/jh/Desktop/new/oauthy Kopie/node_modules/passport/lib/authenticator.js:294:9)
    at Authenticator.serializeUser (/Users/jh/Desktop/new/oauthy Kopie/node_modules/passport/lib/authenticator.js:299:5)
    at SessionManager.logIn (/Users/jh/Desktop/new/oauthy Kopie/node_modules/passport/lib/sessionmanager.js:14:8)
    at IncomingMessage.req.login.req.logIn (/Users/jh/Desktop/new/oauthy Kopie/node_modules/passport/lib/http/request.js:50:33)
    at /Users/jh/Desktop/new/oauthy Kopie/api/controllers/AuthController.js:94:9
    at Strategy.strategy.error (/Users/jh/Desktop/new/oauthy Kopie/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at /Users/jh/Desktop/new/oauthy Kopie/node_modules/passport-oauth2/lib/strategy.js:197:27
    at /Users/jh/Desktop/new/oauthy Kopie/node_modules/passport-facebook/lib/strategy.js:181:5
    at passBackControl (/Users/jh/Desktop/new/oauthy Kopie/node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (/Users/jh/Desktop/new/oauthy Kopie/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
error: Sending 500 ("Server Error") response: 
 Could not render view "".  Tried locating view file @ "/Users/jh/Desktop/new/oauthy Kopie/views". Layout configured as "layout", so tried using layout @ "/Users/jh/Desktop/new/oauthy Kopie/views/layout")
debug: ***********************************************************************************
debug: `res.jsonx()` is deprecated in Sails v1.0 and will be removed in a future release.
debug: Any files in `api/responses/` that haven't been customized can simply be removed.
debug: Otherwise see http://sailsjs.com/upgrading for options to replace `res.jsonx()`.
debug: (jsonx was called from `serverError`)
debug: ***********************************************************************************


```

and here is my views.js file!!!!!!

```

/**
 * View Engine Configuration
 * (sails.config.views)
 *
 * Server-sent views are a secure and effective way to get your app up
 * and running. Views are normally served from actions.  Below, you can
 * configure your templating language/framework of choice and configure
 * Sails' layout support.
 *
 * For details on available options for configuring server-side views, check out:
 * https://sailsjs.com/config/views
 *
 * For more background information on views and partials in Sails, check out:
 * https://sailsjs.com/docs/concepts/views
 */

module.exports.views = {

  /***************************************************************************
  *                                                                          *
  * Extension to use for your views. When calling `res.view()` in an action, *
  * you can leave this extension off. For example, calling                   *
  * `res.view('homepage')` will (using default settings) look for a          *
  * `views/homepage.ejs` file.                                               *
  *                                                                          *
  ***************************************************************************/

  extension: 'ejs',

  /***************************************************************************
  *                                                                          *
  * The path (relative to the views directory, and without extension) to     *
  * the default layout file to use, or `false` to disable layouts entirely.  *
  *                                                                          *
  * Note that layouts only work with the built-in EJS view engine!           *
  *                                                                          *
  ***************************************************************************/

  layout: 'layout'

};


```

**Sails version*1.0.1*:
**Node version*v8.10.0*:
**NPM version*6.0.0*:
**DB adapter name*sails-mongo*: N/A
**DB adapter version**: N/A
**Operating system**:

**Comment by Alienigenaro** [comment]
try something like this:
 res.view('\\homepage')
 res.view('\\pages\\homepage')
 res.view('\\pages\\yourpagename')
