### ISSUE TITLE
Temporary endpoint message from amazon causes uncaught error

### ISSUE THREAD

**Issue by jopdorp** [balderdashy/sails#4967]
I'm using skipper to upload an image to amazon in region eu-west-1, I just created a new bucket and this is what happens:
## The code

 req.file('file-0').upload({
        adapter: require('skipper-s3'),
        key: sails.config.s3.key,
        secret: sails.config.s3.secret,
        bucket: sails.config.s3.bucket
      }, function (err, filesUploaded) {
        if (err) return res.negotiate(err);
        return res.ok({path: filesUploaded[0].extra.Location});
      });
## Error that crashes the server:

Error: Uncaught, unspecified "error" event. (Unable to initiate stream upload [Error: Unexpected response from AWS:{ Code: 'TemporaryRedirect',
  Message: 'Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.',
  Bucket: 'tosti-rsvp-acc',
  Endpoint: 'tosti-rsvp-acc.s3-eu-west-1.amazonaws.com',
  RequestId: 'D1059082E6952443',
  HostId: 'mGQ4covV5auLKJE1zy2sX8zujSHRz4ETotqdd3khJ8kzRnCER2U5pFzMK4PxW2tDVJwbs4tLaPc=' })
    at Writable.emit (events.js:157:17)
    at /home/bitnami/programtable/node_modules/skipper-s3/index.js:259:22
    at PassThrough.<anonymous> (/home/bitnami/programtable/node_modules/knox-mpu-alt/lib/multipartupload.js:328:16)
    at emitOne (events.js:95:20)
    at PassThrough.emit (events.js:182:7)
    at /home/bitnami/programtable/node_modules/skipper/standalone/Upstream/prototype.fatalIncomingError.js:83:17
    at Function.forEach (/home/bitnami/programtable/node_modules/lodash/dist/lodash.js:3298:15)
    at lodash.ctor.(anonymous function) [as each](/home/bitnami/programtable/node_modules/lodash/dist/lodash.js:5925:31)
    at Upstream.fatalIncomingError (/home/bitnami/programtable/node_modules/skipper/standalone/Upstream/prototype.fatalIncomingError.js:55:18)
    at Writable.unableToUpload (/home/bitnami/programtable/node_modules/skipper/standalone/Upstream/prototype.upload.js:143:10)
    at Writable.g (events.js:273:16)
    at emitOne (events.js:95:20)
    at Writable.emit (events.js:182:7)
    at /home/bitnami/programtable/node_modules/skipper-s3/index.js:259:22
    at /home/bitnami/programtable/node_modules/knox-mpu-alt/lib/multipartupload.js:217:42
    at /home/bitnami/programtable/node_modules/knox-mpu-alt/lib/multipartupload.js:131:18
    at Parser.<anonymous> (/home/bitnami/programtable/node_modules/knox-mpu-alt/node_modules/xml2js/lib/xml2js.js:255:20)
    at emitOne (events.js:90:13)
    at Parser.emit (events.js:182:7)
    at Object.saxParser.onclosetag (/home/bitnami/programtable/node_modules/knox-mpu-alt/node_modules/xml2js/lib/xml2js.js:225:24)
    at emit (/home/bitnami/programtable/node_modules/knox-mpu-alt/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/home/bitnami/programtable/node_modules/knox-mpu-alt/node_modules/sax/lib/sax.js:620:3)
error: Forever detected script exited with code: 1
error: Script restart attempt #15
Not attaching EB to window
## The possible solution:

Re-send this request to the specified temporary endpoint like amazon suggests

**Comment by blk-niranjan** [comment]
i'm getting same error, can someone suggest a solution?

**Comment by blk-ayush** [comment]
hi, i'm getting same error. Can someone suggest some soln?
