### ISSUE TITLE
Model attribute: The property columnType isn't a recognized property.

### ISSUE THREAD

**Issue by mickelindahl** [balderdashy/sails#5249]
[example.zip](https://github.com/balderdashy/waterline/files/1596669/example.zip)

**Waterline version**: 0.13.1-9
**Node version**:8.9.3
**NPM version**: 5.6.0
**Operating system**: debian 9

<hr/>

Reading here https://libupdate.com/libs/5b73bab9-7c91-4ab6-8cea-ebeb3aacd925 i understand it as model attributes should in this waterline version have the property columnType to indicate how the value should be stored in the datanase (e.g INTEGER or DATETIME in sql db). However i receive the following error when defining a simple model

```
let model = Waterline.Collection.extend({
        identity: 'arraymodel',
        datastore: 'edgetests',
        attributes: {
            id: { type: 'number', autoMigrations: { autoIncrement: true }},
            date: {type: 'string', columnType:'DATETIME'}
        },
        primaryKey: 'id'
 });
```

{ userError: The attribute `date` on the `arraymodel` model contains invalid properties. The property `columnType` isn't a recognized property.
    at parseProperties (/home/mikael/git/waterline-test/node_modules/waterline-schema/lib/waterline-schema/schema.js:239:48)
    at /home/mikael/git/waterline-test/node_modules/@sailshq/lodash/lib/index.js:3228:15
    at baseForOwn (/home/mikael/git/waterline-test/node_modules/@sailshq/lodash/lib/index.js:2199:14)
    at /home/mikael/git/waterline-test/node_modules/@sailshq/lodash/lib/index.js:3198:18
    at Function.<anonymous> (/home/mikael/git/waterline-test/node_modules/@sailshq/lodash/lib/index.js:3501:13)
    at parseAttributes (/home/mikael/git/waterline-test/node_modules/waterline-schema/lib/waterline-schema/schema.js:237:9)
    at /home/mikael/git/waterline-test/node_modules/@sailshq/lodash/lib/index.js:3228:15
    at baseForOwn (/home/mikael/git/waterline-test/node_modules/@sailshq/lodash/lib/index.js:2199:14)
    at /home/mikael/git/waterline-test/node_modules/@sailshq/lodash/lib/index.js:3198:18
    at Function.<anonymous> (/home/mikael/git/waterline-test/node_modules/@sailshq/lodash/lib/index.js:3501:13)
    at normalizeCollection (/home/mikael/git/waterline-test/node_modules/waterline-schema/lib/waterline-schema/schema.js:158:7)
    at arrayEach (/home/mikael/git/waterline-test/node_modules/@sailshq/lodash/lib/index.js:1439:13)
    at Function.<anonymous> (/home/mikael/git/waterline-test/node_modules/@sailshq/lodash/lib/index.js:3500:13)
    at schemaBuilder (/home/mikael/git/waterline-test/node_modules/waterline-schema/lib/waterline-schema/schema.js:34:5)
    at new WaterlineSchema (/home/mikael/git/waterline-test/node_modules/waterline-schema/lib/waterline-schema.js:36:12)
    at Object.initialize (/home/mikael/git/waterline-test/node_modules/waterline/lib/waterline.js:581:26) name: 'userError' }

Looking into waterline-schema (1.0.0-25 ) I can not find columType in accesable/valid-attribute-properties. 

Thus this seems to be a bug.

### To reproduce
download an unzip

run: npm install && node.index.js

**Comment by MarcosAtApprentice** [comment]
Documentation is still not up to date apparently, documenting `unique`, `isIn`, and `columnType` as root level fields
