### ISSUE TITLE
Permissions error with Mongo Authentication

### ISSUE THREAD

**Issue by dniccum** [balderdashy/sails#5254]
**Waterline version**: 0.12.13
**Node version**: v6.10.3
**NPM version**: 3.10.10
**Operating system**: Ubuntu 16.04.2 LTS

<hr/>

I am attempting to utilize MongoDB authentication for my database. The application lifts as it should, but when I go to insert a new line within the database, I receive this error: 

```
Sending 500 ("Server Error") response:
 Error (E_UNKNOWN) :: Encountered an unexpected error
MongoError: not authorized on quiq-math to execute command { insert: "user", documents: [ { firstName: "Doug", lastName: "Niccum", email: "dniccumdesign@gmail.com", encryptedPassword: "XXXXXX", stripeCustomerId: "placeholder", subscriptionDate: new Date(1532533782121), lastLoggedIn: new Date(0), createdAt: new Date(1500997782152), updatedAt: new Date(1500997782152), _id: ObjectId('597768963a2d172d1a41b34f') } ], ordered: true, writeConcern: { w: 1, fsync: false, wtimeout: 0 } }
    at Function.MongoError.create (/var/www/html/node_modules/mongodb-core/lib/error.js:31:11)
    at commandCallback (/var/www/html/node_modules/mongodb-core/lib/topologies/server.js:1206:66)
    at Callbacks.emit (/var/www/html/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at Connection.messageHandler (/var/www/html/node_modules/mongodb-core/lib/topologies/server.js:371:23)
    at Socket.<anonymous> (/var/www/html/node_modules/mongodb-core/lib/connection/connection.js:301:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```

This is what my production environment configuration looks like:

```
mongoProd: {
      adapter: 'sails-mongo',
      host: 'XX.XXX.XXX.XXX',
      port: XXXXXX,
      username: 'QuiqMath',
      password: 'XXXXXXX',
      database: 'quiq-math',
      authenticationDatabase: 'quiq-math',
      schema: true
    }
```

I have created a Mongo user that looks like this:

```
{
	"_id" : "quiq-math.QuiqMath",
	"user" : "QuiqMath",
	"db" : "quiq-math",
	"roles" : [
		{
			"role" : "readWrite",
			"db" : "quiq-math"
		}
	]
}
```

I can verify that my Sails application can connect to a **remote** database server, as the lift process does not fail, so it is not a firewall issue. I can also verify that credentials provided above do in fact work as I can connect to the database and insert new records via Robo 3T.

Are there known issues with the authentication database attribute?

**Comment by Nielio** [comment]
I got it! Thank you @sgress454 

```javascript
datastores: {

    default: {
      adapter: 'sails-mongo',
      //url: `mongodb://${process.env.DB_USER}:${process.env.DB_PASS}@mongo/${process.env.DB_NAME}`,
      host: 'mongo',
      user: process.env.DB_USER,
      password: process.env.DB_PASS,
      database: process.env.DB_NAME,
      authSource: 'admin', //authenticationDatabase
    },

  },
```
