### ISSUE TITLE
beforeCreate() model not working in bootstrap - proceed is not a function

### ISSUE THREAD

**Issue by abrar71** [balderdashy/sails#7259]
**Node version**: 16.8.0
**Sails version** _(sails)_: 1.5.3
**ORM hook version** _(sails-hook-orm)_: 4.0.2
**Sockets hook version** _(sails-hook-sockets)_: 2.0.3
**Organics hook version** _(sails-hook-organics)_:  2.2.1
<hr/>

I'm using the latest sails to install the sample web app, I changed `migrate` -> `drop` and added the following to `Users.js` model
```javascript
  beforeCreate: async (valuesToSet, proceed) => {
    proceed()
  },
  beforeUpdate: async (valuesToSet, proceed) => {
    proceed()
  },
```
During bootstrap on creating a new record in the model, it gives the following error:
```shell
error: Bootstrap encountered an error: (see below)
error: Failed to lift app: TypeError: proceed is not a function
    at beforeCreate (/home/abr/sails-test/api/models/User.js:171:5)
    at /home/abr/sails-test/node_modules/waterline/node_modules/async/dist/async.js:196:27
    at /home/abr/sails-test/node_modules/waterline/node_modules/async/dist/async.js:74:12
    at /home/abr/sails-test/node_modules/waterline/node_modules/async/dist/async.js:3113:16
    at eachOfArrayLike (/home/abr/sails-test/node_modules/waterline/node_modules/async/dist/async.js:1072:9)
    at eachOf (/home/abr/sails-test/node_modules/waterline/node_modules/async/dist/async.js:1120:5)
    at Object.eachLimit (/home/abr/sails-test/node_modules/waterline/node_modules/async/dist/async.js:3175:5)
    at _maybeRunBeforeLC (/home/abr/sails-test/node_modules/waterline/lib/waterline/methods/create-each.js:207:15)
    at Deferred._.extend._WLModel [as _handleExec] (/home/abr/sails-test/node_modules/waterline/lib/waterline/methods/create-each.js:212:9)
    at Deferred.exec (/home/abr/sails-test/node_modules/parley/lib/private/Deferred.js:286:10)
    at Deferred.tryCatcher (/home/abr/sails-test/node_modules/bluebird/js/release/util.js:11:23)
    at ret (eval at makeNodePromisifiedEval (/home/abr/sails-test/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
    at Deferred.toPromise (/home/abr/sails-test/node_modules/parley/lib/private/Deferred.js:572:19)
    at Deferred.then (/home/abr/sails-test/node_modules/parley/lib/private/Deferred.js:431:22)
```

**Comment by eashaw** [comment]
Thanks for reporting this issue @abrar71. 
We think this was caused by upgrading the `async` dependency. The solution is that you don’t need to call the second argument when calling async functions, we’re looking into fixing this.
