### ISSUE TITLE
Error: Failed to lookup view "main/index"

### ISSUE THREAD

**Issue by dadambickford** [balderdashy/sails#741]
getting this error when trying to go to a fresh clone of a repo that works for @oscargodson and @sebnitu.

```
Error: Failed to lookup view "main/index"
    at Function.app.render (/home/adam/piggybank/node_modules/sails/node_modules/express/lib/application.js:495:17)
    at ServerResponse.res.render (/home/adam/piggybank/node_modules/sails/node_modules/express/lib/response.js:756:7)
    at /home/adam/piggybank/node_modules/sails/lib/hooks/views/index.js:266:24
    at Object.oncomplete (fs.js:107:15)
```

@oscargodson and @sebnitu are both using Mac OSX 10.8, while I am on Ubuntu. The file definitely exists at `views/Main/index.ejs`

**Comment by sunita-kadam** [comment]
thank u very much..
