### ISSUE TITLE
Hook failed to load: orm (When I lift sails on local machine after I linked with mongoDB provided by Heroku)

### ISSUE THREAD

**Issue by TheFinestArtist** [balderdashy/sails#770]
It has some strange error and I can't figure out what it is...

error: Hook failed to load: orm
error: Error encountered while loading Sails core!
error: MongoError: not authorized for query on heroku_app17543428.system.namespaces
    at Object.exports.toError (/Users/TheFinestArtist/Desktop/WatchOut/NodeJS/WatchOut/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/utils.js:108:11)
    at /Users/TheFinestArtist/Desktop/WatchOut/NodeJS/WatchOut/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/cursor.js:634:54
    at Cursor.close (/Users/TheFinestArtist/Desktop/WatchOut/NodeJS/WatchOut/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/cursor.js:889:5)
    at commandHandler (/Users/TheFinestArtist/Desktop/WatchOut/NodeJS/WatchOut/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/cursor.js:634:21)
    at null.<anonymous> (/Users/TheFinestArtist/Desktop/WatchOut/NodeJS/WatchOut/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/db.js:1651:20)
    at g (events.js:175:14)
    at EventEmitter.emit (events.js:106:17)
    at Server.Base._callHandler (/Users/TheFinestArtist/Desktop/WatchOut/NodeJS/WatchOut/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:409:25)
    at /Users/TheFinestArtist/Desktop/WatchOut/NodeJS/WatchOut/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:20
    at MongoReply.parseBody (/Users/TheFinestArtist/Desktop/WatchOut/NodeJS/WatchOut/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:131:5)
    at null.<anonymous> (/Users/TheFinestArtist/Desktop/WatchOut/NodeJS/WatchOut/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:514:22)
    at EventEmitter.emit (events.js:95:17)
    at null.<anonymous> (/Users/TheFinestArtist/Desktop/WatchOut/NodeJS/WatchOut/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:190:13)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/Users/TheFinestArtist/Desktop/WatchOut/NodeJS/WatchOut/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:382:22)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:736:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:526:21)

**Comment by KareemMohamed0** [comment]
d
