### ISSUE TITLE
Error kill ENOSYS

### ISSUE THREAD

**Issue by Vadorequest** [balderdashy/sails#846]
Hi.

When I want shut down my sails running, if I do ctrl+c in the shell, I have this error: (Windows 7 x64)

```
C:\wamp\www\sailsTest1>sails lift
info:
info:
info:    Sails.js           <|
info:    v0.9.4              |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------'
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info:
info: Server lifted in `C:\wamp\www\sailsTest1`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Tue Sep 10 2013 21:15:35 GMT+0200 (Paris, Madrid (heure d'été))
debug:
debug: Environment      : development
debug: Port             : 1337
debug: --------------------------------------------------------
info: handshake authorized xD1VfmvQ7t9r6aQNTOEb
info: handshake authorized _8pME1oR3se_5yagTOEc
debug: Lowering sails...

child_process.js:1016
      throw errnoException(process._errno, 'kill');
            ^
Error: kill ENOSYS
    at errnoException (child_process.js:980:11)
    at ChildProcess.kill (child_process.js:1016:13)
    at kill (C:\Users\Ambroise\AppData\Roaming\npm\node_modules\sails\lib\app\index.js:189:18)
    at Object.forEach (C:\Users\Ambroise\AppData\Roaming\npm\node_modules\sails\node_modules\lodash\dist\lodash.js:2331:15)
    at C:\Users\Ambroise\AppData\Roaming\npm\node_modules\sails\lib\app\index.js:187:9
    at beforeShutdown (C:\Users\Ambroise\AppData\Roaming\npm\node_modules\sails\lib\app\index.js:181:21)
    at bound.Sails.lower (C:\Users\Ambroise\AppData\Roaming\npm\node_modules\sails\lib\app\index.js:183:3)
    at bound (C:\Users\Ambroise\AppData\Roaming\npm\node_modules\sails\node_modules\lodash\dist\lodash.js:491:21)
    at process.<anonymous> (C:\Users\Ambroise\AppData\Roaming\npm\node_modules\sails\lib\app\teardown.js:14:10)
    at process.EventEmitter.emit (events.js:92:17)
    at Signal.wrap.onsignal (node.js:756:46)
Terminer le programme de commandes (O/N) ? o

```

I have upgraded node.js today from 0.8.10 to 0.10.18, I didn't have this error before that, on the same project.

**Comment by ZeeshanVbase** [comment]
Changing SIGHUP to SIGINT fixes it for me.
