### ISSUE TITLE
EventEmitter memory leak

### ISSUE THREAD

**Issue by shobhitsinghal624** [balderdashy/sails#931]
I am seeing these a lot : 

<pre>
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.EventEmitter.addListener (events.js:160:15)
    at Request.init (/home/ubuntu/sails-app/node_modules/request/request.js:368:8)
    at Request.onResponse (/home/ubuntu/sails-app/node_modules/request/request.js:794:10)
    at ClientRequest.g (events.js:175:14)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1689:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:120:23)
    at Socket.socketOnData [as ondata] (http.js:1584:20)
    at TCP.onread (net.js:525:27)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.EventEmitter.addListener (events.js:160:15)
    at Request.start (/home/ubuntu/sails-app/node_modules/request/request.js:612:8)
    at Request.end (/home/ubuntu/sails-app/node_modules/request/request.js:1212:28)
    at /home/ubuntu/sails-app/node_modules/request/request.js:416:12
    at process._tickDomainCallback (node.js:459:13)
</pre>

Any ideas how to resolve the issue.

**Comment by mikermcneil** [comment]
For future reference, there's more information and tips on diagnosing memory leaks in Node apps, and on reproducing+reporting suspected memory leaks in Sails here: https://github.com/balderdashy/sails/issues/3782#issuecomment-238679052
